### ISSUE TITLE
SMART SWITCH TONGOU TO-Q-SY1-JWT

### ISSUE THREAD

**Issue by jvm1000** [Xenomes/Domoticz-TinyTUYA-Plugin#10]
Hello thank for you hard work, please, this smart switch has a problem
https://es.aliexpress.com/item/1005004153509348.html?gatewayAdapt=glo2esp
the black one with power meter

The problem is with the **Switch**, 
the rest is ok (Volt,power,etc)

here are devices in domoticz
Idx | Hardware | ID |                                   Unit |   Name |                                 Type |   SubType |  Data
76 | TinyTuya1 | bf7ed421221e9996b9l2ir | 1 | carril DIN 1 (Unknown Device) | General | Text | On | - | - |   | 2023-01-23 18:29:51
57 | TinyTuya1 | bf7ed421221e9996b9l2ir | 14 | carril DIN 1 (kWh)                  | General   | kWh | 0.357 kWh | - | - |   | 2023-01-23 18:31:02
54 | TinyTuya1 | bf7ed421221e9996b9l2ir | 11 | carril DIN 1 (A)                       | General        | Current | 0.281 A | - | - |   | 2023-01-23 18:29:51
55 | TinyTuya1 | bf7ed421221e9996b9l2ir | 12 | carril DIN 1 (W)                      | Usage         | Electric | 64.6 Watt | - | - |   | 2023-01-23 18:29:51
56 | TinyTuya1 | bf7ed421221e9996b9l2ir | 13 | carril DIN 1 (V)                       | General        | Voltage | 230.5 V

List of devices: 
[
  {
    "name": "carril DIN 1",
    "id": "bf7ed421221e9996b9l2ir",
    "key": "Deleted",
    "mac": "a0:92:08:87:9f:20",
    "category": "dlq",
    "product_name": "WiFi Din Rail Switch with metering",
    "product_id": "jdj6ccklup7btq3a",
    "biz_type": 0,
    "model": "AT-Q-SY1-JWT",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/bay1638066107344ANbl/49a020b43a5acc39d95eb2b1da0fb7c1.jpg",
    "uuid": "17f6a7de28e42c60"
  }
]
Functions of device: bf7ed421221e9996b9l2ir
{
  "result": {
    "category": "dlq",
    "functions": [
      {
        "code": "switch",
        "desc": "switch",
        "name": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "countdown 1",
        "name": "countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "desc": "relay status",
        "name": "relay status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "light_mode",
        "desc": "light mode",
        "name": "light mode",
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\",\"on\"]}"
      }
    ]
  },
  "success": true,
  "t": 1674493795382,
  "tid": "c20381f19b4011edae3d265fe02d1603"
}
Status of device: bf7ed421221e9996b9l2ir
{
  "result": [
    {
      "code": "switch",
      "value": true
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "add_ele",
      "value": 2
    },
    {
      "code": "cur_current",
      "value": 23
    },
    {
      "code": "cur_power",
      "value": 36
    },
    {
      "code": "cur_voltage",
      "value": 2329
    },
    {
      "code": "test_bit",
      "value": 1
    },
    {
      "code": "voltage_coe",
      "value": 0
    },
    {
      "code": "electric_coe",
      "value": 0
    },
    {
      "code": "power_coe",
      "value": 0
    },
    {
      "code": "electricity_coe",
      "value": 0
    },
    {
      "code": "fault",
      "value": 0
    },
    {
      "code": "relay_status",
      "value": "last"
    },
    {
      "code": "light_mode",
      "value": "relay"
    },
    {
      "code": "child_lock",
      "value": false
    }
  ],
  "success": true,
  "t": 1674493795692,
  "tid": "c22a58169b4011edae3d265fe02d1603"
}
}}

**Comment by Xenomes** [comment]
Hi, I fixed your device, please pull the branche of the update (no version change).

**Comment by jvm1000** [comment]
Here is the dump
i did to update

    Upgrade the tinytuya library sudo pip3 install tinytuya --upgrade
    Go in your Domoticz directory using a command line and open the plugins directory then the Domoticz-TUYA directory.
    Run: git pull
    Restart Domoticz.

but i dont have the Domoticz-TUYA directory., i have the Domoticz-TinyTUYA directory., i supose its the same

how do i force to reload tuya devices in domoticz?

Thanks a lot


List of devices: 
[
  {
    "name": "carril DIN 1",
    "id": "bf7ed421221e9996b9l2ir",
    "key": "Deleted",
    "mac": "a0:92:08:87:9f:20",
    "category": "dlq",
    "product_name": "WiFi Din Rail Switch with metering",
    "product_id": "jdj6ccklup7btq3a",
    "biz_type": 0,
    "model": "AT-Q-SY1-JWT",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/bay1638066107344ANbl/49a020b43a5acc39d95eb2b1da0fb7c1.jpg",
    "uuid": "17f6a7de28e42c60"
  },
]
Functions of device: bf7ed421221e9996b9l2ir
{
  "result": {
    "category": "dlq",
    "functions": [
      {
        "code": "switch",
        "desc": "switch",
        "name": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "countdown 1",
        "name": "countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "desc": "relay status",
        "name": "relay status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "light_mode",
        "desc": "light mode",
        "name": "light mode",
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\",\"on\"]}"
      }
    ]
  },
  "success": true,
  "t": 1674753889495,
  "tid": "562bed3b9d9e11ed89e112b09600735b"
}
Status of device: bf7ed421221e9996b9l2ir
{
  "result": [
    {
      "code": "switch",
      "value": true
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "add_ele",
      "value": 17
    },
    {
      "code": "cur_current",
      "value": 42
    },
    {
      "code": "cur_power",
      "value": 35
    },
    {
      "code": "cur_voltage",
      "value": 2308
    },
    {
      "code": "test_bit",
      "value": 1
    },
    {
      "code": "voltage_coe",
      "value": 0
    },
    {
      "code": "electric_coe",
      "value": 0
    },
    {
      "code": "power_coe",
      "value": 0
    },
    {
      "code": "electricity_coe",
      "value": 0
    },
    {
      "code": "fault",
      "value": 0
    },
    {
      "code": "relay_status",
      "value": "last"
    },
    {
      "code": "light_mode",
      "value": "relay"
    },
    {
      "code": "child_lock",
      "value": false
    }
  ],
  "success": true,
  "t": 1674753889728,
  "tid": "5652f5929d9e11ed89e112b09600735b"
}
}

**Comment by Xenomes** [comment]
> but i dont have the Domoticz-TUYA directory., i have the Domoticz-TinyTUYA directory., i supose its the same

Oops .. i will change that in the readme!

> how do i force to reload tuya devices in domoticz?

I your case i don't think you to recreate devices, because the wrong switch name was called. If you are on 1.3.9+ then it could work.
