### ISSUE TITLE
Irrigation garden controller

### ISSUE THREAD

**Issue by tanki658** [Xenomes/Domoticz-TinyTUYA-Plugin#101]
Hi Xenomes,

couple days ago I bought a new tuya device. 
https://pl.aliexpress.com/item/1005005942672923.html?spm=a2g0o.order_list.order_list_main.11.69041c24bhQwdc&gatewayAdapt=glo2pol
Domoticz recognized it and create only one device:
![image](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/35660536/403d03b8-e3d4-4d34-8c33-1c8de6d98b7b)
but my device has 6 irrigation zones.

Could you please add the missing zones?

**Comment by tanki658** [comment]
![image](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/35660536/a2b3add5-ce9e-4d0f-aad1-cd9c913bfa76)

**Comment by tanki658** [comment]
Xenomes r u there?

**Comment by Xenomes** [comment]
Hi tanki658, I was a bit busy the last couple of weeks. I will try to added it this this week.

**Comment by Xenomes** [comment]
The six areas are added to version 1.8.1

**Comment by tanki658** [comment]
Thank you. It works properly
