### ISSUE TITLE
Solar pane (Micro Inverter SP Series 800)

### ISSUE THREAD

**Issue by romaint2b** [Xenomes/Domoticz-TinyTUYA-Plugin#102]
Hi, I recently bought 2 solar panel connected with tuya.
I use your script and it detects the panel. 
Panel is recognized as switch (cz).
I debug and analyse your code (i'm java dev, not python dev).
Panel send data using out_power attribute. So I search for cur_power and add some similar lines :). And it works.
For information, I use python 3.7.3 and domoticz 2022.1.

Solar panel export these informations : 
ac_volt (V)
energy (kWh)
plant (pcs)
pv_current (A)
out_power (W) <-- This one returns the power at the output of the inverter. (this is the electricity injected in your electrical network).It's 80/90% of the pv_power .
day_energy (kWh)
ac_current (A)
temperature (°C)
pv_volt (V)
emission (kg) <-- Co2 emission reduction.
pv_power (W) <--This on returns the power at the direct panel output.
cur_voltage (V)
cur_power (W)
cur_current (A)

So, by default the cur_* was added but are always at 0....

I check the dashboard on tuya and the real produced energy is out_power.

Line 941 I add : 
```
if createDevice(dev['id'], 17) and (searchCode('out_power', ResultValue) or searchCode('phase_a', ResultValue)):
                        Domoticz.Unit(Name=dev['name'] + ' outpower (W)', DeviceID=dev['id'], Unit=17, Type=248, Subtype=1, Used=1).Create()
```

I'm not sure with the searchCode('phase_a', ResultValue) in my case.

line 1970 i add: 
```
if searchCode('out_power', ResultValue):
                            outpower = StatusDeviceTuya('out_power')
                            lastupdate = (int(time.time()) - int(time.mktime(time.strptime(Devices[dev['id']].Units[17].LastUpdate, '%Y-%m-%d %H:%M:%S'))))
                            lastvalue = Devices[dev['id']].Units[17].sValue if len(Devices[dev['id']].Units[17].sValue) > 0 else '0;0'
                            UpdateDevice(dev['id'], 17, str(outpower) + ';' + str(float(lastvalue.split(';')[1]) + ((outpower) * (lastupdate / 3600))) , 0, 0, 1)
```

I use unit 17 because last was 16 :). I hope I forget nothing on the code but it works.
 
Thank you very much for your work :)

[plugin.py.txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/14825409/plugin.py.txt)

**Comment by Xenomes** [comment]
Hi romaint2b,
Thanks for sharing! Very good, will add it to the plugin, so other can benefit!
Xenomes

**Comment by romaint2b** [comment]
[plugin_v2.py.txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/14889053/plugin_v2.py.txt)
Hi, I add a small update. 
Duplication of id 17 in new id : 18. I use the type 243 and subtype 29 in order to obtain the sum of all generated energy day by day in kwh.

**Comment by Xenomes** [comment]
Very good, i will take over the change.

**Comment by Xenomes** [comment]
Changes are added to 1.8.2
