### ISSUE TITLE
LSC / action slimme buitenlamp met camera  not recognized

### ISSUE THREAD

**Issue by haeewee** [Xenomes/Domoticz-TinyTUYA-Plugin#103]
Hi,

thanks for  this great  plugin
my issue:
all other devices are recognized  (except for another camera only device)
but this devices also has a motion detector and  a lamp included  which I would like to use in  automations
(I have no direct wish  to use the camera in domoticz)
 
 (because of expiring  IoT account I tried the Domoticz-TUYA-Plugin plugin too, but then some devices (including this device)  aren´t discovered at  all)   so now using  this tuya IoT connected  plugin again . 
in domotics it shows  subtype "text"
I hope it's possible to use the motion sensor and the light in this tinytuya plugin

thanks in advance

  {
    "name": "Slimme buitenlamp met camera",
    "id": "bf624db3276c8acebdahsp",
    "key": "Deleted",
    "mac": "c6:6e:12:21:4e:e4",
    "uuid": "jdws85fcc66e12214ee4",
    "category": "sp",
    "product_name": "Smart outdoor light with camera",
    "product_id": "0loqqbblnx1io8nm",
    "biz_type": 0,
    "model": "CIP-39900AT",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1541056239985fDGjj/ee43bacf01c55326647b3f840662b7c8.jpg"
  },

domoticz log:
tuya: Device name=Slimme buitenlamp met camera id=bf624db3276c8acebdahsp category=doorbell
tuya: No controls found for device: Slimme buitenlamp met camera
tuya: (tuya) Creating Unit 'Slimme buitenlamp met camera (Unknown Device)'.
tuya: Update device value: bf624db3276c8acebdahsp Unit: 1 sValue: This device is not recognized. Please edit and run the 
           debug_discovery with Python from the tools directory and recreate an issue report at 
           https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/issues so that the device can be added. nValue: 0 TimedOut=0

on iot.tuya  this device  seems to  have these  capabilities:

Code	Type	Values
basic_flip	Boolean	
"{true,false}"
basic_osd	Boolean	
"{true,false}"
basic_private	Boolean	
"{true,false}"
motion_sensitivity	Enum	
{
  "range": [
    "0",
    "1",
    "2"
  ]
}
sd_format	Boolean	
"{true,false}"
motion_record	Boolean	
"{true,false}"
nightvision_mode	Enum	
{
  "range": [
    "auto",
    "ir_mode",
    "color_mode"
  ]
}
motion_switch	Boolean	
"{true,false}"
floodlight_switch	Boolean	
"{true,false}"
record_switch	Boolean	
"{true,false}"
record_mode	Enum	
{
  "range": [
    "1",
    "2"
  ]
}
floodlight_lightness	Integer	
{
  "unit": "",
  "min": 1,
  "max": 100,
  "scale": 0,
  "step": 1
}
siren_switch	Boolean	
"{true,false}"
motion_area_switch	Boolean	
"{true,false}"
motion_area	String	
{
  "maxlen": 255
}
humanoid_filter	Boolean	
"{true,false}"
flight_warn_time	Integer	
{
  "min": 1,
  "max": 3600,
  "scale": 0,
  "step": 1
}
ipc_siren_duration	Integer	
{
  "unit": "s",
  "min": 10,
  "max": 600,
  "scale": 0,
  "step": 10
}
ipc_siren_volume	Integer	
{
  "unit": "%",
  "min": 0,
  "max": 100,
  "scale": 0,
  "step": 1
}

**Comment by Xenomes** [comment]
Hi haeewee,

We could try adding it, but please be warned in advance: the plugin retrieves the status from the server once every minute. Therefore, it's possible that if the status changes to true only briefly, the plugin might miss it.

**Comment by haeewee** [comment]
Hi Xenomes,
thanks  in advance for  your effort.
good to know it retrieves once every minute
then I  better add a separate motion sensor outside for automation
and  it's a better idea to only focus on controlling  the lamp  ?
best regards, ErikW

**Comment by Xenomes** [comment]
Yes controlling the lamp is a push command, that is instant. A Zigbee motion sensor is a much better solution.

**Comment by Xenomes** [comment]
Light control added in 1.8.3.

**Comment by haeewee** [comment]
Hi Xenomos,
awesome ! 
just updated the plugin,  devices is recognized and working !  
thank  you  so  much! 
best regards, ErikW

**Comment by Xenomes** [comment]
Perfect good to hear!
