### ISSUE TITLE
Unrecognized: Parkside Lawn Mower PMRDA 20-Li A1

### ISSUE THREAD

**Issue by joost12345** [Xenomes/Domoticz-TinyTUYA-Plugin#104]
Unrecognized Parkside Lawn Mower (itemnumber PMRDA 20-Li A1)

List of devices: 
[
  {
    "name": "Robotmaaier",
    "id": "xxxxxxxxxxxxxxx",
    "key": "Deleted",
    "mac": "xx:xx:xx:xx:xx:xx",
    "uuid": "xxxxxxxxxx",
    "sn": "xxxxxxxxxxxxx",
    "category": "gcj",
    "product_name": "Robot lawn mower PMRDA 20-Li A1",
    "product_id": "icw5sal7xfcevsve",
    "biz_type": 0,
    "model": "",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1559701439060fw6BY/cd5d1eb275462c33b3ea5f52672fe535.png"
  }
]
Properties of device: bf37464164168f12dfncpx
{
  "result": {
    "category": "gcj",
    "functions": [
      {
        "code": "battery_percentage",
        "desc": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}",
        "name": "\u5269\u4f59\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "MachineRainMode",
        "desc": "{}",
        "name": "\u96e8\u6c34\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "MachineWorktime",
        "desc": "{\"unit\":\"\u5c0f\u65f6\",\"min\":1,\"max\":99,\"scale\":0,\"step\":1}",
        "name": "\u5de5\u4f5c\u65f6\u957f",
        "type": "Integer",
        "values": "{\"unit\":\"\u5c0f\u65f6\",\"min\":1,\"max\":99,\"scale\":0,\"step\":1}"
      },
      {
        "code": "ClearAppointment",
        "desc": "{}",
        "name": "\u6e05\u7a7a\u673a\u5668\u9884\u7ea6\u65f6\u95f4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "QueryAppointment",
        "desc": "{}",
        "name": "\u67e5\u8be2\u673a\u5668\u9884\u7ea6",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "QueryPartition",
        "desc": "{}",
        "name": "\u67e5\u8be2\u5206\u533a\u53c2\u6570",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "MachineAppointment",
        "desc": "{}",
        "name": "\u4e0a\u62a5\u673a\u5668\u9884\u7ea6",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "MachinePartition",
        "desc": "{}",
        "name": "MachinePartition",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "boolreserved01",
        "desc": "{}",
        "name": "boolreserved01",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "MachineControlCmd",
        "desc": "{\"range\":[\"PauseWork\",\"CancelWork\",\"ContinueWork\",\"StartMowing\",\"StartFixedMowing\",\"StartReturnStation\"]}",
        "name": "\u673a\u5668\u63a7\u5236\u6307\u4ee4",
        "type": "Enum",
        "values": "{\"range\":[\"PauseWork\",\"CancelWork\",\"ContinueWork\",\"StartMowing\",\"StartFixedMowing\",\"StartReturnStation\"]}"
      },
      {
        "code": "boolreserved02",
        "desc": "{}",
        "name": "boolreserved02",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "boolreserved03",
        "desc": "{}",
        "name": "boolreserved03",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "valuereserved01",
        "desc": "{\"unit\":\"\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}",
        "name": "valuereserved01",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "valuereserved02",
        "desc": "{\"unit\":\"\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}",
        "name": "valuereserved02",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "valuereserved03",
        "desc": "{\"unit\":\"\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}",
        "name": "valuereserved03",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "enumreserved01",
        "desc": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\"]}",
        "name": "enumreserved01",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\"]}"
      },
      {
        "code": "enumreserved02",
        "desc": "{\"range\":[\"1\"]}",
        "name": "enumreserved02",
        "type": "Enum",
        "values": "{\"range\":[\"1\"]}"
      },
      {
        "code": "enumreserved03",
        "desc": "{\"range\":[\"1\"]}",
        "name": "enumreserved03",
        "type": "Enum",
        "values": "{\"range\":[\"1\"]}"
      },
      {
        "code": "strreserved01",
        "desc": "{\"maxlen\":255}",
        "name": "strreserved01",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "strreserved02",
        "desc": "{\"maxlen\":255}",
        "name": "strreserved02",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "strreserved03",
        "desc": "{\"maxlen\":255}",
        "name": "strreserved03",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "rawreserved01",
        "desc": "{}",
        "name": "rawreserved01",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "rawreserved02",
        "desc": "{}",
        "name": "rawreserved02",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "rawreserved03",
        "desc": "{}",
        "name": "rawreserved03",
        "type": "Raw",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "battery_percentage",
        "name": "\u5269\u4f59\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "MachineStatus",
        "name": "\u673a\u5668\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"STANDBY\",\"CHARGING\",\"MOWING\",\"PAUSED\",\"PARK\",\"UPDATA\",\"FIXED_MOWING\",\"ERROR\",\"SELF_TEST\",\"CHARGING_WITH_TASK_SUSPEND\",\"EMERGENCY\",\"LOCKED\"]}"
      },
      {
        "code": "MachineError",
        "name": "\u673a\u5668\u9519\u8bef",
        "type": "Bitmap",
        "values": "{\"label\":[\"FAULT_LEAN\",\"FAULT_TOO_STEEP\",\"NO_SIGNAL\",\"L_MOTOR_ERROR\",\"R_MOTOR_ERROR\",\"BATTERY_VOL_HIG\",\"B_TEMP_ERROR\",\"DISCHAR_ERROR\",\"CHARGE_OVERTEMP\",\"BATTERY_DAMAGE\",\"BATTERY_LOWDIS\",\"CHARGE_CURDIS\",\"CHARGE_TEMP\",\"UNEXCEPECT_LOW\",\"B_ERROR_RESET\",\"IMU_INVALID\",\"EMS_INVALID\",\"RAIN_INVALID\",\"HALL_INVALID\",\"STEEP_OVER_3S\",\"OUTSIDE_AREA\",\"LIFTED\",\"TRAPPED\",\"B_MOTOR_ERROR\",\"OVERTURN\",\"MOTOR_OVERCUR\",\"MOTOR_HALL\",\"MOTOR_DISCON\",\"EMS_DISCONNECT\",\"MOTOR_ERROR\"],\"maxlen\":30}"
      },
      {
        "code": "MachineWarning",
        "name": "\u673a\u5668\u8b66\u544a",
        "type": "Enum",
        "values": "{\"range\":[\"MOWER_LEAN\",\"MOWER_STEEP\",\"RAIN_PARK\",\"BATTERY_NOT_ENOUGH\",\"NO_LOOP_SIGNAL\",\"CLOSE_TOPCOVER\",\"MOWER_IN_STATION\",\"MOWER_OUT_STATION\",\"PLACE_INSIDE_STATION\",\"FIXED_END\",\"CHARGING_DISCONNECT\",\"CHARGING_PAUSE\",\"WORK_INTERRUPT\",\"FIXED_MOWING_INTERUPT\",\"TURN_ON_BUTTON\",\"PRESS_START_KEY\",\"TIMESET_30MIN\",\"TIMESET_UNLEGAL\",\"CHARGR_CURRENT_LOW\",\"RAIN_OUT_STATION\",\"UPDATA_FAIL\",\"CONTINUE_TOOLTIP\",\"MOWER_EMERGENCY\",\"MOWER_UI_LOCKED\",\"DISCHARGE_ERROR\",\"CHARGE_TEMP_ERROR\"]}"
      },
      {
        "code": "MachineRainMode",
        "name": "\u96e8\u6c34\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "MachineWorktime",
        "name": "\u5de5\u4f5c\u65f6\u957f",
        "type": "Integer",
        "values": "{\"unit\":\"\u5c0f\u65f6\",\"min\":1,\"max\":99,\"scale\":0,\"step\":1}"
      },
      {
        "code": "MachinePassword",
        "name": "\u673a\u5668\u5bc6\u7801",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1111,\"max\":4444,\"scale\":0,\"step\":1}"
      },
      {
        "code": "MachineAppointment",
        "name": "\u4e0a\u62a5\u673a\u5668\u9884\u7ea6",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "MachineErrorLog",
        "name": "\u9519\u8bef\u65e5\u5fd7",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "MachineWorkLog",
        "name": "\u5de5\u4f5c\u65e5\u5fd7",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "MachinePartition",
        "name": "MachinePartition",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "boolreserved01",
        "name": "boolreserved01",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "MachineCover",
        "name": "\u673a\u5668\u76d6\u5b50",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "boolreserved02",
        "name": "boolreserved02",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "boolreserved03",
        "name": "boolreserved03",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "valuereserved01",
        "name": "valuereserved01",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "valuereserved02",
        "name": "valuereserved02",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "valuereserved03",
        "name": "valuereserved03",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "enumreserved01",
        "name": "enumreserved01",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\"]}"
      },
      {
        "code": "enumreserved02",
        "name": "enumreserved02",
        "type": "Enum",
        "values": "{\"range\":[\"1\"]}"
      },
      {
        "code": "enumreserved03",
        "name": "enumreserved03",
        "type": "Enum",
        "values": "{\"range\":[\"1\"]}"
      },
      {
        "code": "faultreserved01",
        "name": "faultreserved01",
        "type": "Bitmap",
        "values": "{\"label\":[\"1\"],\"maxlen\":1}"
      },
      {
        "code": "strreserved01",
        "name": "strreserved01",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "strreserved02",
        "name": "strreserved02",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "strreserved03",
        "name": "strreserved03",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "rawreserved01",
        "name": "rawreserved01",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "rawreserved02",
        "name": "rawreserved02",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "rawreserved03",
        "name": "rawreserved03",
        "type": "Raw",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1713554484902,
  "tid": "033b8bd7fe8211ee807a9a248848decc"
}
Status of device: bf37464164168f12dfncpx
{
  "result": [
    {
      "code": "battery_percentage",
      "value": 100
    },
    {
      "code": "MachineStatus",
      "value": "STANDBY"
    },
    {
      "code": "MachineError",
      "value": 1048576
    },
    {
      "code": "MachineWarning",
      "value": "MOWER_LEAN"
    },
    {
      "code": "MachineRainMode",
      "value": true
    },
    {
      "code": "MachineWorktime",
      "value": 1
    },
    {
      "code": "MachinePassword",
      "value": 1111
    },
    {
      "code": "MachineAppointment",
      "value": "AIiIiIgBiIiIiAKIiIiIA4iIiIgEiIiIiAURABIABoiIiIgAiIiIiAGIiIiIAoiIiIgDiIiIiASIiIiIBQAAAAAGiIiIiA=="
    },
    {
      "code": "MachineErrorLog",
      "value": "ZiLXVAJmItajAmYi1qIUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
    },
    {
      "code": "MachineWorkLog",
      "value": ""
    },
    {
      "code": "MachinePartition",
      "value": ""
    },
    {
      "code": "boolreserved01",
      "value": false
    },
    {
      "code": "MachineCover",
      "value": false
    },
    {
      "code": "boolreserved02",
      "value": false
    },
    {
      "code": "boolreserved03",
      "value": false
    },
    {
      "code": "valuereserved01",
      "value": 0
    },
    {
      "code": "valuereserved02",
      "value": 0
    },
    {
      "code": "valuereserved03",
      "value": 0
    },
    {
      "code": "enumreserved01",
      "value": "1"
    },
    {
      "code": "enumreserved02",
      "value": "1"
    },
    {
      "code": "enumreserved03",
      "value": "1"
    },
    {
      "code": "faultreserved01",
      "value": 0
    },
    {
      "code": "strreserved01",
      "value": ""
    },
    {
      "code": "strreserved02",
      "value": ""
    },
    {
      "code": "strreserved03",
      "value": ""
    },
    {
      "code": "rawreserved01",
      "value": ""
    },
    {
      "code": "rawreserved02",
      "value": ""
    },
    {
      "code": "rawreserved03",
      "value": ""
    }
  ],
  "success": true,
  "t": 1713554485031,
  "tid": "03518a57fe8211ee83bd6a1108d921ac"
}

**Comment by Xenomes** [comment]
Thanks for the Json, Will try to add it this weekend to the plugin.

**Comment by Xenomes** [comment]
Add the device to version 1.8.5

**Comment by joost12345** [comment]
Thanks! I will check when I'm back from holiday (end of May).
