### ISSUE TITLE
Air Quality - (Nobito)

### ISSUE THREAD

**Issue by Fnasy** [Xenomes/Domoticz-TinyTUYA-Plugin#105]
Hi,

I got a air quality device from China. (Brand : Nobito ???)
Smart life recognize it without any 
[DumpNobito.pdf](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/15064421/DumpNobito.pdf)

problem.
It has only one way data giving the differents mesurements (CO, Co2,...) 
Could it be integrated into Domoticz Tinytuya plugin ?

 Regards

Thierry

[DumpNobito.pdf](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/15064421/DumpNobito.pdf)

**Comment by Xenomes** [comment]
I will try to test the json with the plugin this weekend!

**Comment by Xenomes** [comment]
The device is already supported, but it encountered a strange error while testing the JSON. What error do you get at the start of the plugin?
