### ISSUE TITLE
3-way switch - TinyTuya: Device read failed: bfca7b0908fc2e217eztow

### ISSUE THREAD

**Issue by wvries** [Xenomes/Domoticz-TinyTUYA-Plugin#106]
Hi,

Installed a new 3-way switch, conneted to Tuya app and working in the Tuya app.
Switched to DP instruction mode, Tuya subscription up to date.
When restarting Tuya plugin, 3 switch devices are created in Domoticz.
From Domoticz, switches can be switched on and off, displaying the correct status in the Tuya app.
When switching in the Tuya app, no status changes in Domoticz.
When switching the device itself, no status changes in Domoticz (Tuya app updates to correct state)

Error in log (every minute, the polling time):
2024-04-25 15:21:52.668 TinyTuya: Update devices in Domoticz
2024-04-25 15:21:52.669 Error: TinyTuya: Device read failed: bfca7b0908fc2e217eztow

All other switched work without any issues.
Below the JSON for the device.

With kind regards,
Wilbert de Vries

List of devices:
[
  {
    "name": "Smart Switch",
    "id": "bfca7b0908fc2e217eztow",
    "key": "Deleted",
    "mac": "c4:82:e1:b3:58:98",
    "uuid": "f7385ef4f05ced79",
    "category": "kg",
    "product_name": "Smart Switch",
    "product_id": "lhayxix9j09fgeax",
    "biz_type": 0,
    "model": "wifi\u89e6\u6478\u5f00\u5173\uff08\u4e09\u5f00\uff09",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay15306906879543yc3O/08f06c15f266143a3f42ec451ff00a2e.png"
  }
]
Properties of device: bfca7b0908fc2e217eztow
{
  "result": {
    "category": "kg",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "desc": "{}",
        "name": "\u5f00\u51732",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "desc": "{}",
        "name": "\u5f00\u51733",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51732\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51733\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "desc": "{\"range\":[\"off\",\"on\",\"memory\"]}",
        "name": "\u4e0a\u7535\u72b6\u6001\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"off\",\"on\",\"memory\"]}"
      },
      {
        "code": "cycle_time",
        "desc": "{\"maxlen\":255}",
        "name": "\u5faa\u73af\u5b9a\u65f6",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "random_time",
        "desc": "{\"maxlen\":255}",
        "name": "\u968f\u673a\u5b9a\u65f6",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
     {
        "code": "switch_inching",
        "desc": "{\"maxlen\":255}",
        "name": "\u70b9\u52a8\u5f00\u5173",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "name": "\u5f00\u51732",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "name": "\u5f00\u51733",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "name": "\u5f00\u51732\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "name": "\u5f00\u51733\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "name": "\u4e0a\u7535\u72b6\u6001\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"off\",\"on\",\"memory\"]}"
      },
      {
        "code": "cycle_time",
        "name": "\u5faa\u73af\u5b9a\u65f6",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "random_time",
        "name": "\u968f\u673a\u5b9a\u65f6",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "switch_inching",
        "name": "\u70b9\u52a8\u5f00\u5173",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ]
  },
  "success": true,
  "t": 1714050314681,
  "tid": "74d1d666030411efb9742aed87e938e1"
}

Status of device: bfca7b0908fc2e217eztow
{
  "result": [
    {
      "code": "switch_1",
      "value": false
    },
    {
      "code": "switch_2",
      "value": false
    },
    {
      "code": "switch_3",
      "value": false
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "countdown_2",
      "value": 0
    },
    {
      "code": "countdown_3",
      "value": 0
    },
    {
      "code": "relay_status",
      "value": "off"
    },
    {
      "code": "cycle_time",
      "value": ""
    },
    {
      "code": "random_time",
      "value": ""
    },
    {
      "code": "switch_inching",
      "value": ""
    }
  ],
  "success": true,
  "t": 1714050314875,
  "tid": "74f0da79030411efb0684a5aa45b6ee1"
}

**Comment by Xenomes** [comment]
Hi wvries,
Thanks for reporting, the issue is fix in 1.8.4.
