### ISSUE TITLE
Pool temperature (RADDY PT-3)

### ISSUE THREAD

**Issue by cth35** [Xenomes/Domoticz-TinyTUYA-Plugin#107]
Device is not recognized. Here is the dump 

List of devices:
[
  {
    "name": "pool-temperature-1",
    "id": "bf60d5632c66fa046b1ma9",
    "key": "Deleted",
    "mac": "d8:XX:XX:XX:XX:XX",
    "uuid": "41406753f188dce7",
    "sn": "1001324790077A",
    "category": "qxj",
    "product_name": " pool-temperature-1",
    "product_id": "bev7tpincjaysgzs",
    "biz_type": 0,
    "model": "EM3406TY",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/bay16148256503824wwj/b10fb138e46a36bc606daf2428600044.jpg"
  }
]
Properties of device: bf60d5632c66fa046b1ma9
{
  "result": {
    "category": "qxj"
  },
  "success": true,
  "t": 1717617104376,
  "tid": "09236c81237511efb2c7424759d4fc99"
}
Status of device: bf60d5632c66fa046b1ma9
{
  "result": [],
  "success": true,
  "t": 1717617104653,
  "tid": "094e78aa237511efbdd1c23db552a5a2"
}

**Comment by cth35** [comment]
If you need mac address I can provide in MP.

**Comment by Xenomes** [comment]
Hi cth35,
Thanks for sharing, the json of Properties and Status is empty, did you put the device in the iot.tuya,com on 'DP instruction'?

**Comment by cth35** [comment]
Yes I think so :
![image](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/51801882/32bbdd98-dee0-43a3-b0a0-4e105f19fec4)

**Comment by Xenomes** [comment]
That is correct, can you run the debug_discovery again?

**Comment by cth35** [comment]
ok it seems better 

List of devices:
 [
  {
    "name": "pool-temperature-1",
    "id": "bf60d5632c66fa046b1ma9",
    "key": "Deleted",
    "mac": "XXXXXXXX",
    "uuid": "41406753f188dce7",
    "sn": "1001324790077A",
    "category": "qxj",
    "product_name": " pool-temperature-1",
    "product_id": "bev7tpincjaysgzs",
    "biz_type": 0,
    "model": "EM3406TY",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/bay16148256503824wwj/b10fb138e46a36bc606daf2428600044.jpg"
  }
]

Properties of device: bf60d5632c66fa046b1ma9
 {
  "result": {
    "category": "qxj",
    "functions": [
      {
        "code": "Time",
        "desc": "{\"maxlen\":255}",
        "name": "\u540c\u6b65\u65f6\u95f4",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "pressure_units",
        "desc": "{\"range\":[\"inHg\",\"mmHg\",\"hPa\"]}",
        "name": "\u5927\u6c14\u538b\u5355\u4f4d\u5207\u6362",
        "type": "Enum",
        "values": "{\"range\":[\"inHg\",\"mmHg\",\"hPa\"]}"
      },
      {
        "code": "C_F",
        "desc": "{}",
        "name": "\u6e29\u5ea6\u5355\u4f4d\u5207\u6362",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "Tin_set",
        "desc": "{\"maxlen\":255}",
        "name": "\u5ba4\u5185\u6e29\u5ea6\u544a\u8b66\u8bbe\u7f6e",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "Hin_set",
        "desc": "{\"maxlen\":255}",
        "name": "\u5ba4\u5185\u6e7f\u5ea6\u544a\u8b66\u8bbe\u7f6e",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "Tout_set",
        "desc": "{\"maxlen\":255}",
        "name": "\u5ba4\u5916\u6e29\u5ea6\u544a\u8b66\u8bbe\u7f6e",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "Hout_set",
        "desc": "{\"maxlen\":255}",
        "name": "\u5ba4\u5916\u6e7f\u5ea6\u544a\u8b66\u8bbe\u7f6e",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "backlight_set",
        "desc": "{\"range\":[\"high\",\"middle\",\"low\",\"close\"]}",
        "name": "\u80cc\u5149\u4eae\u5ea6\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"high\",\"middle\",\"low\",\"close\"]}"
      },
      {
        "code": "Time_Format",
        "desc": "{}",
        "name": "\u65f6\u95f4\u5236\u5f0f",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "DM",
        "desc": "{}",
        "name": "\u65e5\u671f\u663e\u793a\u5207\u6362",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "Light_T",
        "desc": "{\"unit\":\"\u5206\u949f\",\"min\":0,\"max\":1000,\"scale\":1,\"step\":1}",
        "name": "\u80cc\u5149\u65f6\u95f4\u8bbe\u7f6e",
        "type": "Integer",
        "values": "{\"unit\":\"\u5206\u949f\",\"min\":0,\"max\":1000,\"scale\":1,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "Tin",
        "name": "\u5ba4\u5185\u6e29\u5ea6",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-600,\"max\":2550,\"scale\":1,\"step\":1}"
      },
      {
        "code": "Hin",
        "name": "\u5ba4\u5185\u6e7f\u5ea6",
        "type": "Integer",
        "values": "{\"unit\":\"%RH\",\"min\":0,\"max\":255,\"scale\":0,\"step\":1}"
      },
      {
        "code": "ToutCh1",
        "name": "\u5ba4\u5916\u6e29\u5ea6CH1",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-600,\"max\":2550,\"scale\":1,\"step\":1}"
      },
      {
        "code": "HoutCh1",
        "name": "\u5ba4\u5916\u6e7f\u5ea6CH1",
        "type": "Integer",
        "values": "{\"unit\":\"%RH\",\"min\":0,\"max\":255,\"scale\":0,\"step\":1}"
      },
      {
        "code": "Time",
        "name": "\u540c\u6b65\u65f6\u95f4",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "ToutCh2",
        "name": "\u5ba4\u5916\u6e29\u5ea6CH2",
        "type": "Integer",
        "values": "{\"unit\":\" \u2103\",\"min\":-600,\"max\":2550,\"scale\":1,\"step\":1}"
      },
      {
        "code": "HoutCh2",
        "name": "\u5ba4\u5916\u6e7f\u5ea6CH2",
        "type": "Integer",
        "values": "{\"unit\":\"%RH\",\"min\":0,\"max\":255,\"scale\":0,\"step\":1}"
      },
      {
        "code": "ToutCh3",
        "name": "\u5ba4\u5916\u6e29\u5ea6CH3",
        "type": "Integer",
        "values": "{\"unit\":\" \u2103\",\"min\":-600,\"max\":2550,\"scale\":1,\"step\":1}"
      },
      {
        "code": "HoutCh3",
        "name": "\u5ba4\u5916\u6e7f\u5ea6CH3",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":255,\"scale\":0,\"step\":1}"
      },
      {
        "code": "atmosphere",
        "name": "\u5927\u6c14\u538b",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":300,\"max\":1100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "pressure_units",
        "name": "\u5927\u6c14\u538b\u5355\u4f4d\u5207\u6362",
        "type": "Enum",
        "values": "{\"range\":[\"inHg\",\"mmHg\",\"hPa\"]}"
      },
      {
        "code": "C_F",
        "name": "\u6e29\u5ea6\u5355\u4f4d\u5207\u6362",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "Tin_set",
        "name": "\u5ba4\u5185\u6e29\u5ea6\u544a\u8b66\u8bbe\u7f6e",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "Hin_set",
        "name": "\u5ba4\u5185\u6e7f\u5ea6\u544a\u8b66\u8bbe\u7f6e",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "Tout_set",
        "name": "\u5ba4\u5916\u6e29\u5ea6\u544a\u8b66\u8bbe\u7f6e",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "Hout_set",
        "name": "\u5ba4\u5916\u6e7f\u5ea6\u544a\u8b66\u8bbe\u7f6e",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "fault",
        "name": "\u6545\u969c\u544a\u8b66",
        "type": "Bitmap",
        "values": "{\"label\":[\"HTI\",\"LTI\",\"HHI\",\"LHI\",\"HTO\",\"LTO\",\"HHO\",\"LHO\",\"LP1\",\"LP2\",\"LP3\"],\"maxlen\":11}"
      },
      {
        "code": "backlight_set",
        "name": "\u80cc\u5149\u4eae\u5ea6\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"high\",\"middle\",\"low\",\"close\"]}"
      },
      {
        "code": "Time_Format",
        "name": "\u65f6\u95f4\u5236\u5f0f",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "DM",
        "name": "\u65e5\u671f\u663e\u793a\u5207\u6362",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "Light_T",
        "name": "\u80cc\u5149\u65f6\u95f4\u8bbe\u7f6e",
        "type": "Integer",
        "values": "{\"unit\":\"\u5206\u949f\",\"min\":0,\"max\":1000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "Slave_Unit",
        "name": "\u4ece\u8bbe\u5907\u7535\u91cf",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "DATA",
        "name": "\u8bbe\u5907\u6570\u636e\u7c7b\u578b",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "Setting",
        "name": "Setting",
        "type": "Raw",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1717702490752,
  "tid": "d7646d2a243b11efba4b0a9d16b0493d"
}

Status of device: bf60d5632c66fa046b1ma9
 {
  "result": [
    {
      "code": "Tin",
      "value": 233
    },
    {
      "code": "Hin",
      "value": 36
    },
    {
      "code": "ToutCh1",
      "value": -600
    },
    {
      "code": "HoutCh1",
      "value": 0
    },
    {
      "code": "Time",
      "value": ""
    },
    {
      "code": "ToutCh2",
      "value": 246
    },
    {
      "code": "HoutCh2",
      "value": 56
    },
    {
      "code": "ToutCh3",
      "value": 233
    },
    {
      "code": "HoutCh3",
      "value": 0
    },
    {
      "code": "atmosphere",
      "value": 300
    },
    {
      "code": "pressure_units",
      "value": "inHg"
    },
    {
      "code": "C_F",
      "value": true
    },
    {
      "code": "Tin_set",
      "value": ""
    },
    {
      "code": "Hin_set",
      "value": ""
    },
    {
      "code": "Tout_set",
      "value": ""
    },
    {
      "code": "Hout_set",
      "value": ""
    },
    {
      "code": "fault",
      "value": 0
    },
    {
      "code": "backlight_set",
      "value": "high"
    },
    {
      "code": "Time_Format",
      "value": false
    },
    {
      "code": "DM",
      "value": false
    },
    {
      "code": "Light_T",
      "value": 0
    },
    {
      "code": "Slave_Unit",
      "value": "A200B100C100"
    },
    {
      "code": "DATA",
      "value": "AQEAAQEBAQEA"
    },
    {
      "code": "Setting",
      "value": "AQABAAEA"
    }
  ],
  "success": true,
  "t": 1717702491049,
  "tid": "d7917d50243b11ef80b62a5a52237ee2"
}

**Comment by cth35** [comment]
But still have this message 👍 
This device is not recognized. Please edit and run the debug_discovery with Python from the tools directory and recreate an issue report at https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/issues so that the device can be added.

**Comment by Xenomes** [comment]
That is better! What values would you like to see in Domoticz compared with the app?

**Comment by cth35** [comment]
In the App there are 4 temperatures. Tin and HIn = Interior temp and humidity + 3 remote channels On Ch1 (nothing yet I haven't power the sensorbut there will be temerature un celcius and humidity in %), on Ch2 it should be temperature and humidity (246 = 24.6 °C, 56 = 56% of humidity). Ch3 has only temperature (233 = 23.3°C). Regards

**Comment by Xenomes** [comment]
Okay thanks, I will try to add it this weekend. Atmosphere 300 is not in the app?

**Comment by cth35** [comment]
I don't see it. Also I don't see any battery level in the data (but exist in the app)
![Screenshot_20240606-221216_Tuya Smart](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/51801882/7ef1397c-398e-437a-925a-9a4f4315321e)

**Comment by Xenomes** [comment]
Hi, I want to update the plugin for your device, but the JSON in the post is missing a lot of escape characters. Can you upload or email the dump.json file?

**Comment by Xenomes** [comment]
Updated the plugin for your device, could not test with out the json, let me know if there need to be a fix.

**Comment by cth35** [comment]
Thanks a lot, it works !
