### ISSUE TITLE
Device not recognised in TinyTuya. Following the instruction given.

### ISSUE THREAD

**Issue by geschriever** [Xenomes/Domoticz-TinyTUYA-Plugin#108]
[dump.json](https://github.com/user-attachments/files/16102919/dump.json)
The Smart Soil Sensor is not recognised in TinyTuya.
The device is a Zigbee device.
Thanks for help! 

Device: bff5e3b73fb2a07c57sssa

If more information is needed, I'm happy to supply this.

Best regards,
Gé Schriever

**Comment by geschriever** [comment]
"name": "Bamboe-oprit",
    "id": "bff5e3b73fb2a07c57sssa",
    "key": "Deleted",
    "mac": "not published",
    "uuid": "not published",
    "category": "zwjcy",
    "product_name": "Soil moisture",
    "product_id": "g2e6cpnw",
    "biz_type": 0,
    "model": "",
    "sub": true,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1503986080106Gppjy/5b2990c900bab8e613384dd7cb21627f.png",
    "node_id": "a4c1382ec0102764"
  },

**Comment by Xenomes** [comment]
Thanks, i see in the json that humidity is 0 was that also visible in the app?

**Comment by geschriever** [comment]
In the beginning yes because the soil was dry at that place. Now I have replaced the sensor and he is giving a value of 22% and a temperature of 16.7.
New dump.json with these values added.

[dump.json](https://github.com/user-attachments/files/16113595/dump.json)

**Comment by Xenomes** [comment]
Yes perfect the values match! I will try tomorrow to add it to the code.

**Comment by geschriever** [comment]
Thanks in advance!

**Comment by Xenomes** [comment]
Your device is added to 1.9.0

**Comment by geschriever** [comment]
Thanks for your good work! It is working now.
