### ISSUE TITLE
1.39 domoticz 2022.2 : some device doesn't respond

### ISSUE THREAD

**Issue by stefg73** [Xenomes/Domoticz-TinyTUYA-Plugin#11]

**Comment by Xenomes** [comment]
Sorry, i need more info then 'some device doesn't respond'. Can you edit and run the debug_discovery.py and post the json?

**Comment by stefg73** [comment]
i can't run  debug_discovery.py, get this : [Errno 13] Permission denied: 'dump.json' line 39

**Comment by stefg73** [comment]
sorry, here is it : 
Properties of device: bf58684fee8ed8806ac5zp
 {
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "desc": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}",
        "name": "\u4e0a\u7535\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "name": "\u4e0a\u7535\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      }
    ]
  },
  "success": true,
  "t": 1674879851501,
  "tid": "9d63cf519ec311ed89e112b09600735b"
}

Status of device: bf58684fee8ed8806ac5zp
 {
  "result": [
    {
      "code": "switch_1",
      "value": true
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "relay_status",
      "value": "last"
    }
  ],
  "success": true,
  "t": 1674879851986,
  "tid": "9dad9b879ec311edbd98a6d801a7eabc"

**Comment by stefg73** [comment]
this device works fine with smartlife app, but doesn't with domoticz

**Comment by Xenomes** [comment]
I found the issue, can you do a pull of the plugin to test if it resolves your issue.

**Comment by stefg73** [comment]
Hello : only the off function work : impossible to switch On from Domoticz

**Comment by stefg73** [comment]
Functions of device: bf58684fee8ed8806ac5zp
 {
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "desc": "switch 1",
        "name": "switch 1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "countdown 1",
        "name": "countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "desc": "relay status",
        "name": "relay status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      }
    ]
  },
  "success": true,
  "t": 1674903243011,
  "tid": "13cfcc149efa11ed89e112b09600735b"
}

Properties of device: bf58684fee8ed8806ac5zp
 {
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "desc": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}",
        "name": "\u4e0a\u7535\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "name": "\u4e0a\u7535\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      }
    ]
  },
  "success": true,
  "t": 1674903243371,
  "tid": "1406c5909efa11ed97b7f276006a160b"
}

Status of device: bf58684fee8ed8806ac5zp
 {
  "result": [
    {
      "code": "switch_1",
      "value": true
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "relay_status",
      "value": "last"
    }
  ],
  "success": true,
  "t": 1674903243775,
  "tid": "1443c3bb9efa11edbd98a6d801a7eabc"
}

**Comment by Xenomes** [comment]
I found the problem. please do a new pull.

**Comment by stefg73** [comment]
YES !!! You got it : it works ! 

Thanks

**Comment by Xenomes** [comment]
Perfect!
