### ISSUE TITLE
Support for QLIMA D 812 Smart Dehumidifier

### ISSUE THREAD

**Issue by GertVersteeg1956** [Xenomes/Domoticz-TinyTUYA-Plugin#111]
A couple of weeks ago I bought a QLIMA D 812 Smart dehumidifier and installed it in the basement. Connected it to the Tuya Smart app. It works fine. This week I connected it to Domoticz with this Cloud plugin and studied topic 39441 in the Domoticz forum.
It also works fine. I did write a small python script that turns on the device when the humidity is to high and turn it off when it is ok again. I defined 2 user variables for the limits. Humidity is read by Alecto RFlink devices.
When I inspect the json file created by the debug_discovery.py script I can see that the "water reservoir full" indicator is also available. Is it possible to make it available in Domoticz as well?
[dump.json](https://github.com/user-attachments/files/16446040/dump.json)

**Comment by Xenomes** [comment]
Hi, in the json i don't see "water reservoir full" did you send the wrong json or do you disabled the 'DP instruction'?

**Comment by GertVersteeg1956** [comment]
Sorry,
I  was a little bit sloppy.
'DP instruction' is on, json is correct.
It is a status.fault condition. It is called "water_full" and mentioned in line 75 of dump.json.
It will take me some time decoding the json and to study your plugin. Final goal is to minimize delivery of my solar panel energy when they stop the "saldering" benefit in the Netherlands. 
Loading my PHEV
dehumidify my house
Loading a battery
A lot of study will be required.
I only programmed Fortran IV and 77, C, Pascall, PL1, several Assembly languages . I'll manage, but it will take time

**Comment by Xenomes** [comment]
Ha, Yes I see now. that is not a big thing to add to the code. I will try to added it Friday,

**Comment by GertVersteeg1956** [comment]
Thank you. I'll fork the project and check the differences.

**Comment by GertVersteeg1956** [comment]
Today I started to study the code. Found the locations where the modifications have to be made, but I'm not familiar enough with python yet to do reliable changes.
Thanks for offering top make the changes. I'll study them and learn more about python plugins.

**Comment by Xenomes** [comment]
Hi Gert, its added to version 1.9.4

**Comment by GertVersteeg1956** [comment]
Thanks for the modification.
Tried to update
It failed (see log)

[update tinytutya.log](https://github.com/user-attachments/files/16467292/update.tinytutya.log)

will try 2 more options
1) stop domoticz
    git pull
    when success
          start domoticz
2) stop domoticz
    rename plugin.py 
    git pull
    when success
        start domoticz

**Comment by GertVersteeg1956** [comment]
Its working!
[log2.log](https://github.com/user-attachments/files/16467434/log2.log)
Device is visible now

![Screenshot from 2024-08-02 09-58-52](https://github.com/user-attachments/assets/db12be2c-929b-4f7a-9807-aa99efc6c5b8)
It is full now. I will empty it and share a new screendump

**Comment by GertVersteeg1956** [comment]
I'm happy 
![Screenshot from 2024-08-02 10-07-06](https://github.com/user-attachments/assets/c460472b-274a-43bd-a958-3451633aa292)
I can check it now in my script and sent a notification to my phone when it is full.
But first I will learn Python
Do you think https://www.pythontutorial.net/ is a good start?

**Comment by Xenomes** [comment]
Good to see that it's working, but I see the label isn't used correctly and shows as an int. I will try to improve that.

**Comment by Xenomes** [comment]
Updated the code, now is the label used. update small mistake for the selector_switch.

**Comment by Xenomes** [comment]
>But first I will learn Python Do you think https://www.pythontutorial.net/ is a good start?
 
Yes i think so, i learn by just doing it, but my coding is bit dirty 🤣

**Comment by GertVersteeg1956** [comment]
Hi Xenomes
You did a great job thanks.
For completeness I'll include the log and a screenshot.
[update tinytutya3.log](https://github.com/user-attachments/files/16478480/update.tinytutya3.log)
![Screenshot from 2024-08-03 09-20-11](https://github.com/user-attachments/assets/f76d1e94-bcdf-4c81-be08-2be5e8712cf1)
I'll add another screenshot when the reservoir is full

NB
With different ways of learning we can get to our goal together.

**Comment by Xenomes** [comment]
Good to hear!
