### ISSUE TITLE
"LSC Radiator Valve" is not updating anymore in Domoticz

### ISSUE THREAD

**Issue by michelscholte** [Xenomes/Domoticz-TinyTUYA-Plugin#112]
After updating to the latest version, "LSC Radiator Valve" is not updating anymore in Domoticz.

Removed the devices from Domoticz, after first run of the plugin, the devices were recreated correctly. Then the values were updated only once (a few minutes after creation). 

2024-08-09 12:04:37.226 Error: TinyTuya: Device read failed: bfa32d318c3275b98bd6yo
2024-08-09 12:04:37.703 Error: TinyTuya: Device read failed: bff309b4293d42ee51dlmr
2024-08-09 12:04:38.227 Error: TinyTuya: Device read failed: bf593d4c99a947e6ad9wuk
2024-08-09 12:04:39.024 Error: TinyTuya: Device read failed: bf1ed72ebd9cd85b00ousx

[dump.json](https://github.com/user-attachments/files/16559896/dump.json)

**Comment by Xenomes** [comment]
That is not good, i will take a look.

**Comment by Xenomes** [comment]
I can't replicate the issue, can you enable debug to 'all' at the plugin, to see if there is a line number logged there the error concurs.

**Comment by michelscholte** [comment]
Thank you for your response. Attached is the logging of the plugin. Hopefully you can find something.
When I set the setpoint through the TuyApp, I see the change in the plugin logging, but the device is not updated in Domoticz. 
When I change the setpoint in Domoticz and I click on "instellen"(see attachment), I see the change in the TuyaApp, but the setpoint in Domoticz is still the old value.

![Knipsel](https://github.com/user-attachments/assets/432fdf8e-2767-4321-9c8d-90b3c1f0f026)


Thanks in advance

[tinytuya_log.txt](https://github.com/user-attachments/files/16565268/tinytuya_log.txt)

**Comment by Xenomes** [comment]
Did you update the python version also? Can you share the version used in Domoticz?
`2024-08-09 20:00:42.454 TinyTuya: handleThread: 'float' object cannot be interpreted as an integer line 2363`
Have a report with similar error with python version 3.12.*

**Comment by michelscholte** [comment]
Hi Xenomes,

I've updated my message above yours also.
These are my versions:
![version](https://github.com/user-attachments/assets/70f5015e-5386-4f82-b7c1-7d492da5ed0f)
![python_version](https://github.com/user-attachments/assets/4663c881-1789-4879-a838-292685d3ae49)
Domoticz version: 2024.7

**Comment by Xenomes** [comment]
Okay, you are on bookworm. I have create a docker environment to test it with bookworm, Python 3.11.2. I have now the same error. Will try to make a fix so it will work on both python versions. The old version of the plug was working... can you recall the version?

**Comment by michelscholte** [comment]
I've switched to a new SD-card in my RaspberryPi and I've reinstalled everything. So unfortunately, I cannot recall the old version.
You're right. I have installed the bookworm version.

Thanks for your help.

**Comment by Xenomes** [comment]
No problem, I have found the issue, bug is patched and pushed to github. Solved in 1.9.5

**Comment by michelscholte** [comment]
Installed version 1.9.5. It works perfectly again.

Great work.  Thank you very much.
Have a nice weekend.

**Comment by Xenomes** [comment]
Thanks! Good weekend too!

**Comment by Xenomes** [comment]
Don't forget to set Debug back to None.
