### ISSUE TITLE
Extending the trial period does not return the expected result

### ISSUE THREAD

**Issue by GertVersteeg1956** [Xenomes/Domoticz-TinyTUYA-Plugin#114]
Since yesterday morning the tuya devices do not update anymore in domotizc
I tried to extend the trial period but that does not give the desired result
![Screenshot from 2024-08-12 11-40-51](https://github.com/user-attachments/assets/df13880e-adca-49d8-9840-c434b9e5953d)
Also tried the tinytuya wizzard
It gives a quota used up message
Please advise how to proceed
> gert@raspberrypi:~ $ python -m tinytuya wizard -nocolor
TinyTuya Setup Wizard [1.15.1]

    Existing settings:
        API Key=xxxxxxx 
        Secret=xxxxxxx
        DeviceID=bf3b2b83c3e9a27199olvh
        Region=eu

    Use existing credentials (Y/n): Y

Download DP Name mappings? (Y/n): Y

Error from Tuya server: Error from Tuya Cloud: Code 28841004: 'Please upgrade to the official version: Your quota of Trial Edition is used up.'

**Comment by Xenomes** [comment]
I don't have the issue that i need to extent the trail, old time user.
I have see better results with:
![afbeelding](https://github.com/user-attachments/assets/2230a034-c05f-4b48-af58-afbb6281b145)
Then its manual reviewed and mostly approved, you will receive a mail. Some have no extension request after the 6 months.
But this is in Tuya's hands.

**Comment by GertVersteeg1956** [comment]
Thanks,
I'll wait a while. In a week or so I'll try again with your settings

**Comment by GertVersteeg1956** [comment]
In the meantime I created a new iot account with a new project. I disconnected my tuya account form the original iot project and connected to the new project. The integration with Domoticz is operational again.
I also found your local tuya plugin and installed it. My action LSC powerplugs with energy monitoring work fine with it. 
My dehumidifier has some issues. I will try to fork it and try to debug the dehumidifier issue.
It will take some time because I'm fairly new with this type of development.
I'll keep you posted

**Comment by Xenomes** [comment]
> In the meantime I created a new iot account with a new project. I disconnected my tuya account form the original iot project and connected to the new project. The integration with Domoticz is operational again. 

Very good, that is also a solution 😆

> I also found your local tuya plugin and installed it. My action LSC powerplugs with energy monitoring work fine with it. My dehumidifier has some issues. I will try to fork it and try to debug the dehumidifier issue. It will take some time because I'm fairly new with this type of development. I'll keep you posted

Please do, the local version is harder to debug if you don't have the hardware.
