### ISSUE TITLE
Mapping beween domoticz status and airconditioner control

### ISSUE THREAD

**Issue by ilpol984** [Xenomes/Domoticz-TinyTUYA-Plugin#115]
Hello,
after installing the plugin wilt domoticz 2024.7 it created a Mode device for each air conditioner.

The mode device is a stepper device with multiple values: (0,1,2,3,4,5).

I expect these values to correspond to cold, hot, deumidify, auto ecc but I cannot find the mapping anywere.

Where can I find it?

Thank you, regards,

**Comment by Xenomes** [comment]
Can you create a dump.json with the debug_discovery.py script. Then i can check if i can find the matching value.

**Comment by Xenomes** [comment]
Added bitmap detection.
