### ISSUE TITLE
roller shut wifi

### ISSUE THREAD

**Issue by Epik77** [Xenomes/Domoticz-TinyTUYA-Plugin#116]
hello,
the device is not detected by the plugins,
I did the operations requested by the guide.
I hope you can insert this device.

I remain available for other tests.
thanks
[dump.json](https://github.com/user-attachments/files/16689416/dump.json)

**Comment by Xenomes** [comment]
Hi Epik77,
Thanks for the json! It looks all controls are in the json.
Will create code to support it.
Xenomes

**Comment by Xenomes** [comment]
Device added in 1.9.6

**Comment by Epik77** [comment]
hello,
sorry but the position of the device is inverted
I tried to click on the option to reverse the position but it doesn't work
The open and close buttons work correctly.
thank's

**Comment by Xenomes** [comment]
Hi,
I have tested the 'Revere Position' setting, but that is working, enabled, slider to 80, 20 i sent to Tuya.

**Comment by Epik77** [comment]
I apologize
I calibrated the sensor and now the level is correct
but the device signals Closed when it is at 100% (open)
and Open when it is at 0% (closed)
![schermata_open](https://github.com/user-attachments/assets/06525206-a30f-47d7-b3ef-1b75888d9a5c)
![schermataClosed](https://github.com/user-attachments/assets/aa72fcb4-6148-4614-bfa9-3bb65207eb0c)

**Comment by Xenomes** [comment]
Then you need to switch the 'Reverse Position'?
![afbeelding](https://github.com/user-attachments/assets/02e053b5-552e-4b13-936f-2bb5c4abea7c)
![afbeelding](https://github.com/user-attachments/assets/34595b59-2ec2-4347-9e69-34d855130f7b)

**Comment by Epik77** [comment]
I tried but it only reverses the percentage (100% is closed and 0% is open)

the percentages and buttons are OK it's just a display problem

![Immagine 2024-08-24 083849](https://github.com/user-attachments/assets/5fb12c02-3a8c-4848-ad1f-f1c273846dd7)
![Immagine 2024-08-24 084114](https://github.com/user-attachments/assets/d7f9835c-313a-4a08-a0e8-ec8a8d85b976)
![Immagine 2024-08-24 084316](https://github.com/user-attachments/assets/6d31be03-61bb-4010-bf69-4dd9eb2278a7)
![Screenshot 2024-08-24 (08 43 32)](https://github.com/user-attachments/assets/bb4958de-03e5-4480-8db6-a7148e08be00)
![Screenshot 2024-08-24 (08 39 29)](https://github.com/user-attachments/assets/dd543884-97f5-4dfa-9411-9069f09502bf)

**Comment by Xenomes** [comment]
Hi, unfortunately, I don't understand the issue of 'it's just a display problem.' Can you reverse all the functions in Domoticz?

**Comment by Epik77** [comment]
sorry,
if you check "Reverse position" you only change the percentage value
if you check "Reverse Open/Close state" you change the order of the buttons.

sorry,
if you check "Reverse position" you only change the value in percentage
if you check "Reverse Open/Close state" you change the order of the buttons.

Using these functions the state does not change and is always wrong :-(

![esempio_open](https://github.com/user-attachments/assets/7cb8c926-b41e-4b66-baa6-22b0cfe7193a)

**Comment by Xenomes** [comment]
I can not replicate your issue, so it must be in theme that is using the wrong icon. 
![Shutters](https://github.com/user-attachments/assets/af044423-4668-4d34-aeae-42f2f7d31b65)
Can you change to the default theme and test again?

**Comment by Epik77** [comment]
I think the problem is the same as the shelly plugins

https://github.com/domoticz/domoticz/issues/5414

here is the json of my device:

`{
	"ActTime" : 1724744128,
	"AstrTwilightEnd" : "21:36",
	"AstrTwilightStart" : "04:47",
	"CivTwilightEnd" : "20:23",
	"CivTwilightStart" : "06:01",
	"DayLength" : "13:24",
	"NautTwilightEnd" : "20:59",
	"NautTwilightStart" : "05:25",
	"ServerTime" : "2024-08-27 09:35:28",
	"SunAtSouth" : "13:12",
	"Sunrise" : "06:30",
	"Sunset" : "19:54",
	"app_version" : "2024.7",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 0,
			"Data" : "Open",
			"Description" : "",
			"DimmerType" : "none",
			"Favorite" : 1,
			"HardwareDisabled" : false,
			"HardwareID" : 20,
			"HardwareName" : "SmartLife Cloud",
			"HardwareType" : "TinyTUYA (Cloud)",
			"HardwareTypeVal" : 94,
			"HaveDimmer" : true,
			"HaveGroupCmd" : true,
			"HaveTimeout" : false,
			"ID" : "bfb1e9991554ad9131qsah",
			"Image" : "blinds",
			"IsSubDevice" : false,
			"LastUpdate" : "2024-08-27 09:24:46",
			"Level" : 0,
			"LevelInt" : 0,
			"MaxDimLevel" : 100,
			"Name" : "Tapparella Camera",
			"Notifications" : "false",
			"PlanID" : "0",
			"PlanIDs" : 
			[
				0
			],
			"Protected" : false,
			"ReversePosition" : false,
			"ReverseState" : false,
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"Status" : "Open",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "Switch",
			"SwitchType" : "Blinds + Stop",
			"SwitchTypeVal" : 21,
			"Timers" : "false",
			"Type" : "Light/Switch",
			"TypeImg" : "blinds",
			"Unit" : 1,
			"Used" : 1,
			"UsedByCamera" : false,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "1118"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}

`

**Comment by Xenomes** [comment]
What is you domoticz version?

**Comment by Epik77** [comment]
Version: 2024.7
Build Hash: b317cfab1
Compile Date: 2024-07-13 16:59:31
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Mar 23 2024, 16:12:05) [GCC 8.3.0]

**Comment by Xenomes** [comment]
Same domoticz version...

**Comment by Epik77** [comment]
It must be a domoticz bug
I have now adapted my scripts to use the percentage level.
hopefully it will be fixed in the next releases

{
	"ActTime" : 1724755475,
	"AstrTwilightEnd" : "21:36",
	"AstrTwilightStart" : "04:47",
	"CivTwilightEnd" : "20:23",
	"CivTwilightStart" : "06:01",
	"DayLength" : "13:24",
	"NautTwilightEnd" : "20:59",
	"NautTwilightStart" : "05:25",
	"ServerTime" : "2024-08-27 12:44:35",
	"SunAtSouth" : "13:12",
	"Sunrise" : "06:30",
	"Sunset" : "19:54",
	"app_version" : "2024.7",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 0,
			"Data" : "Set Level: 36 %",
			"Description" : "",
			"DimmerType" : "none",
			"Favorite" : 1,
			"HardwareDisabled" : false,
			"HardwareID" : 20,
			"HardwareName" : "SmartLife Cloud",
			"HardwareType" : "TinyTUYA (Cloud)",
			"HardwareTypeVal" : 94,
			"HaveDimmer" : true,
			"HaveGroupCmd" : true,
			"HaveTimeout" : false,
			"ID" : "bfb1e9991554ad9131qsah",
			"Image" : "blinds",
			"IsSubDevice" : false,
			"LastUpdate" : "2024-08-27 12:03:51",
			"Level" : 36,
			"LevelInt" : 36,
			"MaxDimLevel" : 100,
			"Name" : "Tapparella Camera Posizione",
			"Notifications" : "false",
			"PlanID" : "0",
			"PlanIDs" : 
			[
				0
			],
			"Protected" : false,
			"ReversePosition" : false,
			"ReverseState" : false,
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"Status" : "Set Level: 36 %",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "Switch",
			"SwitchType" : "Blinds + Stop",
			"SwitchTypeVal" : 21,
			"Timers" : "false",
			"Type" : "Light/Switch",
			"TypeImg" : "blinds",
			"Unit" : 1,
			"Used" : 1,
			"UsedByCamera" : false,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "1118"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}

**Comment by Epik77** [comment]
I'm reopening this issue to compare the tiny tuya roller shutter with another tuya zigbee device:

`<html><body>

ActTime | 1725950340
-- | --
AstrTwilightEnd | "21:07"
AstrTwilightStart | "05:07"
CivTwilightEnd | "19:58"
CivTwilightStart | "06:17"
DayLength | "12:44"
NautTwilightEnd | "20:32"
NautTwilightStart | "05:43"
ServerTime | "2024-09-10 08:39:00"
SunAtSouth | "13:07"
Sunrise | "06:45"
Sunset | "19:29"
app_version | "2024.7"
result |  
0 |  
AddjMulti | 1
AddjMulti2 | 1
AddjValue | 0
AddjValue2 | 0
BatteryLevel | 255
CustomImage | 0
Data | "Closed"
Description | ""
DimmerType | "none"
Favorite | 1
HardwareDisabled | false
HardwareID | 20
HardwareName | "SmartLife Cloud"
HardwareType | "TinyTUYA (Cloud)"
HardwareTypeVal | 94
HaveDimmer | true
HaveGroupCmd | true
HaveTimeout | false
ID | "bfb1e9991554ad9131qsah"
Image | "blinds"
IsSubDevice | false
LastUpdate | "2024-09-10 07:37:27"
Level | 100
LevelInt | 100
MaxDimLevel | 100
Name | "Tapparella Camera Posizione"
Notifications | "false"
PlanID | "6"
PlanIDs |  
0 | 6
Protected | false
ReversePosition | false
ReverseState | false
ShowNotifications | true
SignalLevel | "-"
Status | "Closed"
StrParam1 | ""
StrParam2 | ""
SubType | "Switch"
SwitchType | "Blinds + Stop"
SwitchTypeVal | 21
Timers | "false"
Type | "Light/Switch"
TypeImg | "blinds"
Unit | 1
Used | 1
UsedByCamera | false
XOffset | "945"
YOffset | "430"
idx | "1118"
status | "OK"
title | "Devices"


</body>
</html>`

Device zigbee:

`<html><body>

ActTime | 1725950375
-- | --
AstrTwilightEnd | "21:07"
AstrTwilightStart | "05:07"
CivTwilightEnd | "19:58"
CivTwilightStart | "06:17"
DayLength | "12:44"
NautTwilightEnd | "20:32"
NautTwilightStart | "05:43"
ServerTime | "2024-09-10 08:39:35"
SunAtSouth | "13:07"
Sunrise | "06:45"
Sunset | "19:29"
app_version | "2024.7"
result |  
0 |  
AddjMulti | 1
AddjMulti2 | 1
AddjValue | 0
AddjValue2 | 0
BatteryLevel | 255
CustomImage | 0
Data | "Open"
Description | ""
DimmerType | "none"
Favorite | 1
HardwareDisabled | false
HardwareID | 18
HardwareName | "HomeAssistant"
HardwareType | "MQTT Auto Discovery Client Gateway with LAN interface"
HardwareTypeVal | 125
HaveDimmer | true
HaveGroupCmd | true
HaveTimeout | false
ID | "0xa4c13895ffb82e8e_cover_zigbee2mqtt2"
Image | "blinds"
IsSubDevice | false
LastUpdate | "2024-09-10 07:35:24"
Level | 100
LevelInt | 100
MaxDimLevel | 100
Name | "Tapparella Cucina Posizione"
Notifications | "false"
PlanID | "9"
PlanIDs |  
0 | 9
Protected | false
ReversePosition | false
ReverseState | false
ShowNotifications | true
SignalLevel | 5
Status | "Open"
StrParam1 | ""
StrParam2 | ""
SubType | "Switch"
SwitchType | "Blinds + Stop"
SwitchTypeVal | 21
Timers | "false"
Type | "Light/Switch"
TypeImg | "blinds"
Unit | 1
Used | 1
UsedByCamera | false
XOffset | "1157"
YOffset | "654"
idx | "1102"
status | "OK"
title | "Devices"


</body>
</html>`

**Comment by Xenomes** [comment]
This is the compare:
![afbeelding](https://github.com/user-attachments/assets/e7118e18-e7ab-4331-a2bb-3c8ce65191e7)

**Comment by Epik77** [comment]
the usage percentage is ok

`{
	"ActTime" : 1726070766,
	"AstrTwilightEnd" : "21:05",
	"AstrTwilightStart" : "05:09",
	"CivTwilightEnd" : "19:56",
	"CivTwilightStart" : "06:18",
	"DayLength" : "12:41",
	"NautTwilightEnd" : "20:30",
	"NautTwilightStart" : "05:44",
	"ServerTime" : "2024-09-11 18:06:06",
	"SunAtSouth" : "13:07",
	"Sunrise" : "06:46",
	"Sunset" : "19:28",
	"app_version" : "2024.7",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 0,
			"Data" : "Set Level: 29 %",
			"Description" : "",
			"DimmerType" : "none",
			"Favorite" : 1,
			"HardwareDisabled" : false,
			"HardwareID" : 20,
			"HardwareName" : "SmartLife Cloud",
			"HardwareType" : "TinyTUYA (Cloud)",
			"HardwareTypeVal" : 94,
			"HaveDimmer" : true,
			"HaveGroupCmd" : true,
			"HaveTimeout" : false,
			"ID" : "bfb1e9991554ad9131qsah",
			"Image" : "blinds",
			"IsSubDevice" : false,
			"LastUpdate" : "2024-09-11 12:27:01",
			"Level" : 29,
			"LevelInt" : 29,
			"MaxDimLevel" : 100,
			"Name" : "Tapparella Camera Posizione",
			"Notifications" : "false",
			"PlanID" : "6",
			"PlanIDs" : 
			[
				6
			],
			"Protected" : false,
			"ReversePosition" : false,
			"ReverseState" : false,
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"Status" : "Set Level: 29 %",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "Switch",
			"SwitchType" : "Blinds + Stop",
			"SwitchTypeVal" : 21,
			"Timers" : "false",
			"Type" : "Light/Switch",
			"TypeImg" : "blinds",
			"Unit" : 1,
			"Used" : 1,
			"UsedByCamera" : false,
			"XOffset" : "945",
			"YOffset" : "430",
			"idx" : "1118"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}
`


Other Device ziggbee

`{
	"ActTime" : 1726070814,
	"AstrTwilightEnd" : "21:05",
	"AstrTwilightStart" : "05:09",
	"CivTwilightEnd" : "19:56",
	"CivTwilightStart" : "06:18",
	"DayLength" : "12:41",
	"NautTwilightEnd" : "20:30",
	"NautTwilightStart" : "05:44",
	"ServerTime" : "2024-09-11 18:06:54",
	"SunAtSouth" : "13:07",
	"Sunrise" : "06:46",
	"Sunset" : "19:28",
	"app_version" : "2024.7",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 0,
			"Data" : "Set Level: 60 %",
			"Description" : "",
			"DimmerType" : "none",
			"Favorite" : 1,
			"HardwareDisabled" : false,
			"HardwareID" : 18,
			"HardwareName" : "HomeAssistant",
			"HardwareType" : "MQTT Auto Discovery Client Gateway with LAN interface",
			"HardwareTypeVal" : 125,
			"HaveDimmer" : true,
			"HaveGroupCmd" : true,
			"HaveTimeout" : false,
			"ID" : "0xa4c13895ffb82e8e_cover_zigbee2mqtt2",
			"Image" : "blinds",
			"IsSubDevice" : false,
			"LastUpdate" : "2024-09-11 13:45:00",
			"Level" : 60,
			"LevelInt" : 60,
			"MaxDimLevel" : 100,
			"Name" : "Tapparella Cucina Posizione",
			"Notifications" : "false",
			"PlanID" : "9",
			"PlanIDs" : 
			[
				9
			],
			"Protected" : false,
			"ReversePosition" : false,
			"ReverseState" : false,
			"ShowNotifications" : true,
			"SignalLevel" : 1,
			"Status" : "Set Level: 60 %",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "Switch",
			"SwitchType" : "Blinds + Stop",
			"SwitchTypeVal" : 21,
			"Timers" : "false",
			"Type" : "Light/Switch",
			"TypeImg" : "blinds",
			"Unit" : 1,
			"Used" : 1,
			"UsedByCamera" : false,
			"XOffset" : "1157",
			"YOffset" : "654",
			"idx" : "1102"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}`

**Comment by Xenomes** [comment]
Hi, so in the real world, both blinds are closed, but in the data, the Tuya one shows as open. Is that correct? In the Tuya app, the controls are not inverted, and the wiring of the incorrect blind is correct, right?

**Comment by Epik77** [comment]
yes exactly the level is correct but the status (data field) is wrong.
The same device (zigbee version) works correctly (the data field is seen correctly). The wiring is correct and also the tuya app works correctly.

**Comment by Xenomes** [comment]
I changed a value, hoping it fixes your issue. Please check version 1.9.9b.

**Comment by Epik77** [comment]
ok now it works properly
thank's for your support.



`{
	"ActTime" : 1726228317,
	"AstrTwilightEnd" : "21:01",
	"AstrTwilightStart" : "05:11",
	"CivTwilightEnd" : "19:52",
	"CivTwilightStart" : "06:20",
	"DayLength" : "12:36",
	"NautTwilightEnd" : "20:26",
	"NautTwilightStart" : "05:46",
	"ServerTime" : "2024-09-13 13:51:57",
	"SunAtSouth" : "13:06",
	"Sunrise" : "06:48",
	"Sunset" : "19:24",
	"app_version" : "2024.7",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 0,
			"Data" : "Open",
			"Description" : "",
			"DimmerType" : "none",
			"Favorite" : 1,
			"HardwareDisabled" : false,
			"HardwareID" : 20,
			"HardwareName" : "SmartLife Cloud",
			"HardwareType" : "TinyTUYA (Cloud)",
			"HardwareTypeVal" : 94,
			"HaveDimmer" : true,
			"HaveGroupCmd" : true,
			"HaveTimeout" : false,
			"ID" : "bfb1e9991554ad9131qsah",
			"Image" : "blinds",
			"IsSubDevice" : false,
			"LastUpdate" : "2024-09-13 13:48:23",
			"Level" : 100,
			"LevelInt" : 100,
			"MaxDimLevel" : 100,
			"Name" : "Tapparella Camera Posizione",
			"Notifications" : "false",
			"PlanID" : "6",
			"PlanIDs" : 
			[
				6
			],
			"Protected" : false,
			"ReversePosition" : false,
			"ReverseState" : false,
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"Status" : "Open",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "Switch",
			"SwitchType" : "Blinds + Stop",
			"SwitchTypeVal" : 21,
			"Timers" : "false",
			"Type" : "Light/Switch",
			"TypeImg" : "blinds",
			"Unit" : 1,
			"Used" : 1,
			"UsedByCamera" : false,
			"XOffset" : "945",
			"YOffset" : "430",
			"idx" : "1118"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}`

**Comment by Xenomes** [comment]
Perfect!
