### ISSUE TITLE
name 'product_id' is not defined line 877

### ISSUE THREAD

**Issue by vespino** [Xenomes/Domoticz-TinyTUYA-Plugin#117]
I have been getting this error ever since updating a few minutes ago:

`2024-09-05 16:37:14.054 Error: TinyTUYA: handleThread: name 'product_id' is not defined line 877`

The error repeats every 10 seconds or so. Plugin seems to work fine otherwise.

**Comment by Xenomes** [comment]
Hi, it looks like your device is missing a product_id. I'll work on a fix.

**Comment by Xenomes** [comment]
Found the issue, fixed in the latest version.
