### ISSUE TITLE
After update from 1.7.9 to 1.9.7

### ISSUE THREAD

**Issue by Epik77** [Xenomes/Domoticz-TinyTUYA-Plugin#119]
sorry

after the update the on/off switches (SMART switch) of the lights no longer work

deleting the devices and rescanning the message comes out:

this devices is note recognized.....

this is my dump
[dump.json](https://github.com/user-attachments/files/16913277/dump.json)

Thank's

**Comment by Epik77** [comment]
I downgraded to version 1.7.9 and on/off switches (SMART switch) work fine.

**Comment by Xenomes** [comment]
Found the issue, put the category tdq at dimmer had to be switch 😣 fixed in the latest push.
