### ISSUE TITLE
error log Domoticz

### ISSUE THREAD

**Issue by stefg73** [Xenomes/Domoticz-TinyTUYA-Plugin#12]
Hi,

i've sometimes this error in Domoticz's logs : 
Error: TinyTUYA: handleThread: 'result'

but all seems to work fine...

What's it ?

**Comment by Xenomes** [comment]
Hi, I don't have see this in my live version. Maybe it is relate with a internet drop. do you get it often?

**Comment by stefg73** [comment]
hi, no i don't get it often. All my system and captors are behind a vpn provider, perhaps you're wright : internet drop.

**Comment by Xenomes** [comment]
Could be possible. Will close the issue can't replicate it.
