### ISSUE TITLE
BREAKER WIFI - SWITCH not recognized.

### ISSUE THREAD

**Issue by titis78** [Xenomes/Domoticz-TinyTUYA-Plugin#120]
Hello, I can't get the ON/OFF switch for breaker device bf59f635611ff44fe3l03h. It's a wifi switch and the electrical properties (A,V,W) are shown in Domoticz but the function switch is not recognized. Dump File is joined. I test all mode Standard and DP instruction, it's the same result after reboot.
[dump.json](https://github.com/user-attachments/files/16922942/dump.json)

**Comment by Xenomes** [comment]
Hi, the device was created in my latest version of the code. I think you weren't on the latest version.

**Comment by titis78** [comment]
Hi, i test the new version 1.9.8 but it's not work for my breaker WIFI. I put the new dump file here.
[dump.json](https://github.com/user-attachments/files/16932283/dump.json)

**Comment by Xenomes** [comment]
The extra controls have been added to version 1.9.9.

**Comment by titis78** [comment]
[dump.json](https://github.com/user-attachments/files/16947697/dump.json)
Here the new dump after i test new version 1.9.9. I have the switch recognised now (Thank You) but i can't command it. It stay ON when i put it OFF.

**Comment by Xenomes** [comment]
On/Off in domoticz or in the Tuya app?

**Comment by titis78** [comment]
On/Off in Domoticz. In Tuya App and Google Home, that's work fine !

**Comment by Xenomes** [comment]
Okay, Found it, check version 1.9.9a

**Comment by titis78** [comment]
Thanks you, it works.

**Comment by Xenomes** [comment]
Perfect!
