### ISSUE TITLE
Local heat recovery ventilator

### ISSUE THREAD

**Issue by fdmekinabo** [Xenomes/Domoticz-TinyTUYA-Plugin#122]
I have a local heat recovery ventilator, and while the current code correctly recognizes the ventilator switch, it is crucial to control the operating modes specific to this type of system. For a heat recovery ventilator, the key modes include exhaust, supply, and ventilate (heat recovery).

I have made some adaptations to the code that allow me to control these modes, and it’s working well for my setup. Specifically, I added the following modes for the device fan: supply, ventilate, and exhaust, along with fan speed control.

I believe incorporating these changes into future updates would be beneficial for users with similar systems. Below are three additions I made to the plugin.py file to support fan mode control:
1: 

if dev_type == 'fan':
                if Command == 'Set Level' and Unit == 4:
                    mode = Devices[DeviceID].Units[Unit].Options['LevelNames'].split('|')
                    SendCommandCloud(DeviceID, 'mode', mode[int(Level / 10)])
                    UpdateDevice(DeviceID, 4, Level, 1, 0)
2:

if dev_type == 'fan':
                    if createDevice(dev['id'], 4) and searchCode('mode', FunctionProperties):
                        for item in FunctionProperties:
                            if item['code'] == 'mode':
                                the_values = json.loads(item['values'])
                                mode = ['off']
                                mode.extend(the_values.get('range'))
                                options = {}
                                options['LevelOffHidden'] = 'true'
                                options['LevelActions'] = ''
                                options['LevelNames'] = '|'.join(mode)
                                options['SelectorStyle'] = '1'
                        Domoticz.Unit(Name=dev['name'], DeviceID=dev['id'], Unit=4, Type=244, Subtype=62, Options=options, Switchtype=18, Image=9, Used=1).Create()

3:

if dev_type == 'fan':
                        if searchCode('mode', FunctionProperties):
                            current_mode = StatusDeviceTuya('mode')  # Read the current mode from the device
        # Map the mode to Domoticz selector values
                            if current_mode == 'supply':
                             mode_value = 10  # Ventilate mode
                            elif current_mode == 'exhaust':
                             mode_value = 20  # Exhaust mode
                            elif current_mode == 'ventilate':
                             mode_value = 30  # Supply mode
                            else:
                             mode_value = 0  # Default to 0 if mode is unknown
        # Update the device in Domoticz with the correct selector value
                            UpdateDevice(dev['id'], 4, mode_value, 0, 0)

**Comment by Xenomes** [comment]
Hi fdmekinabo,

I have a routine to find the used modes in the Tuya environment, but I need the dump.json file to verify if the correct one is selected. Could you create it by running debug_discovering.py in the tools directory?

**Comment by fdmekinabo** [comment]
Here it is, thanks: 
[dump.json](https://github.com/user-attachments/files/16985671/dump.json)

**Comment by Xenomes** [comment]
Thanks for the Json, there where a lot of data in this device.

**Comment by Xenomes** [comment]
Device update added to version 2.0.0

**Comment by fdmekinabo** [comment]
Great! Everything works. Thank you.

**Comment by Xenomes** [comment]
Perfect! thanks for the feed back!
