### ISSUE TITLE
Partly supported LSC RGB 200LED Stringlight

### ISSUE THREAD

**Issue by Pjedr** [Xenomes/Domoticz-TinyTUYA-Plugin#124]
Partly supported LSC RGB 200LED Stringlight.
I can turn it On or Off, but not change modes.

{
    "name": "Kerstlicht Kleurenstring",
    "id": "bf1d259cd88cd2c1865p1d",
    "key": "Deleted",
    "mac": "cc:8c:bf:bb:15:48",
    "uuid": "6e79e60a78d3adcc",
    "category": "dc",
    "product_name": "LSC Stringlight RGB",
    "product_id": "hdpemggvmsynwdjw",
    "biz_type": 18,
    "model": "6025000100",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/bay16279833154642Sqp/16547793593de469d00b8.png"
  },

DP Instruction	Standard Instruction
switch_led
work_mode
bright_value
colour_data
countdown
music_data
control_data
classicmode

Properties of device: bf1d259cd88cd2c1865p1d
{
  "result": {
    "category": "dc",
    "functions": [
      {
        "code": "switch_led",
        "desc": "{}",
        "name": "\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "desc": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}",
        "name": "\u6a21\u5f0f",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value",
        "desc": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}",
        "name": "\u4eae\u5ea6\u503c",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "colour_data",
        "desc": "{\"maxlen\":255}",
        "name": "\u5f69\u5149",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "countdown",
        "desc": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5012\u8ba1\u65f6\u5269\u4f59\u65f6\u95f4",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "music_data",
        "desc": "{\"maxlen\":255}",
        "name": "\u97f3\u4e50\u706f",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "control_data",
        "desc": "{\"maxlen\":255}",
        "name": "\u8c03\u8282",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "classicmode",
        "desc": "{\"maxlen\":255}",
        "name": "\u573a\u666f",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "name": "\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "name": "\u6a21\u5f0f",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value",
        "name": "\u4eae\u5ea6\u503c",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "colour_data",
        "name": "\u5f69\u5149",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "countdown",
        "name": "\u5012\u8ba1\u65f6\u5269\u4f59\u65f6\u95f4",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "classicmode",
        "name": "\u573a\u666f",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ]
  },
  "success": true,
  "t": 1726438453437,
  "tid": "d6ec476673af11efb77736033862a1ba"
}
Status of device: bf1d259cd88cd2c1865p1d
{
  "result": [
    {
      "code": "switch_led",
      "value": true
    },
    {
      "code": "work_mode",
      "value": "white"
    },
    {
      "code": "bright_value",
      "value": 1000
    },
    {
      "code": "colour_data",
      "value": ""
    },
    {
      "code": "countdown",
      "value": 0
    },
    {
      "code": "classicmode",
      "value": "00000003e803e803e803e8"
    }
  ],
  "success": true,
  "t": 1726438453705,
  "tid": "d714cb3873af11ef88b02ac421ecbce6"
}

**Comment by Xenomes** [comment]
Hi Pjerd,
The work_mode is chosen if the light is changed from White to Color.
Scene and Music are not used, of Scene there is noting to select and Music was never requested.
