### ISSUE TITLE
8ch Tuya Wireless Switch Modul

### ISSUE THREAD

**Issue by ilkaskim** [Xenomes/Domoticz-TinyTUYA-Plugin#127]
Hello, can you please add this module to the list. It does appear in Domoticz but not all relays are displayed

https://de.aliexpress.com/item/1005007259679325.html?spm=a2g0o.order_list.order_list_main.40.135f5c5fOiYxVv&gatewayAdapt=glo2deu

[dump.json](https://github.com/user-attachments/files/17318405/dump.json)

Thank you

**Comment by Xenomes** [comment]
Hi, that's strange. I’m using this code: [f'switch_{i}' for i in range(1, 9)], so either none or all 8 should be created.
Could you upload the devices.json file and mask the sensitive key data?

**Comment by ilkaskim** [comment]
Can you please tell me how to get the device.json file? dump.json I know how to do it. 
There are 8 channels and 5 appear in domoticz. I can also switch the 5 channels via domoticz.

**Comment by Xenomes** [comment]
I think you posted the issue on the wrong plugin, You need the cloud version support. 😉 If so i can move it over to the other plugin.

**Comment by Xenomes** [comment]
Found the problem, fixed in 202
