### ISSUE TITLE
[Solved] 2nd channel of switch ignored - cannot be switched

### ISSUE THREAD

**Issue by plontajos** [Xenomes/Domoticz-TinyTUYA-Plugin#128]
Hi, I have two channel switch for controlling window blinds. Unfortunately only first channel is operable, the second is ignored by tinytuya plugin.
The simplest idea is to clone switch with first channel (CH#1) and adjust it to steer the second one (CH#2).

Is there any possibility to fix it? Can I do it by myslef (basic programming knowlage?).

Product Name
2CH WiFi Curtain Module
Product Category
clkg

General settings 
control | Enum | {   "range": [     "open",     "stop",     "close",     "continue"   ] } (CH#1)
percent_control | Integer | {   "unit": "%",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 } (CH#1)
cur_calibration | Enum | {   "range": [     "start",     "end"   ] } (CH#1)
control_2 | Enum | {   "range": [     "open",     "stop",     "close",     "continue"   ] } (CH#2)
percent_control_2 | Integer | {   "unit": "%",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 } (CH#2)
cur_calibration_2 | Enum | {   "range": [     "start",     "end"   ] } (CH#2)
control_back | Enum | {   "range": [     "forward",     "back"   ] } (CH#1)
control_back_2 | Enum | {   "range": [     "forward",     "back"   ] } (CH#2)
quick_calibration_1 | Integer | {   "unit": "s",   "min": 0,   "max": 900,   "scale": 0,   "step": 1 } (CH#1)
quick_calibration_2 | Integer | {   "unit": "s",   "min": 0,   "max": 900,   "scale": 0,   "step": 1 } (CH#2)

Thanks for any advice in advance.

**Comment by Xenomes** [comment]
Hi Plontajos, I’ve added the second channel to version 2.0.3. Can you test it?

**Comment by plontajos** [comment]
Thanks for prompt answer and fixing it.
It works perfectly. Thanks.

**Comment by plontajos** [comment]
Sovled

**Comment by Xenomes** [comment]
Thanks for the feed back!

**Comment by plontajos** [comment]
If the trial version of IoT Core for half a year will be expired, do I need to renew it each 6 month?
After that it will stop working, isn't it? 

Local tuya should work faster (LAN) and without necessity of IoT Core interaction?

**Comment by Xenomes** [comment]
> If the trial version of IoT Core for half a year will be expired, do I need to renew it each 6 month? After that it will stop working, isn't it?

Yes, once the trial version of IoT Core for half a year expires, you will need to renew it every 6 months if you want to continue using the service. After the trial period ends, the service will stop working unless it's renewed.

> Local tuya should work faster (LAN) and without necessity of IoT Core interaction?

As for Local Tuya, it operates over the LAN (local network) and doesn’t require interaction with IoT Core for basic control functions. This reduces reliance on cloud services. However, any advanced features or cloud-based interactions may still require IoT Core.
