### ISSUE TITLE
Could you add an ir remote to tuya?

### ISSUE THREAD

**Issue by stadswandelaar** [Xenomes/Domoticz-TinyTUYA-Plugin#135]
Hallo, I would like to use a tuya ir remote with tinytuya. I made the dump.json, and hope you will find time to take a look at it, and perhaps add this to tinytuya.

Regards,

Enno Oosterhuis

[dump.json](https://github.com/user-attachments/files/17601363/dump.json)

**Comment by Xenomes** [comment]
Hi Stadswandelaar.

Sorry, neither Tuya nor TinyTuya returned any information for this device.

```
Properties of device: bf7db9c82acbb66782ekd2
{
  "result": {
    "category": "wnykq"
  },
  "success": true,
  "t": 1730475015179,
  "tid": "312886d8986611ef894136243096d294"
}
Status of device: bf7db9c82acbb66782ekd2
{
  "result": [],
  "success": true,
  "t": 1730475015374,
  "tid": "314fe520986611efbfa92a8db75a9554"
}

```
