### ISSUE TITLE
Not supported  Dimmer module chfpey4klfcp1ipl

### ISSUE THREAD

**Issue by WimHager** [Xenomes/Domoticz-TinyTUYA-Plugin#137]
Please can you add this one:

List of devices: 
[
  {
    "name": "Dimmer Woonkamer",
    "id": "bfaf01fc6340ed009flflr",
    "key": "Deleted",
    "mac": "fc:3c:d7:66:c6:4d",
    "category": "tdq",
    "product_name": "Dimmer Module",
    "product_id": "chfpey4klfcp1ipl",
    "biz_type": 0,
    "model": "",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1562830083757AoBrF/e704105a7242eadf28a07854e140ed9c.png",
    "uuid": "d2cca7528a2517fe"
  }
]

Properties of device: bfaf01fc6340ed009flflr
{
  "result": {
    "category": "tdq",
    "functions": [
      {
        "code": "switch_led_1",
        "desc": "{}",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value_1",
        "desc": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}",
        "name": "\u4eae\u5ea6\u503c1",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "brightness_min_1",
        "desc": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}",
        "name": "\u6700\u5c0f\u4eae\u5ea61",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "brightness_max_1",
        "desc": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}",
        "name": "\u6700\u5927\u4eae\u5ea61",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "desc": "{\"range\":[\"0\",\"1\",\"2\"]}",
        "name": "\u4e0a\u7535\u72b6\u6001\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      }
    ],
    "status": [
      {
        "code": "switch_led_1",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value_1",
        "name": "\u4eae\u5ea6\u503c1",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "brightness_min_1",
        "name": "\u6700\u5c0f\u4eae\u5ea61",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "brightness_max_1",
        "name": "\u6700\u5927\u4eae\u5ea61",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "name": "\u4e0a\u7535\u72b6\u6001\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      }
    ]
  },
  "success": true,
  "t": 1730998278145,
  "tid": "823c9e679d2811efacb2ded37fff273c"
}
Status of device: bfaf01fc6340ed009flflr
{
  "result": [
    {
      "code": "switch_led_1",
      "value": false
    },
    {
      "code": "bright_value_1",
      "value": 714
    },
    {
      "code": "brightness_min_1",
      "value": 200
    },
    {
      "code": "brightness_max_1",
      "value": 1000
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "relay_status",
      "value": "0"
    }
  ],
  "success": true,
  "t": 1730998278451,
  "tid": "826d7b2b9d2811efacb2ded37fff273c"
}

**Comment by Xenomes** [comment]
Thanks for the Json, i will added it a soon as possible.

**Comment by WimHager** [comment]
Thank you! Works like a charm.

**Comment by Xenomes** [comment]
Perfect!
