### ISSUE TITLE
Bewegingssensor "PIR Motion Sensor" does not read data.

### ISSUE THREAD

**Issue by WimHager** [Xenomes/Domoticz-TinyTUYA-Plugin#139]
Bewegingssensor "PIR Motion Sensor" does not read data.
Status stay on OFF

Image link https://m.media-amazon.com/images/I/31z2UicsAwL._AC_SL1001_.jpg

Devices: 
TINY-TUYA	bf051c476faeaef8f57scs	1	Bewegingssensor	Light/Switch	Switch	Off

Json: 

List of devices: 
[
   {
    "name": "Bewegingssensor",
    "id": "bf051c476faeaef8f57scs",
    "key": "Deleted",
    "mac": "4c:a9:19:e6:32:fc",
    "category": "pir",
    "product_name": "Motion Sensor",
    "product_id": "rjzon9kyxpoeksj3",
    "biz_type": 0,
    "model": "",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1525749833414yotNt/977689dc3cf45a12a3b33f1d4cb9ff36.png",
    "uuid": "9a9a121acc3be4aa"
  }
]

Properties of device: bf051c476faeaef8f57scs
{
  "result": {
    "category": "pir",
    "status": [
      {
        "code": "pir",
        "name": "\u4eba\u4f53\u611f\u5e94\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"pir\",\"none\"]}"
      },
      {
        "code": "battery_state",
        "name": "\u7535\u6c60\u7535\u91cf\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      }
    ]
  },
  "success": true,
  "t": 1731179338524,
  "tid": "12a371b39ece11ef8f0f9ea63fc007e4"
}
Status of device: bf051c476faeaef8f57scs
{
  "result": [
    {
      "code": "pir",
      "value": "none"
    },
    {
      "code": "battery_state",
      "value": "high"
    }
  ],
  "success": true,
  "t": 1731179338822,
  "tid": "12d144dc9ece11efacb2ded37fff273c"
}

**Comment by Xenomes** [comment]
The code is working, but it’s possible that the status change isn’t long enough to be detected by TinyTuya when checked once per minute.

**Comment by WimHager** [comment]
Ah, Ok, Ill close this issue. Thx.
Xenomes was right, after starting a log file there are detection's.

**Comment by Xenomes** [comment]
Hi, i have made a update to the plugin that may be resolves your issue. See https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/issues/154#issuecomment-2620041279
