### ISSUE TITLE
T&H tuya sensor not reconised

### ISSUE THREAD

**Issue by christophevielfrederic** [Xenomes/Domoticz-TinyTUYA-Plugin#15]
Hi,
My T&H sensor is well processed on Tuya mobile app (trademark of the sensor : KSIX).
But not recognised on Domoticz.
On Device panel i get this message :
"This device is not reconised, edit and run the debug_discovery with python from the tools directory and receate a issue report at https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/issues so the device can be added."
So please find dump.json file attached.
The concerned device is ;
"id": "bf6e4369609b7e32b4aeup",

As i'm novice in this area please be comprehensive in case of i did not provide all mandatory information.
regards
[dump.json.txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/10669001/dump.json.txt)

**Comment by Xenomes** [comment]
Hi,
The device is report empty json:
```
{
  "result": {
    "category": "qt"
  },
  "success": true,
  "t": 1675709505671,
  "tid": "4dc9b07fa64f11edbd98a6d801a7eabc"
}
```
Can you check at iot.tuya.com => Cloud => your project => Devices 
at 'View Devices by Product.' check i setting as image.
![afbeelding](https://user-images.githubusercontent.com/11648297/217083234-999c20f0-78a3-465e-8195-1ddc36e9ad01.png)

**Comment by christophevielfrederic** [comment]
Hi Thanks for your reply.
It seems to me that it is already the case :
[image: image.png]

Do you need anything else ?
Regards.

**Comment by Xenomes** [comment]
Ok, first device that is empty. Maybe the problem is at the Tinytuya module level. You could try to make a report that you got a unsupported device. https://github.com/jasonacox/tinytuya/issues

Edit:
Try update Tinytuya, see that version 1.10.1 is release.

**Comment by Xenomes** [comment]
Indeed can you try the other setting?

**Comment by Xenomes** [comment]
DP Instruction is the best way. Added in the new version.
