### ISSUE TITLE
Please add LSC smart connect smoke detector

### ISSUE THREAD

**Issue by koningdde** [Xenomes/Domoticz-TinyTUYA-Plugin#16]
I would like to add the smoke detector to my domoticz systems, this is the data dump:

Thanks in advance!

 {
    "name": "Rook woonkamer",
    "id": "61840056c45bbee91776",
    "key": "Deleted",
    "mac": "c4:5b:be:e9:17:76",
    "category": "ywbj",
    "product_name": "Smoke Alarm",
    "product_id": "cjlutkuuvxnie17o",
    "biz_type": 0,
    "model": "PD-8912",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1541056239985fDGjj/a1d1460f5a071a3412cc0c4659fc9756.png",
    "uuid": "61840056c45bbee91776"
  },

Functions of device: 61840056c45bbee91776
 {
  "result": {
    "category": "ywbj",
    "functions": []
  },
  "success": true,
  "t": 1675799007451,
  "tid": "b104e068a71f11edbe05a63cfb33a057"
}

Properties of device: 61840056c45bbee91776
 {
  "result": {
    "category": "ywbj",
    "status": [
      {
        "code": "battery_state",
        "name": "\u7535\u6c60\u7535\u91cf\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      }
    ]
  },
  "success": true,
  "t": 1675799007671,
  "tid": "b12913e1a71f11ed9a310aeeb3bc8fba"
}

Status of device: 61840056c45bbee91776
 {
  "result": [
    {
      "code": "battery_state",
      "value": "high"
    }
  ],
  "success": true,
  "t": 1675799007849,
  "tid": "b144423fa71f11edbe05a63cfb33a057"
}

**Comment by Xenomes** [comment]
There is only a 'battery_state' in the status of device. I see no possibility to add device. I am not sure if this is a Tuya or Tinytuya problem. https://developer.tuya.com/en/docs/iot/s?id=K9gf48r5i2iiy

**Comment by koningdde** [comment]
I see the problem here, the Tuya platform don't has this instruction set:
moke_sensor_status | Status value of smoke detector | Enum | {“range”:[“alarm”,“normal”]}

I will request a change at Tuya.

Thanks!

**Comment by koningdde** [comment]
My Tuya develop cloud account is expired, i cannot renew it anymore. So no more testing, for users after jun-2021 the plugin is only usable for one month.... have to workout another way to control the devices.

Thanks for your help anyway!

**Comment by Xenomes** [comment]
Hi,
You can extend the trail with 6 months at https://iot.tuya.com/cloud/products/apply-extension
The HA community has the same issue, i follow the progress.
