### ISSUE TITLE
Please add LSC smart connect door sensor

### ISSUE THREAD

**Issue by koningdde** [Xenomes/Domoticz-TinyTUYA-Plugin#17]
Please add LSC smart connect door sensor.

This is a battery powered door sensor, this would also be nice in the domoticz system.
Thanks! 

This is the dump:

{
    "name": "Garage binnendeur",
    "id": "310068152462ab13a20d",
    "key": "Deleted",
    "mac": "24:62:ab:13:a2:0d",
    "category": "mcs",
    "product_name": "Smart Door/window sensor",
    "product_id": "i22freyypqdcirq3",
    "biz_type": 0,
    "model": "SW82",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/15526362116fs8am7qlw_0.png",
    "uuid": "310068152462ab13a20d"
  },

Functions of device: 310068152462ab13a20d
 {
  "result": {
    "category": "mcs",
    "functions": []
  },
  "success": true,
  "t": 1675799006826,
  "tid": "b0a7c9aca71f11edbe05a63cfb33a057"
}

Properties of device: 310068152462ab13a20d
 {
  "result": {
    "category": "mcs",
    "status": [
      {
        "code": "doorcontact_state",
        "name": "\u95e8\u78c1\u72b6\u6001",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_state",
        "name": "\u7535\u6c60\u7535\u91cf\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      }
    ]
  },
  "success": true,
  "t": 1675799007035,
  "tid": "b0c6c983a71f11ed9a310aeeb3bc8fba"
}

Status of device: 310068152462ab13a20d
 {
  "result": [
    {
      "code": "doorcontact_state",
      "value": false
    },
    {
      "code": "battery_state",
      "value": "low"
    }
  ],
  "success": true,
  "t": 1675799007232,
  "tid": "b0e67919a71f11edbe05a63cfb33a057"
}

**Comment by Xenomes** [comment]
Hi,
Added to Develop version 1.4.1, keep in mind that the plugin is pulling data for Tuya so a contact switch can take up to 60 sec to register in Domoticz.

**Comment by koningdde** [comment]
This works perfect, thank you. I am aware for the update time, so i don't think it should be used for intrusion detection.

**Comment by Xenomes** [comment]
'intrusion detection' Yeah max 60 sec delay 😅
