### ISSUE TITLE
Nice to have: Add PIR control to smart flood light 

### ISSUE THREAD

**Issue by koningdde** [Xenomes/Domoticz-TinyTUYA-Plugin#18]
This device has some aditional functions, the flood light has a pir sensor that can be controlled.

So the state can be: Off - On - Automatic. The sensor can be modified: Light sense (lux), distance and delay off. There is also a function that dims the light when no movement is detected and after the time the light goes of.

To explain:
Off - Well that's clear
On - Aditional the light can be dimt.
Auto: Pir sensor > Light goes to certain level > wait time > light goes to lower level > wait time > light goes off.

And to make this even more complicated, the light also has some color settings (only white)

This is the dump:
{
    "name": "Spot garage",
    "id": "bf8d395f0b724b5d0ersua",
    "key": "Deleted",
    "mac": "d4:a6:51:29:87:87",
    "category": "gyd",
    "product_name": "Smart Floodlight",
    "product_id": "p34tkhljhjgfr5vl",
    "biz_type": 0,
    "model": "Meka",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1541056239985fDGjj/5eb5b06866f946a91387acd6522e0578.png",
    "uuid": "0f131f6d2afc3629"
  },

Functions of device: bf8d395f0b724b5d0ersua
 {
  "result": {
    "category": "gyd",
    "functions": [
      {
        "code": "switch_led",
        "desc": "switch led",
        "name": "switch led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "desc": "work mode",
        "name": "work mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\"]}"
      },
      {
        "code": "bright_value",
        "desc": "bright value",
        "name": "bright value",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value",
        "desc": "temp value",
        "name": "temp value",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_data",
        "desc": "control data",
        "name": "control data",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "device_mode",
        "desc": "device mode",
        "name": "device mode",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "cds",
        "desc": "cds",
        "name": "cds",
        "type": "Enum",
        "values": "{\"range\":[\"2000lux\",\"300lux\",\"50lux\",\"10lux\",\"5lux\",\"now\"]}"
      },
      {
        "code": "pir_sensitivity",
        "desc": "pir sensitivity",
        "name": "pir sensitivity",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "pir_delay",
        "desc": "pir delay",
        "name": "pir delay",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":5,\"max\":3600,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_pir",
        "desc": "switch pir",
        "name": "switch pir",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "standby_time",
        "desc": "standby time",
        "name": "standby time",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":1,\"max\":480,\"scale\":0,\"step\":1}"
      },
      {
        "code": "standby_bright",
        "desc": "standby bright",
        "name": "standby bright",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1675799006203,
  "tid": "b048ac23a71f11eda120e66c285aff6b"
}

Properties of device: bf8d395f0b724b5d0ersua
 {
  "result": {
    "category": "gyd",
    "functions": [
      {
        "code": "switch_led",
        "desc": "{}",
        "name": "\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "desc": "{\"range\":[\"white\",\"colour\"]}",
        "name": "\u6a21\u5f0f",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\"]}"
      },
      {
        "code": "bright_value",
        "desc": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}",
        "name": "\u4eae\u5ea6\u503c",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value",
        "desc": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}",
        "name": "\u51b7\u6696\u503c",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_data",
        "desc": "{\"maxlen\":255}",
        "name": "\u8c03\u8282",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "device_mode",
        "desc": "{\"range\":[\"auto\",\"manual\"]}",
        "name": "\u8bbe\u5907\u6a21\u5f0f",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "cds",
        "desc": "{\"range\":[\"2000lux\",\"300lux\",\"50lux\",\"10lux\",\"5lux\",\"now\"]}",
        "name": "\u5149\u654f\u53c2\u6570\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"2000lux\",\"300lux\",\"50lux\",\"10lux\",\"5lux\",\"now\"]}"
      },
      {
        "code": "pir_sensitivity",
        "desc": "{\"range\":[\"low\",\"middle\",\"high\"]}",
        "name": "pir\u7075\u654f\u5ea6",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "pir_delay",
        "desc": "{\"unit\":\"s\",\"min\":5,\"max\":3600,\"scale\":0,\"step\":1}",
        "name": "\u611f\u5e94\u5ef6\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":5,\"max\":3600,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_pir",
        "desc": "{}",
        "name": "\u611f\u5e94\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "standby_time",
        "desc": "{\"unit\":\"min\",\"min\":1,\"max\":480,\"scale\":0,\"step\":1}",
        "name": "\u534a\u4eae\u5ef6\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":1,\"max\":480,\"scale\":0,\"step\":1}"
      },
      {
        "code": "standby_bright",
        "desc": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}",
        "name": "\u534a\u4eae\u4eae\u5ea6\u503c",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "name": "\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "name": "\u6a21\u5f0f",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\"]}"
      },
      {
        "code": "bright_value",
        "name": "\u4eae\u5ea6\u503c",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value",
        "name": "\u51b7\u6696\u503c",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "device_mode",
        "name": "\u8bbe\u5907\u6a21\u5f0f",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "pir_state",
        "name": "\u4eba\u4f53\u611f\u5e94\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"pir\",\"none\"]}"
      },
      {
        "code": "cds",
        "name": "\u5149\u654f\u53c2\u6570\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"2000lux\",\"300lux\",\"50lux\",\"10lux\",\"5lux\",\"now\"]}"
      },
      {
        "code": "pir_sensitivity",
        "name": "pir\u7075\u654f\u5ea6",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "pir_delay",
        "name": "\u611f\u5e94\u5ef6\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":5,\"max\":3600,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_pir",
        "name": "\u611f\u5e94\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "pir_resume_countdown",
        "name": "\u611f\u5e94\u6062\u590d\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":480,\"scale\":0,\"step\":1}"
      },
      {
        "code": "standby_time",
        "name": "\u534a\u4eae\u5ef6\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":1,\"max\":480,\"scale\":0,\"step\":1}"
      },
      {
        "code": "standby_bright",
        "name": "\u534a\u4eae\u4eae\u5ea6\u503c",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1675799006409,
  "tid": "b068774fa71f11ed9a310aeeb3bc8fba"
}

Status of device: bf8d395f0b724b5d0ersua
 {
  "result": [
    {
      "code": "switch_led",
      "value": false
    },
    {
      "code": "work_mode",
      "value": "white"
    },
    {
      "code": "bright_value",
      "value": 100
    },
    {
      "code": "temp_value",
      "value": 604
    },
    {
      "code": "device_mode",
      "value": "auto"
    },
    {
      "code": "pir_state",
      "value": "none"
    },
    {
      "code": "cds",
      "value": "10lux"
    },
    {
      "code": "pir_sensitivity",
      "value": "low"
    },
    {
      "code": "pir_delay",
      "value": 120
    },
    {
      "code": "switch_pir",
      "value": true
    },
    {
      "code": "pir_resume_countdown",
      "value": 5
    },
    {
      "code": "standby_time",
      "value": 2
    },
    {
      "code": "standby_bright",
      "value": 100
    }
  ],
  "success": true,
  "t": 1675799006619,
  "tid": "b088460aa71f11ed9a310aeeb3bc8fba"
}

**Comment by koningdde** [comment]
Here are some pictures from the tuya app.

![IMG_1479](https://user-images.githubusercontent.com/12693756/217355685-6b87a2a9-df59-4aa4-bddd-9a7af84812a6.PNG)
![IMG_1480](https://user-images.githubusercontent.com/12693756/217355688-af2c9ff5-bb9a-473e-96a5-de2978f2c46e.PNG)

**Comment by Xenomes** [comment]
Hi,
Added to Develop version 1.4.1, keep in mind that the plugin is pulling data for Tuya so a pir_state change can take up to 60 sec to register in Domoticz.

**Comment by koningdde** [comment]
Thank you for the work on this, it works fine accept for the level, the setting 0 - 100% in domoticz results in 0 tot 10% for the light.

**Comment by Xenomes** [comment]
I will see if i can correct that!

**Comment by Xenomes** [comment]
Fixed in the Develop (no version change)
