### ISSUE TITLE
catch expired subscription

### ISSUE THREAD

**Issue by wvries** [Xenomes/Domoticz-TinyTUYA-Plugin#20]
When the subscription of the IOT API is expired, the plugin stops working with many errors (with onHeartbeat errors).

Expected behaviour:
The plugin to stop with an error code in the Domoticz log when the subscription has ended, otherwise continue to function as usual.

Solution:
Catch expiration of the subscription before trying to login and proceed.

<label>Enhancement

**Comment by Xenomes** [comment]
There is a detection, but is not triggered. I can not test this scenario because my tuya subscription is the old one that not expires.
I now included more tuya readouts to trigger the message.

**Comment by Xenomes** [comment]
Added a better detection.
