### ISSUE TITLE
Add WIFIDS10WT smoke detector

### ISSUE THREAD

**Issue by rleunk** [Xenomes/Domoticz-TinyTUYA-Plugin#21]
Hello, is it possible to add the WIFIDS10WT smoke detector, or is there not enough info that the device sends,  hope this is the right dump info:

  {
    "name": "Rookmelder overloop",
    "id": "72832224d8bfc056c82b",
    "key": "Deleted",
    "mac": "d8:bf:c0:56:c8:2b",
    "category": "qt",
    "product_name": "Smoke Detector",
    "product_id": "xwwcvhmbotekh5ye",
    "biz_type": 0,
    "model": "WIFIDS10WT",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/154886265446d512gq47i_0.png",
    "uuid": "72832224d8bfc056c82b"
  },

Functions of device: 72832224d8bfc056c82b
{
  "result": {
    "category": "qt",
    "functions": []
  },
  "success": true,
  "t": 1676402975173,
  "tid": "e9d47241ac9d11ed954a4e3668f00a74"
}
Properties of device: 72832224d8bfc056c82b
{
  "result": {
    "category": "qt"
  },
  "success": true,
  "t": 1676402975269,
  "tid": "e9e621c0ac9d11ed8a3392fe1232b0cc"
}
Status of device: 72832224d8bfc056c82b
{
  "result": [],
  "success": true,
  "t": 1676402975369,
  "tid": "e9f5e193ac9d11ed838e2a0aa76353ad"
}

**Comment by Xenomes** [comment]
The dump is correct but the "result": [], is empty.
Can you change the Tuya setting https://github.com/jasonacox/tinytuya/issues/280#issuecomment-1427267620
and make a new dump?

**Comment by rleunk** [comment]
Hallo,

 

Misschien niet helemaal de juiste weg via de mail, maar heb stap 1-5 gedaan, stap 6 is met niet helemaal duidelijk of ik daar iets mee moet?

 

Top voor je snelle actie / reactie trouwens!

 

m.vr.gr.

R.Leunk

 

Van: Xenomes ***@***.***> 
Verzonden: dinsdag 14 februari 2023 22:26
Aan: Xenomes/Domoticz-TinyTUYA-Plugin ***@***.***>
CC: rleunk ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Xenomes/Domoticz-TinyTUYA-Plugin] Add WIFIDS10WT smoke detector (Issue #21)

 

The dump is correct but the "result": [], is empty.
Can you change the Tuya setting jasonacox/tinytuya#280 (comment) <https://github.com/jasonacox/tinytuya/issues/280#issuecomment-1427267620> 
and make a new dump?

**Comment by rleunk** [comment]
Thnx will do a new dump tomorrow, already did step 1-5, not clear what to do with step 6?

**Comment by rleunk** [comment]
Made a new dump today, and there is some more info, hope this is what you are looking for:

  {
    "name": "Rookmelder overloop",
    "id": "72832224d8bfc056c82b",
    "key": "Deleted",
    "mac": "d8:bf:c0:56:c8:2b",
    "category": "qt",
    "product_name": "Smoke Detector",
    "product_id": "xwwcvhmbotekh5ye",
    "biz_type": 0,
    "model": "WIFIDS10WT",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/154886265446d512gq47i_0.png",
    "uuid": "72832224d8bfc056c82b"
  },

Functions of device: 72832224d8bfc056c82b
{
  "result": {
    "category": "qt",
    "functions": []
  },
  "success": true,
  "t": 1676482683481,
  "tid": "7fb1726dad5711ed954a4e3668f00a74"
}
Properties of device: 72832224d8bfc056c82b
{
  "result": {
    "category": "qt",
    "status": [
      {
        "code": "control",
        "name": "\u53d7\u63a7\u4fe1\u606f",
        "type": "Enum",
        "values": "{\"range\":[\"0x03\",\"0x04\"]}"
      },
      {
        "code": "signal_quality",
        "name": "\u4fe1\u53f7\u8d28\u91cf",
        "type": "Enum",
        "values": "{\"range\":[\"0x00\",\"0x01\",\"0x02\",\"0x03\",\"0x04\"]}"
      },
      {
        "code": "battery",
        "name": "\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":1,\"step\":1}"
      },
      {
        "code": "PIR",
        "name": "\u5de5\u4f5c\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      }
    ]
  },
  "success": true,
  "t": 1676482683581,
  "tid": "7fc18fa7ad5711ed838e2a0aa76353ad"
}
Status of device: 72832224d8bfc056c82b
{
  "result": [
    {
      "code": "control",
      "value": "0x03"
    },
    {
      "code": "signal_quality",
      "value": "0x00"
    },
    {
      "code": "battery",
      "value": 83
    },
    {
      "code": "PIR",
      "value": "0"
    }
  ],
  "success": true,
  "t": 1676482683681,
  "tid": "7fcf7d32ad5711ed8a3392fe1232b0cc"
}

**Comment by Xenomes** [comment]
OK we got more data, but I don't know if it is useful.
Can you match this with a function in the app?
"code": "PIR",
"values": "{"range":["0","1","2","3","4"]}"

**Comment by rleunk** [comment]
In the app there is a tab "Meldingen" in there are 4 swtitch buttons "Smoke alarm" - "Mute"  - "Product failure"  - "TEST" could that have something to do with the functions?

**Comment by Xenomes** [comment]
I don't know, but it looks like it. I got 5 options, i could make a test.

**Comment by rleunk** [comment]
Thnx in advance
