### ISSUE TITLE
Please, can you add door contact "Aubess"

### ISSUE THREAD

**Issue by stefg73** [Xenomes/Domoticz-TinyTUYA-Plugin#22]
Hello, here is the dump.json of the device 👍 
Functions of device: bf2a5ce68a248166a5zu0r
{
  "result": {
    "category": "mcs",
    "functions": []
  },
  "success": true,
  "t": 1676471485213,
  "tid": "6d024639ad3d11ed838e2a0aa76353ad"
}
Properties of device: bf2a5ce68a248166a5zu0r
{
  "result": {
    "category": "mcs",
    "status": [
      {
        "code": "doorcontact_state",
        "name": "\u95e8\u78c1\u72b6\u6001",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_percentage",
        "name": "\u7535\u6c60\u7535\u91cf\u767e\u5206\u6bd4",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1676471485525,
  "tid": "6d3017bfad3d11ed8a3392fe1232b0cc"
}
Status of device: bf2a5ce68a248166a5zu0r
{
  "result": [
    {
      "code": "doorcontact_state",
      "value": true
    },
    {
      "code": "battery_percentage",
      "value": 40
    }
  ],
  "success": true,
  "t": 1676471485791,
  "tid": "6d5a7cedad3d11ed954a4e3668f00a74"
}

**Comment by tne7laa** [comment]
I bought also an Tuya Door Sensor (https://nl.aliexpress.com/item/1005004735476918.html)
It is not recognised by this plugin.
It looks that my sensors give the same debug. If needed I can give more info.
Hope these sensors will be implemented.

**Comment by tne7laa** [comment]
> I bought also an Tuya Door Sensor (https://nl.aliexpress.com/item/1005004735476918.html)
> It is not recognised by this plugin.
> It looks that my sensors give the same debug. If needed I can give more info.
> Hope these sensors will be implemented.

When searching in [https://github.com/tuya/tuya-home-assistant/wiki/Supported-Device-Category](url)
It looks like: mcs | Door Window Sensor

**Comment by Xenomes** [comment]
Hi @stefg73 and @tne7laa,
Door-sensor is added to Develop branch, can you both test it. if it works i can merge to the Master.
```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin/
git pull
git checkout Develop
git pull
sudo systemctl restart domoticz
```

Use git checkout Master to go back to the Master branch.

**Comment by stefg73** [comment]
Hi Xenomes,

test = OK for me ! with a domoticz device TXT : value = "On" when door is open since  about 1 minute and value Off when door is closed since about 1 minute

**Comment by tne7laa** [comment]
Hi, Not for me. 
OK:
- It is creating the device (switch)

NOK:
- Also I don't see the battery percentage (important to see of batteries have to be replaced). It is a property. Like to see it as device with percentage.
- Can you change it to Switchtype=11 (Door contact)? At this time it is shown as Switch.

I was looking into to program myself but don't have enough knowledge. Had something like:
                if dev_type in ('contactsensor'):
                    Domoticz.Log('Create device Door/Window contact Sensor')
                    if createDevice(dev['id'], 1) and searchCode('doorcontact_state', ResultValue):
                        Domoticz.Unit(Name=dev['name'] + ' (Status)', DeviceID=dev['id'], Unit=1, Type=244, Subtype=73, Switchtype=11, Image=16, Used=0).Create()
                    if createDevice(dev['id'], 2) and searchCode('battery_percentage', ResultValue):
                        Domoticz.Unit(Name=dev['name'] + ' (Battery percentage)', DeviceID=dev['id'], Unit=2, Type=243, Subtype=6, Used=0).Create()

But I'm very happy that you wil implement!

**Comment by tne7laa** [comment]
After testing again to open close it logs finally. I Maybe I was too fast with open/close. So first bullet is fine.

**Comment by stefg73** [comment]
For me no switch device created, only TXT device with vzalue "On" and "Off" respectively when door is open and closed (after polling time)
Domoticz version : stable 2022.2

**Comment by Xenomes** [comment]
> For me no switch device created, only TXT device with vzalue "On" and "Off" respectively when door is open and closed (after polling time) Domoticz version : stable 2022.2

O sorry forgot to mention, you have to delete the old txt device, so a new device can be created.

**Comment by tne7laa** [comment]
> For me no switch device created, only TXT device with vzalue "On" and "Off" respectively when door is open and closed (after polling time)
> Domoticz version : stable 2022.2

I deleted the previous generated devices before getting de dev branche and restarted domoticz. New devices where created. Don’t know if this helps or is the case.

**Comment by Xenomes** [comment]
> Can you change it to Switchtype=11 (Door contact)? At this time it is shown as Switch.

I can do that, there was a reason that i changed ti to a switch.

**Comment by stefg73** [comment]
That's it ! It works, new switch device created and state change are ok

Like tne7laa said : it would be great to have the battery percentage of this kind of device

**Comment by Xenomes** [comment]
> That's it ! It works, new switch device created and state change are ok
>
Great that it works

> Like tne7laa said : it would be great to have the battery percentage of this kind of device
>
battery was implanted but there was a third way of presenting a battery status.

The new Develop device is changed to door contact and has battery status.
You got to remove the device to get the new door contact.

**Comment by tne7laa** [comment]
It is working! 
![Sensors](https://user-images.githubusercontent.com/805474/219757660-ba573d8c-d7b7-4ec1-b996-d570a17e70ac.jpg)

Also battery status is showing. Only not as device itself like this:
![OtherBatteryPercentage](https://user-images.githubusercontent.com/805474/219757823-24b2b49e-ee3a-4ebe-94e1-4d6619e1af07.jpg)
And then under tab Other ("Overige" in dutch):
![Batterysensor](https://user-images.githubusercontent.com/805474/219758556-826554e5-953e-4505-8fc3-f560a9dcab07.jpg)

Maybe as you said that there is another way to present. 

How can I make something like blockly to look at percentage and make message?

**Comment by stefg73** [comment]
hi again, it works now with battery status, usable with json to update an "General,Percentage" device.

But, when the door open and close a few seconds later = No change in Domoticz. No way to get an history of device state from tuya ?

**Comment by tne7laa** [comment]
> hi again, it works now with battery status, **usable with json to update an "General,Percentage" device.**


You made an extra device with json? How did you do this?

**Comment by Xenomes** [comment]
> But, when the door open and close a few seconds later = No change in Domoticz. No way to get an history of device state from tuya ?

That is a issue, the plugin pull the status once a minute, so if a open and close is in that minute then for Domoticz nothing changed.

**Comment by Xenomes** [comment]
> It is working! !
> 
> Also battery status is showing. Only not as device itself like this
> 
> Maybe as you said that there is another way to present.
> 
> How can I make something like blockly to look at percentage and make message?



With dzvents you can readout the battery status.
```
    domoticz.devices().forEach(function(device)
        if (device.batteryLevel < 20) then
        -- do something
        end
    end)
```

**Comment by Xenomes** [comment]
If you set the Battery Low Level: in settings the you got a message if the battery is lower the the threshold.

**Comment by tne7laa** [comment]
> If you set the Battery Low Level: in settings the you got a message if the battery is lower the the threshold.

Ok, thanks. Like @stefg73 said nog logs will come if contact is short changed. I think because de device first has to connect to internet to the Tuya cloud and then Domoticz has to get status. Like most Tuya via cloud is not as responsive.
Maybe an Zwave contact device (if exists) is better/faster because it connects directly to Zwave-stick and raspberry pi. But this is speculation af course.
Maybe also there is an option like Local Tuya. This connects directly trough your local network and not cloud.

The change/add works fine by me. Only thing I have to look into is battery. Maybe the low battery message in settings is enough otherwise I have to add it somehow to dashboard.

**Comment by Xenomes** [comment]
Yes protocols like Zwave and Zigbee connect to Domoticz are very responsive, the better choice for that kind function.
Tinytuya is supporting Local Tuya but not implanted in the plugin yet. Tinytuya is also developing a server i don't know yet what it cloud do. On https://github.com/jasonacox/tinytuya there are script when modified you can see if you device put out the desired  locally info.

**Comment by stefg73** [comment]
WOW ! the local tinytuya seems to be very promising. No chance to adapt your plugin with this local tinytuya server ?

**Comment by Xenomes** [comment]
Develop merge to Master. Local tinytuya server needs more research.
