### ISSUE TITLE
Add Smart IR sender / receiver & Airco

### ISSUE THREAD

**Issue by wvries** [Xenomes/Domoticz-TinyTUYA-Plugin#23]
Hi,

Can you please add the Smart IR receiver and the Airco unit to the code please ?
Please bear in mind that the Airco is a unit "managed" by the Smart IR sender, so there can be many different type or airco's.
Just to keep in mind that the name given to this might change for others (this airco is a HeatSun).

[Debug.json.txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/10768597/Debug.json.txt)

Thanks in advance for the great work you are doing on this plugin.

**Comment by Xenomes** [comment]
Hi Wilbert,
Can you send me a email yours at your profile is not working.
Thnx!

**Comment by wvries** [comment]
Sorry, email address changed. should work now.

**Comment by K1aasH** [comment]
Hai WVries,

I also have the Smart IR sensor (from Ali) and it works great with this plugin (the temparature and huminity). Every IR code is different to the hardware wich can be an TV, DVD, Airco or something else. I think you can not relay to this plugin to get that worked. I don't think Xenomes can fix that for you.

**Comment by wvries** [comment]
Hi KlaasHI agree, in fact the Smart IR does not do anything active in Tuya, except act as a relay for the commands of the "slave" device. The IR devices are nothing more than a list of functions with its IR code.This is being send through the Smart IR.Solution is that either the plugin will be able to add all the IR devices (IR code lists) or a way to use the plugin as an intermediate which will accapt IR codes from outside of the plugin and relays then through tbe SmartIR.But that is comming close to building an API in the plugin.. which is taking it to anither level :-)Met vriendelijke groet,saludos cordiales,With kind regards,Wilbert de Vries

**Comment by Xenomes** [comment]
At the moment, I am investigating whether we can include basic functions such as power on and off, and setting the temperature.

**Comment by Xenomes** [comment]
HI, i have found is issue with the previous test. Can someone checkout IR-Air i have made a little improved.

**Comment by enpepet** [comment]
After some tests i managed it to work.
Testing at Tuya IOT Platform worked with your commands but it uses a distint URI without 'iot-03'
This part of uri is defined at tuya.sendcommand as a default value for argument 'uri'.

Then i have done next change at yout code and it works. The only change is URI.

Note: I think there can be a better place in code for this config. This is only a test.

```
def SendCommandCloud(ID, CommandName, Status):
......
      uri='iot-03/devices/'
      if 'PowerOff' in CommandName or 'PowerOn' in CommandName:
          uri='devices/'
      if testData != True:
          tuya.sendcommand(ID, {'commands': [{'code': actual_function_name, 'value': actual_status}]}, uri)
......
```

**Comment by enpepet** [comment]
I also prepared an infrared_tv command set

```
Properties of device: bfa88bdeviceeb9642fozb
{
  "result": {
    "category": "infrared_tv",
    "functions": [
      {
        "code": "-/--",
        "desc": "-/--",
        "name": "-/--",
        "type": "STRING",
        "values": "-/--"
      },
      {
        "code": "0",
        "desc": "0",
        "name": "0",
        "type": "STRING",
        "values": "0"
      },
      {
        "code": "1",
        "desc": "1",
        "name": "1",
        "type": "STRING",
        "values": "1"
      },
      {
        "code": "2",
        "desc": "2",
        "name": "2",
        "type": "STRING",
        "values": "2"
      },
      {
        "code": "3",
        "desc": "3",
        "name": "3",
        "type": "STRING",
        "values": "3"
      },
      {
        "code": "4",
        "desc": "4",
        "name": "4",
        "type": "STRING",
        "values": "4"
      },
      {
        "code": "5",
        "desc": "5",
        "name": "5",
        "type": "STRING",
        "values": "5"
      },
      {
        "code": "6",
        "desc": "6",
        "name": "6",
        "type": "STRING",
        "values": "6"
      },
      {
        "code": "7",
        "desc": "7",
        "name": "7",
        "type": "STRING",
        "values": "7"
      },
      {
        "code": "8",
        "desc": "8",
        "name": "8",
        "type": "STRING",
        "values": "8"
      },
      {
        "code": "9",
        "desc": "9",
        "name": "9",
        "type": "STRING",
        "values": "9"
      },
      {
        "code": "Back",
        "desc": "Back",
        "name": "Back",
        "type": "STRING",
        "values": "Back"
      },
      {
        "code": "C",
        "desc": "{\"min\":1,\"max\":999,\"scale\":0,\"step\":1,\"type\":\"Integer\"}",
        "name": "channel",
        "type": "ENUM",
        "values": "{\"min\":1,\"max\":999,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      },
      {
        "code": "Channel+",
        "desc": "Channel+",
        "name": "Channel+",
        "type": "STRING",
        "values": "Channel+"
      },
      {
        "code": "Channel-",
        "desc": "Channel-",
        "name": "Channel-",
        "type": "STRING",
        "values": "Channel-"
      },
      {
        "code": "Down",
        "desc": "Down",
        "name": "Down",
        "type": "STRING",
        "values": "Down"
      },
      {
        "code": "Home",
        "desc": "Home",
        "name": "Home",
        "type": "STRING",
        "values": "Home"
      },
      {
        "code": "Left",
        "desc": "Left",
        "name": "Left",
        "type": "STRING",
        "values": "Left"
      },
      {
        "code": "Menu",
        "desc": "Menu",
        "name": "Menu",
        "type": "STRING",
        "values": "Menu"
      },
      {
        "code": "OK",
        "desc": "OK",
        "name": "OK",
        "type": "STRING",
        "values": "OK"
      },
      {
        "code": "Power",
        "desc": "Power",
        "name": "Power",
        "type": "STRING",
        "values": "Power"
      },
      {
        "code": "Right",
        "desc": "Right",
        "name": "Right",
        "type": "STRING",
        "values": "Right"
      },
      {
        "code": "Up",
        "desc": "Up",
        "name": "Up",
        "type": "STRING",
        "values": "Up"
      },
      {
        "code": "Volume+",
        "desc": "Volume+",
        "name": "Volume+",
        "type": "STRING",
        "values": "Volume+"
      },
      {
        "code": "Volume-",
        "desc": "Volume-",
        "name": "Volume-",
        "type": "STRING",
        "values": "Volume-"
      }
    ]
  },
  "success": true,
  "t": 1687895344031,
  "tid": "ab78c4b01....0d793901"
}
Status of device: bfa88bdeviceeb9642fozb
{
  "result": [],
  "success": true,
  "t": 1687895344304,
  "tid": "aba3395....57e9038830"
}
```

**Comment by Xenomes** [comment]
Hi Thanks for the update. Where did you get the info about uri='iot-03/devices/' or uri='devices/' information? Tested uri='devices/' on my lamp and this works. I have added the code in the IR-Air branch still only for the air conditioner.

**Comment by enpepet** [comment]
> Hi Thanks for the update. Where did you get the info about uri='iot-03/devices/' or uri='devices/' information? Tested uri='devices/' on my lamp and this works. I have added the code in the IR-Air branch still only for the air conditioner.

Checking Chrome Explorer Network tab when I was testing at Tuya Dev website where it is possible to test devices commands.
https://eu.iot.tuya.com/cloud/device/detail/

Also at tintuya code sendcommand function.


And from this doc:

https://developer.tuya.com/en/docs/cloud/device-control?id=K95zu01ksols7

https://developer.tuya.com/en/docs/cloud/e2512fb901?id=Kag2yag3tiqn5

**Comment by Xenomes** [comment]
Where you able to test the IR-Air branch?

**Comment by enpepet** [comment]
> Where you able to test the IR-Air branch?

It works for me.

**Comment by Xenomes** [comment]
OK that is good the hear, So Airco is fixed. I go to try to add the remote function 😅

**Comment by Xenomes** [comment]
Remote is not so easy, I will not fix this at this time.
