### ISSUE TITLE
Help with Temp sensor

### ISSUE THREAD

**Issue by stefg73** [Xenomes/Domoticz-TinyTUYA-Plugin#24]
I don't understand what happened : this temp sensor worked fine but till 02:45 today (Europe-GMT+1) it fail (device txt created in domoticz that said to do the debug-discovery process.

Here's the dump of this device : 

Functions of device: bf7db29f562d366010xacg
{
  "result": {
    "category": "wsdcg",
    "functions": [
      {
        "code": "temp_unit_convert",
        "desc": "temp unit convert",
        "name": "temp unit convert",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "maxtemp_set",
        "desc": "maxtemp set",
        "name": "maxtemp set",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-400,\"max\":1200,\"scale\":1,\"step\":1}"
      },
      {
        "code": "minitemp_set",
        "desc": "minitemp set",
        "name": "minitemp set",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-400,\"max\":1200,\"scale\":1,\"step\":1}"
      },
      {
        "code": "temp_calibration",
        "desc": "temp calibration",
        "name": "temp calibration",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-100,\"max\":100,\"scale\":1,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1676786549215,
  "tid": "fdc52703b01a11ed8a3392fe1232b0cc"
}
Properties of device: bf7db29f562d366010xacg
{
  "result": {
    "category": "wsdcg",
    "functions": [
      {
        "code": "temp_unit_convert",
        "desc": "{\"range\":[\"c\",\"f\"]}",
        "name": "\u6e29\u6807\u5207\u6362",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "maxtemp_set",
        "desc": "{\"unit\":\"\u2103\",\"min\":-400,\"max\":1200,\"scale\":1,\"step\":1}",
        "name": "\u6e29\u5ea6\u4e0a\u9650",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-400,\"max\":1200,\"scale\":1,\"step\":1}"
      },
      {
        "code": "minitemp_set",
        "desc": "{\"unit\":\"\u2103\",\"min\":-400,\"max\":1200,\"scale\":1,\"step\":1}",
        "name": "\u6e29\u5ea6\u4e0b\u9650",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-400,\"max\":1200,\"scale\":1,\"step\":1}"
      },
      {
        "code": "temp_calibration",
        "desc": "{\"unit\":\"\u2103\",\"min\":-100,\"max\":100,\"scale\":1,\"step\":1}",
        "name": "\u6e29\u5ea6\u6821\u51c6",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-100,\"max\":100,\"scale\":1,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "temp_current",
        "name": "\u6e29\u5ea6",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-400,\"max\":1200,\"scale\":1,\"step\":1}"
      },
      {
        "code": "temp_unit_convert",
        "name": "\u6e29\u6807\u5207\u6362",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "maxtemp_set",
        "name": "\u6e29\u5ea6\u4e0a\u9650",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-400,\"max\":1200,\"scale\":1,\"step\":1}"
      },
      {
        "code": "minitemp_set",
        "name": "\u6e29\u5ea6\u4e0b\u9650",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-400,\"max\":1200,\"scale\":1,\"step\":1}"
      },
      {
        "code": "temp_alarm",
        "name": "\u6e29\u5ea6\u62a5\u8b66",
        "type": "Enum",
        "values": "{\"range\":[\"loweralarm\",\"upperalarm\",\"cancel\"]}"
      },
      {
        "code": "temp_calibration",
        "name": "\u6e29\u5ea6\u6821\u51c6",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-100,\"max\":100,\"scale\":1,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1676786549510,
  "tid": "fdf79d39b01a11ed8a3392fe1232b0cc"
}
Status of device: bf7db29f562d366010xacg
{
  "result": [
    {
      "code": "temp_current",
      "value": 77
    },
    {
      "code": "temp_unit_convert",
      "value": "c"
    },
    {
      "code": "maxtemp_set",
      "value": 1200
    },
    {
      "code": "minitemp_set",
      "value": -400
    },
    {
      "code": "temp_alarm",
      "value": "cancel"
    },
    {
      "code": "temp_calibration",
      "value": 0
    }
  ],
  "success": true,
  "t": 1676786549804,
  "tid": "fe23a687b01a11ed8a3392fe1232b0cc"
}

**Comment by Xenomes** [comment]
It look like the data has changed that is coming back from Tuya,

I check in the code for "va_temperature" but in your data is "temp_current" present.

**Comment by Xenomes** [comment]
I have added to the Develop branch can you test it?

**Comment by stefg73** [comment]
Tested Ok, but can you tell me if we have to switch to "DP instruction" or "Standard instruction"  in device iot.tuya ?

**Comment by Xenomes** [comment]
On Tinytuya the DP instruction is advised.

**Comment by stefg73** [comment]
Ok but for this device in standard mode = "va_temperature" and in DP mode = "temp_current", so you check for "standard code" instead of DP mode, no ?

**Comment by Xenomes** [comment]
The plugin is hanging om Tinytuya 'DP instruction' is the way.

**Comment by stefg73** [comment]
ok thanks for information.

When do you think to put Develop branch in Master branch ?

**Comment by Xenomes** [comment]
Doing some last tests. Somewhere this week..

**Comment by stefg73** [comment]
Hello, Be carefull about this : i have to change some things in plugin.py and it works fine for temp sensor who use humidity_value and temp_current :  552-565 : if dev_type in ('temperaturehumiditysensor', 'smartir'):                    Domoticz.Log('Create device T&H Sensor')                    if createDevice(dev['id'], 1) and searchCode('va_temperature', ResultValue):                        Domoticz.Unit(Name=dev['name'] + ' (Temperature)', DeviceID=dev['id'], Unit=1, Type=80, Subtype=5, Used=0).Create()                    if createDevice(dev['id'], 1) and searchCode('temp_current', ResultValue):                        Domoticz.Unit(Name=dev['name'] + ' (Temperature)', DeviceID=dev['id'], Unit=1, Type=80, Subtype=5, Used=1).Create()                    if createDevice(dev['id'], 2) and searchCode('va_humidity', ResultValue):                        Domoticz.Unit(Name=dev['name'] + ' (Humidity)', DeviceID=dev['id'], Unit=2, Type=81, Subtype=1, Used=0).Create()                    if createDevice(dev['id'], 2) and searchCode('humidity_value', ResultValue):                        Domoticz.Unit(Name=dev['name'] + ' (Humidity)', DeviceID=dev['id'], Unit=2, Type=81, Subtype=1, Used=0).Create()                    if createDevice(dev['id'], 3) and searchCode('va_temperature', ResultValue) and searchCode('va_humidity', ResultValue):                        Domoticz.Unit(Name=dev['name'] + ' (Temperature + Humidity)', DeviceID=dev['id'], Unit=3, Type=82, Subtype=5, Used=1).Create()                    if createDevice(dev['id'], 3) and searchCode('temp_current', ResultValue) and searchCode('humidity_value', ResultValue):                        Domoticz.Unit(Name=dev['name'] + ' (Temperature + Humidity)', DeviceID=dev['id'], Unit=3, Type=82, Subtype=5, Used=1).Create()  945-965 :if dev_type in ('temperaturehumiditysensor', 'smartir'):                        if searchCode('va_temperature', ResultValue):                            currenttemp = StatusDeviceTuya('va_temperature')                            if str(currenttemp) != str(Devices[dev['id']].Units[1].sValue):                                UpdateDevice(dev['id'], 1, currenttemp, 0, 0)                        if searchCode('temp_current', ResultValue):                            currenttemp = StatusDeviceTuya('temp_current')                            if str(currenttemp) != str(Devices[dev['id']].Units[1].sValue):                                UpdateDevice(dev['id'], 1, currenttemp, 0, 0)                        if  searchCode('va_humidity', ResultValue):                            currenthumi = StatusDeviceTuya('va_humidity')                            if str(currenthumi) != str(Devices[dev['id']].Units[2].nValue):                                UpdateDevice(dev['id'], 2, 0, currenthumi, 0)                        if  searchCode('humidity_value', ResultValue):                            currenthumi = StatusDeviceTuya('humidity_value')                            if str(currenthumi) != str(Devices[dev['id']].Units[2].nValue):                                UpdateDevice(dev['id'], 2, 0, currenthumi, 0)                        if searchCode('va_temperature', ResultValue) and searchCode('va_humidity', ResultValue):                            currentdomo = Devices[dev['id']].Units[3].sValue                        if searchCode('temp_current', ResultValue) and searchCode('humidity_value', ResultValue):                            currentdomo = Devices[dev['id']].Units[3].sValue    Envoyé à partir de Courrier pour Windows De : XenomesEnvoyé le :dimanche 19 février 2023 21:09À : Xenomes/Domoticz-TinyTUYA-PluginCc : stefg73; AuthorObjet :Re: [Xenomes/Domoticz-TinyTUYA-Plugin] Help with Temp sensor (Issue #24) Doing some last tests. Somewhere this week..—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Xenomes** [comment]
Your post was not easy to read...
You added va_humidity but in your json there was no va_humidity?!

**Comment by stefg73** [comment]
hello, i've sent by mail, it's perhaps more easy to read.

I've just add this 2 code "temp_current" and "humidity_value" in addition of "va_tempeture" and "va_humidity"

**Comment by Xenomes** [comment]
Added in the Develop Branch, can you test it?

**Comment by stefg73** [comment]
It's ok

**Comment by Xenomes** [comment]
Perfect!
