### ISSUE TITLE
Add LED Strip Controller

### ISSUE THREAD

**Issue by wvries** [Xenomes/Domoticz-TinyTUYA-Plugin#25]
Hi, 

Found another device in my pile of stuff :-)
LED Strip Controller (color LED strip)

[dump (LED Strip Controller).txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/10777500/dump.LED.Strip.Controller.txt)

Ik hoor het wel :-)

**Comment by Xenomes** [comment]
There was a bug in the light detection. fixed in the latest version of Develop (No version update).
