### ISSUE TITLE
Logging reduction

### ISSUE THREAD

**Issue by heggink** [Xenomes/Domoticz-TinyTUYA-Plugin#28]
At the moment, the plugin is pretty chatty with message slike
onheartbeat called
onheartbeat called skipped
Update devices in Domoticz
onHeartbeat called last run: 69.43911528587341

could these be moved to debug?

**Comment by Xenomes** [comment]
Not at the moment, until the development slows down.
You are free to replace the Domoticz.Log to Domoticz.Debug
