### ISSUE TITLE
Add water boiler with heatpump Ferroli

### ISSUE THREAD

**Issue by johosoft-be** [Xenomes/Domoticz-TinyTUYA-Plugin#29]
I am get the below fault message.

 No controls found for device: Boiler met geïntegreerde warmtepomp
2023-03-05 11:54:25.746 Threesixty: Update device value:44368835a4e57c90edbc Unit: 1 sValue: This device is not reconised, edit and run the debug_discovery with python from the tools directory and receate a issue report at https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/issues so the device can be added. nValue: 0 TimedOut=0 

List of devices: 
[
  {
    "name": "Boiler met ge\u00efntegreerde warmtepomp",
    "id": "44368835a4e57c90edbc",
    "key": "Deleted",
    "mac": "a4:e5:7c:90:ed:bc",
    "category": "rs",
    "product_name": "Water heater with integrated heat pump",
    "product_id": "ymvlwldw9f9alkee",
    "biz_type": 18,
    "model": "",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1559825824224fhsJk/101509780380fbaf3f2c248037818ff7.png",
    "uuid": "44368835a4e57c90edbc"
  },

Functions of device: 44368835a4e57c90edbc
{
  "result": {
    "category": "rs",
    "functions": [
      {
        "code": "switch",
        "desc": "switch",
        "name": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "desc": "temp set",
        "name": "temp set",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":38,\"max\":75,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "desc": "mode",
        "name": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"eco\"]}"
      }
    ]
  },
  "success": true,
  "t": 1678013790305,
  "tid": "627b9b1cbb4411edb7fdc2ad824e71c9"
}
Properties of device: 44368835a4e57c90edbc
{
  "result": {
    "category": "rs",
    "functions": [
      {
        "code": "switch",
        "desc": "{}",
        "name": "\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "desc": "{\"unit\":\"\u2103\",\"min\":38,\"max\":75,\"scale\":0,\"step\":1}",
        "name": "\u6e29\u5ea6\u8bbe\u7f6e",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":38,\"max\":75,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "desc": "{\"range\":[\"auto\",\"eco\"]}",
        "name": "\u6a21\u5f0f",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"eco\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "name": "\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "name": "\u6e29\u5ea6\u8bbe\u7f6e",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":38,\"max\":75,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "name": "\u5f53\u524d\u6e29\u5ea6",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-30,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "name": "\u6a21\u5f0f",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"eco\"]}"
      },
      {
        "code": "fault",
        "name": "\u6545\u969c\u544a\u8b66",
        "type": "bitmap",
        "values": "{\"label\":[\"sys_high_fault\",\"sys_low_fault\",\"flow_fault\",\"power_fault\",\"cooling_fault\",\"heating_fault\",\"temp_dif_fault\",\"in_temp_fault\",\"eff_temp_fault\",\"coil_temp_fault\",\"ret_temp_fault\",\"news_fault\",\"amb_temp_fault\",\"lack_water\",\"serious_fault\",\"sensor_fault\",\"motor_fault\"],\"maxlen\":16}"
      }
    ]
  },
  "success": true,
  "t": 1678013790580,
  "tid": "62995ea6bb4411ed9f7936041e250963"
}
Status of device: 44368835a4e57c90edbc
{
  "result": [
    {
      "code": "switch",
      "value": true
    },
    {
      "code": "temp_set",
      "value": 55
    },
    {
      "code": "temp_current",
      "value": 12
    },
    {
      "code": "mode",
      "value": "eco"
    },
    {
      "code": "fault",
      "value": 0
    }
  ],
  "success": true,
  "t": 1678013790964,
  "tid": "62c7bab3bb4411ed9f7936041e250963"
}

Is it possible to add this to TinyTuya?

**Comment by Xenomes** [comment]
The data looks promising! Will implant it this week.

**Comment by Xenomes** [comment]
Added in version 1.4.3
