### ISSUE TITLE
new device: PJ-ZGD01

### ISSUE THREAD

**Issue by frenchyyii** [Xenomes/Domoticz-TinyTUYA-Plugin#31]
This is a garage door opener with status
json is in your maibox
Thanx 
Eric

**Comment by Xenomes** [comment]
Thanks for reporting, can you give the ID from the device? I can't find PJ-ZGD01 in the json.

**Comment by frenchyyii** [comment]
All apologize....it was not the good dump.
name of the object is 350z
Hope it is ok now.
Have a good night
________________________________
De : Xenomes ***@***.***>
Envoyé : dimanche 12 mars 2023 19:12
À : Xenomes/Domoticz-TinyTUYA-Plugin ***@***.***>
Cc : frenchyyii ***@***.***>; Author ***@***.***>
Objet : Re: [Xenomes/Domoticz-TinyTUYA-Plugin] new device: PJ-ZGD01 (Issue #31)


Thanks for reporting, can you give the ID from the device? I can't find PJ-ZGD01 in the json.

**Comment by Xenomes** [comment]
Hi, The attachment didn't make it to github 😅

**Comment by frenchyyii** [comment]
I ll push it tomorrow with other devices (lights) that are recognised but keep in red with domoticz. Have a good evening.
Eric

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by frenchyyii** [comment]
Lights aere now working, so here is the dump with  PJ-ZGD01
`"name": "350 Z",
    "id": "bfd2806bd948e52b64kspf",
    "key": "Deleted",
    "mac": "a4:c1:38:3f:eb:8e:65:7c",
    "uuid": "a4c1383feb8e657c",
    "sn": "10009427300205",
    "category": "ckmkzq",
    "product_name": "\u8f66\u5e93\u95e8",
    "product_id": "nklqjk62",
    "biz_type": 18,
    "model": "PJ-ZGD01",
    "sub": true,
    "icon": "https://images.tuyaeu.com/smart/icon/bay16111967609110m8U/96d66f5a642adbdf64f04f71bfb14217.png",
    "node_id": "a4c1383feb8e657c"`

**Comment by frenchyyii** [comment]
Lights are now working, so here is the dump with PJ-ZGD01
"name": "350 Z", "id": "bfd2806bd948e52b64kspf", "key": "Deleted", "mac": "a4:c1:38:3f:eb:8e:65:7c", "uuid": "a4c1383feb8e657c", "sn": "10009427300205", "category": "ckmkzq", "product_name": "\u8f66\u5e93\u95e8", "product_id": "nklqjk62", "biz_type": 18, "model": "PJ-ZGD01", "sub": true, "icon":
 "https://images.tuyaeu.com/smart/icon/bay16111967609110m8U/96d66f5a642adbdf64f04f71bfb14217.png", "node_id": "a4c1383feb8e657c"
[dump.zip](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/10968663/dump.zip)

**Comment by Xenomes** [comment]
Hi i need also the functions and status of the device.


Met vriendelijke groet,

Xenomes

<https://aka.ms/AAb9ysg>
________________________________

**Comment by frenchyyii** [comment]
It is a garage door opener with status of the door, sheduler alarm etc..
Can you download the dump.zip in my precedent message ?
It refuses me to upload it directly as "dump.json"
If you can't download or read the zip file I can send it by email.
Have a good day. Eric

**Comment by Xenomes** [comment]
No, it is missing. Can you mail it to xenomes@outlook.com?

**Comment by frenchyyii** [comment]
[dump.zip](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/10968663/dump.zip)
link seemed to work sniff... I send it to your mailbox  ;)
Thanks
Eric

**Comment by Xenomes** [comment]
The garage door opener is added to the Develop branch, can you check it out? there are two state can you confirm which is the right one?

**Comment by Xenomes** [comment]
Added to the Master.

**Comment by frenchyyii** [comment]
Hi, just back home and could make tests. Everything seems ok with the garage door opener except I had to change the Alarm detector switch to an On/Off switch.
The state of the gate works fine too, everything is perfect thanks.

However I still do not understant why I can't send commands to some of my RGB lights (gamer 1, 2, 3, 4 and also jardin 1 and 2 in the dump). I do receive the infos back from the app but my commands do not work and  apply.

Have a good weekend.

Eric
________________________________
De : Xenomes ***@***.***>
Envoyé : mardi 14 mars 2023 21:43
À : Xenomes/Domoticz-TinyTUYA-Plugin ***@***.***>
Cc : frenchyyii ***@***.***>; Author ***@***.***>
Objet : Re: [Xenomes/Domoticz-TinyTUYA-Plugin] new device: PJ-ZGD01 (Issue #31)


The garage door opener is added to the Develop branch, can you check it out? there are two state can you confirm which is the right one?

**Comment by Xenomes** [comment]
> Everything seems ok with the garage door opener except I had to change the Alarm detector switch to an On/Off switch.

I will change it in the script. Perfect that all the rest works fine.

> However I still do not understant why I can't send commands to some of my RGB lights (gamer 1, 2, 3, 4 and also jardin 1 and 2 in the dump).

You are on the 1.4.7 version, there was a control change at the tuya side that is fixed now. Is there no error when sending a commando?

**Comment by frenchyyii** [comment]
Yes i switched to master branch when I saw you added the gate to the master one.
I see 1.4.7 in the plugin.py and juste made a gitt pull but it seems to be the last one. Should I switch again to dev ?

An no error sending commands, just the command does not apply.
I allready had the trouble and sometimes it worked... quite strange.

Eric
________________________________
De : Xenomes ***@***.***>
Envoyé : dimanche 2 avril 2023 08:16
À : Xenomes/Domoticz-TinyTUYA-Plugin ***@***.***>
Cc : frenchyyii ***@***.***>; Author ***@***.***>
Objet : Re: [Xenomes/Domoticz-TinyTUYA-Plugin] new device: PJ-ZGD01 (Issue #31)


Everything seems ok with the garage door opener except I had to change the Alarm detector switch to an On/Off switch.

I will change it in the script. Perfect that all the rest works fine.

However I still do not understant why I can't send commands to some of my RGB lights (gamer 1, 2, 3, 4 and also jardin 1 and 2 in the dump).

You are on the 1.4.7 version, there was a control change at the tuya side that is fixed now. Is there no error when sending a commando?

**Comment by Xenomes** [comment]
The master is on the same version a the develop.
Do you have a special network solution?
