### ISSUE TITLE
Voltage and current display problem (multiplier) Gosund SP111-A; Gosund SP211

### ISSUE THREAD

**Issue by tomatos-st** [Xenomes/Domoticz-TinyTUYA-Plugin#32]
I have a problem with the display of voltage and current (multiplier)
Some devices (Gosund SP111-A) display incorrect values of voltage 2226V instead of 222.6V and current 1020A instead of 0A.  Watts are also from outer space
Another device (Gosund SP211) gives the voltage correctly but the current in amperes 283A instead of mA (0.283A)
![Gosund SP111-A](https://user-images.githubusercontent.com/56383991/224573921-da35531f-0dd1-45fa-abde-1b79cebda365.jpg)

![Gosund SP211](https://user-images.githubusercontent.com/56383991/224573938-afc3e320-aecc-499a-b155-cc9e4664fce8.jpg)
Thanks

**Comment by Xenomes** [comment]
On what version are you? 
You create a dump.json by edit and run the debug_discovery.py from the tools directory and email it to me? Then i can check what is going wrong.

**Comment by tomatos-st** [comment]
the last one :)
![TinyTuya](https://user-images.githubusercontent.com/56383991/224814109-c27a2b80-f897-45e1-9fdf-fc7583cad6c7.jpg)

[dump.zip](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/10961269/dump.zip)

**Comment by Xenomes** [comment]
Nope 1.4.4 is the last one 😆 but 1.4.3 has the scale correction built in. I will look in to you dump file.
Edit:
I see the problem... 
"{\"min\":0,\"scale\":0,\"unit\":\"mA\",\"max\":30000,\"step\":1}"
the unit report in mA, so i can change the text of the device or detect mA and do scaling... 🤔

**Comment by tomatos-st** [comment]
OK.... I installed on Saturday... and downloaded version 1.4.3... 
And what...? update to 1.4.4 or wait for patches?   🤔

The problem occurs with Gosund sockets,
Similar Nous A1 sockets display the data correctly

**Comment by Xenomes** [comment]
You can update of course, the update is lights if yours work correctly then you can wait for the new update.

**Comment by Xenomes** [comment]
Can you change for example the 'Toster' in iot.tuya.com to DP Instruction.
https://eu.iot.tuya.com => Cloud => Your project => Devices => Find the device => change to DP Instruction
Hopefully it change the output.

**Comment by tomatos-st** [comment]
OK
I changed
![Tuya PD 1](https://user-images.githubusercontent.com/56383991/225117959-9513d016-e183-4a31-949c-16f5d34c7d77.jpg)
but in the device list I see:
![Tuya PD 2](https://user-images.githubusercontent.com/56383991/225118510-3c9ff2bc-34bb-4b90-8a34-b295d2fb14a7.jpg)
so it has to be ?
and what's next ?

**Comment by Xenomes** [comment]
OK good, what do the values in Domoticz?

**Comment by tomatos-st** [comment]
![T](https://user-images.githubusercontent.com/56383991/225232676-8f98c807-5f75-4129-b31a-600599930f5e.jpg)
The device's reporting date is strange...
each measurement has a different...

**Comment by Xenomes** [comment]
But the values are still in correct. I don't have a solution yet to fix or detect this deviation.

**Comment by tomatos-st** [comment]
I'll wait (I have no choice ;) maybe you'll come up with something.
The problem is only with the Gosound socket

**Comment by Xenomes** [comment]
Hi I have a solution build in version 1.4.7, if updated the old sub device will stop updating and a new one for mA is created.

**Comment by tomatos-st** [comment]
What about wrong voltage indication?
![tuya](https://user-images.githubusercontent.com/56383991/229627106-08d93d8e-f6fc-45ea-816a-697ebc6f55a7.jpg)
comma is missing, indication is 10 times too large
The problem continues only with the Gosound socket

**Comment by Xenomes** [comment]
Oops, the voltage I forgot. will check it!
Edit:
The returned data is wrong:
```
{
  "code": "cur_voltage",
  "name": "\u7535\u538b",
  "type": "Integer",
  "values": "{\"min\":0,\"unit\":\"V\",\"scale\":0,\"max\":2500,\"step\":1}"
}
```

With other power monitor sockets, the scale is 1 and that is the number the comma moves. This structure is used for all other values, so i don't know why this device data is divergent to the others. At the moment i have no idea to correct it in the code.

**Comment by Xenomes** [comment]
I had a idea, i compared a lot op Volt en Watt data and notice that the length of the max data is the same as with a device with scale 1 and not with scale 0, i made a bypass if scale = 0 and length of max 4 digest them also do division by 10. Can you check it out version 1.4.9

**Comment by tomatos-st** [comment]
Looks good ;)
![ty](https://user-images.githubusercontent.com/56383991/230200720-08b8f3bc-c191-4323-a69a-d0478f36aa85.jpg)
Just a weird version...
![tv](https://user-images.githubusercontent.com/56383991/230200906-b95239be-8a59-4bb9-90ed-8287878d718e.jpg)

**Comment by Xenomes** [comment]
Oops typo. Corrected 😅
Looks good!
