### ISSUE TITLE
Towel Warmer, only Switch on/off but not temp 

### ISSUE THREAD

**Issue by MikmakNL** [Xenomes/Domoticz-TinyTUYA-Plugin#33]
Hello, 

First, thank you for your great work!

I have add a towel warmer in the TUYA IOT and I will get the current temp to controll the floorheating.
In the dump file I can see that the current temp data is there but in Domoticz I have only: Type: Light/Switch, SubType: Switch

Do I something wrong?

![image](https://user-images.githubusercontent.com/128937177/227744554-4ed4488b-2f89-4fd2-b843-c4051d6ebac0.png)

[dump.json.txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/11070316/dump.json.txt)

Thank You!

**Comment by Xenomes** [comment]
Hi MikmakNL,
Thank for the dump, Tuya change the detection of set_temp to temp_set, made modification to work with both. Update to 1.4.5 then there will be two extra device. 
Xenomes
