### ISSUE TITLE
Tuya Thermostat type 16A-002HB

### ISSUE THREAD

**Issue by Fnasy** [Xenomes/Domoticz-TinyTUYA-Plugin#34]
Hello,
I am trying to connect this kind of thermostat to Domoticz.
The switches are well created (except "eco") and the other devices too. But the temperatures remain at 0.
I have attached the dump in which we can notice that the temperatures are a multiple of 0.5°. (5°=10, 20°=40, 15.5°=31,...Step by 0.5° and no decimals). This for the thermometers and for the temperature set point. It would therefore be necessary to convert in both directions. 
"upper_temp" is the local temperature.
"temp_set" is temperature set point

Is this feasible? This thermostat is sold under many different brands and TinyTuya is the first program that recognizes them with almost all parameters.
If this temperature problem is solved everything should work perfectly. (and I will finally be able to put the finishing touches to the management of self-consumption of my solar energy production, which is my final goal).
Many thanks in advance.

Thierry

[DumpJson.pdf](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/11138303/DumpJson.pdf)

**Comment by Xenomes** [comment]
Hi Thierry,
Thanks for the dump!
Device functions is added to the version 1.4.8

**Comment by Fnasy** [comment]
Hi, 
Wonderful, are you Rocketman ? I am impressed. 

Everything seems to work correctly. I'll make some more tests to be sure.
Thanks a lot for this.

Thierry

**Comment by Fnasy** [comment]
Hi,
After several days of testing everything is working fine and my heat pumps are under control. Again, thank you very much.
Small observation: if the setpoint temperature is greater or less than the limits, the update is not done. Therefore the thermostat and the values ​​in Domoticz no longer match. Not very important but good to know.

Regards

Thierry
