### ISSUE TITLE
Plugin locks the system

### ISSUE THREAD

**Issue by heggink** [Xenomes/Domoticz-TinyTUYA-Plugin#35]
Line 1659 in the plugin does a sleep(10) which will lock the event system. Also, line 1659 does an incorrect check which is always true locking the system any time zero devices are returned.
should check the check be while len(devs) == 0 and i < 4?
Then it will exit after 4 tries.

**Comment by Xenomes** [comment]
Thank you for reporting the issue! I haven't experienced Tuya timeouts that last for a long time. In my experience, it only takes one or two attempts at most before a successful connection is established. I have added your suggestion to the latest version.
