### ISSUE TITLE
Question, no issue ;-)

### ISSUE THREAD

**Issue by heggink** [Xenomes/Domoticz-TinyTUYA-Plugin#36]
Hey Xenomes,

I saw you forked tinytuya2mqtt. Since domoticz supports HA autodiscovery, what decided you to write a plugin instead of enhancing tinytuya2mqtt?

Thx!!

H

**Comment by Xenomes** [comment]
Hi Heggink,
At that moment, I started investigating TinyTuya2MQTT. I was hopeful to get it working, but the way to set it up was not user-friendly for non-coders, so I abandoned it and created a monster of a plugin. But there is hope - maybe the TinyTuya server will support MQTT. https://github.com/jasonacox/tinytuya/issues/255
