### ISSUE TITLE
This line code don't work for me

### ISSUE THREAD

**Issue by stefg73** [Xenomes/Domoticz-TinyTUYA-Plugin#37]
line 162 of plugin.py 1.4.9 : 
switch = 'switch_led' if searchCode('switch_led', FunctionProperties) else 'led_switch'

i have to change the word "switch" to 'switch_led' in the  code after line 162 and it work fine : 

example changed on line 164
before : SendCommandCloud(DeviceID, switch, False) --> doesn't work, the device never change it's state to Off
after modif : SendCommandCloud(DeviceID, 'switch_led', False) --> Working, the device switch to Off state

Any help ?

**Comment by Xenomes** [comment]
Update to the latest version, if this also not works change the 162 line switch to srt(switch).
`switch = 'switch_led' if searchCode('switch_led', FunctionProperties) else 'led_switch'`
to
`switch = str('switch_led') if searchCode('switch_led', FunctionProperties) else str('led_switch')`
There are a lot of light users who don't have issues.

**Comment by stefg73** [comment]
Hello, thanks for your help but it always doesn't work : state change in Domoticz but not the light

**Comment by Xenomes** [comment]
Hi,

Can you change the line to
```
switch = 'switch_led' if searchCode('switch_led', FunctionProperties) else 'led_switch'
Domoticz.Debug(switch)
```

in the log we be reported what the value of switch is.

**Comment by Xenomes** [comment]
Fixed in version 1.5.3

**Comment by stefg73** [comment]
Hi, thanks, it works like a charm !

**Comment by Xenomes** [comment]
Perfect!
