### ISSUE TITLE
Update Plugin to recognise Eurom 300 Mon Soleil Ceiling

### ISSUE THREAD

**Issue by Electr1fying** [Xenomes/Domoticz-TinyTUYA-Plugin#39]
Hello!

Could you please add changes to the code to support the Eurom 300 Mon Soleil Ceiling? I managed to get the proper attributes after changing the DP method to "DP instruction" within the Tuya IoT Platform.

Trying to make the code changes myself at the moment, but i have basic programming skills and it is pretty tough figuring out the right "Connections".

There are some obsolete attributes i figure after changing the DP mode to "Instruction" but i would be really happy if at least on/off, setting the temperature and reading out the temperature sensor work. Further TinyTuya wizard mentions these DPS after changing the DP instruction, in which U1 would be on/off, U2 the set temperature, U5 the current room temperature and i reckon U7 would be the timer in minutes, set per hour (e.g 60, 120, 180 etc.):

![image](https://user-images.githubusercontent.com/73641594/232221526-88fd3e02-4317-4d9a-ac18-1550b09c9634.png)

JSON dump in the attached file:

[Eurom-dump.txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/11239357/Eurom-dump.txt)

Thanks in advance!!

**Comment by Xenomes** [comment]
Hi Electr1fying,
Thanks for the Dump file!
The control of you device is added to the Develop branch, can you check it out?
Didn't add timer device can set by Domoticz of if used in tuya (brand) app, Domoticz show on or off.

**Comment by Electr1fying** [comment]
Hi Xenomes!

Wow. That was fast! Will let you know ASAP!

Thanks a ton!

Groet ;-)

**Comment by Electr1fying** [comment]
Hi Xenomes!

Just confirmed working:

- On/off
- Set Temperature
- Show Current Temperature.

All the devices i wanted.

Thanks!

**Comment by Xenomes** [comment]
HI thanks for the feed back! Good to head that it works.

**Comment by Xenomes** [comment]
Added to the Master
