### ISSUE TITLE
Expiration ?

### ISSUE THREAD

**Issue by ricorico94** [Xenomes/Domoticz-TinyTUYA-Plugin#43]
Hi,
I see a comment about "how to extend after expiration" -> does it mean the local control of devices will stop working after XX months, with need to extend manually ? If yes, is there any way to be warned about expiration, to avoid it occurs during holidays for instance ?
Based on message on TinyTuya project, I understand that TinyTuya will still work for "existing" devices, but would need the extension to retrieve details for new devices.
Is it the same for your plugin, or is there an expiration of whole plugin ?

and other question: your plugin will still work (via Local network) if internet connection is lost ? (it's the case for TinyTuya, but I'm wondering if your plugin always need access to the Cloud as it is the case for your other Tuya plugin).
Thanks

**Comment by Xenomes** [comment]
> Hi, I see a comment about "how to extend after expiration" -> does it mean the local control of devices will stop working after XX months, with need to extend manually ? 

Yes, for people how create a account after Oct 2022. Tuya decided that the develop have a lifetime of 6 moths, I am monitoring the HA community they have the same issue and the Tuya developers help create it there.

> If yes, is there any way to be warned about expiration, to avoid it occurs during holidays for instance ?

I have build in some detection but i can not test it, my main account is from before Oct 2022 I have a extra one but that one is not expired yet.

>Based on message on TinyTuya project, I understand that TinyTuya will still work for "existing" devices, but would need the extension to retrieve details for new devices. Is it the same for your plugin, or is there an expiration of whole plugin ?

The plugin use Tinytuya to pull info from the Tuya cloud, what the TinyTuya (Cloud) can do we can use in the plugin.

> and other question: your plugin will still work (via Local network) if internet connection is lost ? (it's the case for TinyTuya, but I'm wondering if your plugin always need access to the Cloud as it is the case for your other Tuya plugin).

I am using the cloud part of the Tinytuya app, so a internet connection is required. The Local options are not the same to use with the plugin.

**Comment by Xenomes** [comment]
Closed due to no response.
