### ISSUE TITLE
PIR Motion Sensor 

### ISSUE THREAD

**Issue by Magma1200** [Xenomes/Domoticz-TinyTUYA-Plugin#45]
Hello!
Will you add Smart Life PIR Motion Sensor DP-WP001 from Banggood?
It shows up in Domoticz units with text ¨This device is not reconised¨.

**Comment by Xenomes** [comment]
Hi @Magma1200,
For that i need the a json file for the device, you can create it by edit and running the debug_discovery.py from the tools directory. 
You can post it here or send it to xenomes@outlook.com

**Comment by Xenomes** [comment]
Thank for the json, there is no data in it to program the plugin. But there is a other option that reveals more options.
Goto https://iot.tuya.com/cloud/setMode and set the device on DP instruction. Then do a new json dump.

**Comment by Magma1200** [comment]
Ok, I will check.

Unable to save. Permission verification failed.  Is there some more
services that is needed to be turned on?

**Comment by Xenomes** [comment]
I see, think using the link is not working... Try.
https://iot.tuya.com/ => Cloud => Your project => Devices => Find your device in the boxes =>click pencil and change to 'DP Instruction'

**Comment by Xenomes** [comment]
Closed due to no response.
