### ISSUE TITLE
create new device. Camera

### ISSUE THREAD

**Issue by K1aasH** [Xenomes/Domoticz-TinyTUYA-Plugin#46]
Hello Xenomes,

i bought a Tuya PTZ indoor HD camera [.](https://www.bol.com/nl/nl/p/lsc-smart-connect-wifi-draaibare-camera-draait-355-en-kantelt-180-1080p-hd/9300000066840713/) It is visible as an device in Domoticz but it is not yet a part of the TinyTuya plug in family.

Can you make it work like 'on/off' and 'motion dectection' so maybe i can make an script like when a motion is detected the light in the room must go on?

![Device in Domoticz](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/110337158/12729f1c-17f7-4281-ac82-cda1d7fc7cae)

**Comment by Xenomes** [comment]
Hi can you make a dump file so i can check the json.
Edit and run the the debug_discovery.py in the tool directory.

**Comment by K1aasH** [comment]
Sorry, on a holiday right now. Coming home at 8 july.

**Comment by Xenomes** [comment]
The ticket was closed because there was no response or reaction.
