### ISSUE TITLE
New device - water leak sensor and presence sensor

### ISSUE THREAD

**Issue by aldodemi** [Xenomes/Domoticz-TinyTUYA-Plugin#47]
[dump.json.zip](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/11688410/dump.json.zip)
New water leak sensor and presence sensor

**Comment by Xenomes** [comment]
Thank you for the dump, The json is usable for the plugin. All other device recognized expert for the IR device?

**Comment by Xenomes** [comment]
Added your devices check https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/tree/47

**Comment by Gonolbe** [comment]
water leak not working for me. Device is created, but not updated:
2023-06-19 20:24:28.571 Error: Dispositivos TUYA: Device read failed: bfaa5e9951b0baf80auywz

**Comment by Xenomes** [comment]
OK, will check the code.

**Comment by Gonolbe** [comment]
I have managed to get it working. Changed this:

                if dev_type == 'waterleak':
                    if createDevice(dev['id'], 1):
                        Domoticz.Log('Create device Water leak sensor')
                        for item in StatusProperties:
                            if item['code'] == 'watersensor_state':
                                the_values = json.loads(item['values'])
                                mode = ['off']
                                mode.extend(the_values.get('range'))
                                options = {}
                                options['LevelOffHidden'] = 'true'
                                options['LevelActions'] = ''
                                options['LevelNames'] = '|'.join(mode)
                                options['SelectorStyle'] = '0'
                                Domoticz.Unit(Name=dev['name'] + ' (Status)', DeviceID=dev['id'], Unit=1, Type=244, Subtype=62, Switchtype=18, Options=options, Image=9, Used=1).Create()

by this:

                if dev_type == 'waterleak':
                    if createDevice(dev['id'], 1):
                        Domoticz.Log('Create device water leak sesor')
                        Domoticz.Unit(Name=dev['name'], DeviceID=dev['id'], Unit=1, Type=244, Subtype=73, Switchtype=11, Used=1).Create()

and this:

                  if dev_type == 'waterleak':
                        if searchCode('watersensor_state', ResultValue):
                            currentmode = StatusDeviceTuya('watersensor_state')
                            for item in FunctionProperties:
                                if item['code'] == 'watersensor_state':
                                    the_values = json.loads(item['values'])
                                    mode = ['off']
                                    mode.extend(the_values.get('range'))
                            if str(mode.index(str(currentmode)) * 10) != str(Devices[dev['id']].Units[1].sValue):
                                UpdateDevice(dev['id'], 1, int(mode.index(str(currentmode)) * 10), 1, 0)

by this:

                 if dev_type == 'waterleak':
                        if searchCode('watersensor_state', ResultValue):
                            currentstatus = StatusDeviceTuya('watersensor_state')
                            if currentstatus == 'normal':
                                UpdateDevice(dev['id'], 1, 'Off', 0, 0)
                            elif currentstatus == 'alarm':
                                 UpdateDevice(dev['id'], 1, 'On', 1, 0)

It creates a door contact sensor (there is no waterleak sensor in domoticz). I changed afterwards the logo to water leak, and thats all.

**Comment by Xenomes** [comment]
Thanks, I will take over your changes. If there is a device in the further with more status options we can always change it.
Added to the Master
