### ISSUE TITLE
Add new device: Pool heater

### ISSUE THREAD

**Issue by shakisha** [Xenomes/Domoticz-TinyTUYA-Plugin#49]
Hello, i have got this error on domoticz logs: Error: TinyTUYA: Device read failed, which device id is a pool heater.

Is there anyway to help you to add this into project code?

Regards

**Comment by Xenomes** [comment]
This error 'TinyTUYA: Device read failed,' You get then there is something wrong with the credentials or search device.

**Comment by shakisha** [comment]
@Xenomes  thank you, I'll close the issue

**Comment by shakisha** [comment]
I'm reopening the issue since the error is not related to something wrong in the credentials or search device. 
All the other devices are working and this device id is related to a pool heater which is shown as online in tuya cloud:

![CleanShot 2023-06-28 at 06 57 44](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/7482626/fab6de30-a9e0-46f9-811c-e9fa5113127a)

![CleanShot 2023-06-28 at 06 58 56](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/7482626/85a42fc1-bbe7-4491-a0e5-53d875ae8d7b)


I have to disable logs to avoid logs filling. Is there anyway to ignore a device until it will be implemented? 
I can help to implement it anyway :-)

**Comment by Xenomes** [comment]
OK that is strange, can you give me the export of the debug_discovery.py don't forget to edit the file. You can email it to xenomes@outlook.com

**Comment by shakisha** [comment]
@Xenomes  you have got an email :-)

**Comment by Xenomes** [comment]
Received it. Will check tomorrow.

**Comment by Xenomes** [comment]
I see the problem ...
The plugin create a device witch the options from functions... 'auto' is the only choice.
```
      {
        "code": "mode",
        "name": "\u6a21\u5f0f",
        "type": "Enum",
        "values": "{\"range\":[\"auto\"]}"
      }
```
But the results/status give this.
```
    {
      "code": "mode",
      "value": "h_silent"
    }
```
That will not match and creates the error.
I your app what are the choices you have for mode?

**Comment by shakisha** [comment]
silent, powerful, smart

---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
Can you do this?
Go to https://iot.tuya.com/ => Cloud => Your project => Devices => Find your device in the boxes =>click pencil and change to 'DP Instruction'
and create a new dump file and send it to me again.

**Comment by shakisha** [comment]
Give me 4-5 hours since I’m not at home and I’ll give you

---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by shakisha** [comment]
You have got mail :-)

---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by shakisha** [comment]
After the dump I have restored the instruction mode. Is it ok or you need again dp instruction mode?

---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
No that is no problem, will compare the two dumps and try to create a workarround for if the values are not matching.

**Comment by Xenomes** [comment]
Hi Again, Can you check out the Develop version. If there is a mismatch the update of the device will be skip.

**Comment by shakisha** [comment]
Ok, the Develop branch is not triggering the issue.
The only issue is now that the switch selector created contains only “auto”, without silent or smart .

Total modes are 6:

Smart cooling
Powerful cooling
Silent cooling

Smart heating
Powerful heating
Silent heating

If you need additional help I’ll be available :-)

---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
I could add a specific mode for this device only. But then i need a json result of all the six modes.

**Comment by shakisha** [comment]
where i can find it or how can i test them?

---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
You run the debug script and store the mode from the json
```
        "code": "mode",
        "desc": "{\"range\":[\"auto\"]}",
        "name": "\u6a21\u5f0f",
        "type": "Enum",
        "values": "{\"range\":[\"auto\"]}"
```
Change the value in the app and do it again etc...

**Comment by shakisha** [comment]
Troubles coming:


2023-07-04 12:28:37.142 Error: TinyTUYA: if Error is not None:
2023-07-04 12:28:37.142 Error: TinyTUYA: NameError: name 'Error' is not defined
2023-07-04 12:28:46.107 Error: TinyTUYA: Call to function 'onHeartbeat' failed, exception details:
2023-07-04 12:28:46.108 Error: TinyTUYA: Traceback (most recent call last):
2023-07-04 12:28:46.108 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 428, in onHeartbeat
2023-07-04 12:28:46.108 Error: TinyTUYA: _plugin.onHeartbeat()
2023-07-04 12:28:46.108 Error: TinyTUYA: File "/home/pi/domoticz/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 388, in onHeartbeat
2023-07-04 12:28:46.108 Error: TinyTUYA: if Error is not None:



---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
This is after switching the mode device?

**Comment by shakisha** [comment]
I think yes.
Let me debug all the statuses meanwhile and I’ll come back

---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by shakisha** [comment]
These are all the modes (between brackets I’ll put the readable names)


c_powerful  “Powerful cooling mode"
c_silent  “Silent cooling mode
cool  “Smart cooling mode"

h_powerful  “Powerful heating mode"
h_silent  “Silent heating mode”
heat  “Smart heating mode"

a_powerful “Powerful auto mode"
a_silent “Silent auto mode"
auto “Smart auto mode"


---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
Thanks i will try to add them to the plugin.

**Comment by shakisha** [comment]
Ok, I’ll wait you for your updates, thank you.

---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
The Develop is updated. Can you test if the commands are executed.
You need to delete only the mode device of the heatpump.

**Comment by shakisha** [comment]
---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by shakisha** [comment]
Issues...

---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
Can you post the error line?

**Comment by shakisha** [comment]
Where I can find it?

---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
Put the plugin om debug 'All' and there should be a error line in the log.

**Comment by shakisha** [comment]
2023-07-08 00:19:24.394 TinyTUYA: Device name=Calefactor piscina id=bff3f37f83b00fc2670a5y category=heatpump
2023-07-08 00:19:24.938 TinyTUYA: Update device value:bff3f37f83b00fc2670a5y Unit: 2 sValue: 25.0 nValue: 0 TimedOut=0
2023-07-08 00:19:24.939 TinyTUYA: Tuya delivers a wrong status, device not updated!


---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
Did you delete the mode device of the heatpump?

**Comment by shakisha** [comment]
Nope, i have just clicked on auto:

**Comment by Xenomes** [comment]
You need to delete the mode device so the plugin can create a new device with the new modes in the switch.

**Comment by shakisha** [comment]
When I try to choose the mode, nothing happens, the heatpump stays on smart auto mode and there is no way to change it.

How I can help on this?

2023-07-08 17:48:15.872 TinyTUYA: LastLevel: 10
2023-07-08 17:48:15.874 TinyTUYA: Debug switch Temp temp_set
2023-07-08 17:48:16.095 TinyTUYA: Command send to tuya :bff3f37f83b00fc2670a5y, {'commands': [{'code': 'mode', 'value': 'h_powerful'}]}
2023-07-08 17:48:16.102 TinyTUYA: Update device value:bff3f37f83b00fc2670a5y Unit: 4 sValue: 50 nValue: 1 TimedOut=0
2023-07-08 17:48:16.102 TinyTUYA: Acquiring GIL for 'onCommandCallback'


---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
Ok, Tinytuya can proces the given code.  The bypass doesn't work. Then I need to change the code that the mode will be disabled when there is incompatibel function.

**Comment by shakisha** [comment]
ok

---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
Can you update Tinytuya to the latest version?
sudo pip install tinytuya -U

**Comment by shakisha** [comment]
Done but still the same, mode switching neither temperature selection are working.

2023-07-10 23:40:10.173 TinyTUYA: Debug switch Temp temp_set
2023-07-10 23:40:10.436 TinyTUYA: Command send to tuya :bff3f37f83b00fc2670a5y, {'commands': [{'code': 'mode', 'value': 'c_silent'}]}
2023-07-10 23:40:10.447 TinyTUYA: Update device value:bff3f37f83b00fc2670a5y Unit: 4 sValue: 90 nValue: 1 TimedOut=0
2023-07-10 23:40:10.448 TinyTUYA: Acquiring GIL for 'onCommandCallback'

---
Roberto Innaimi
692 22 97 13
robertoinnaimi.com

**Comment by Xenomes** [comment]
I am so sorry; I was cleaning up the issues and saw a response. I hope you figured out that the mode device was removed because the status and the possible choices don't match.

**Comment by shakisha** [comment]
@Xenomes  I didn't updated the app, but the possibility to turn on and off the device are just incredible and enough for me :-)

**Comment by Xenomes** [comment]
OK, if that is not a problem for you, then I will close the issue.
