### ISSUE TITLE
Add Woox smart wifi garden irrigator 

### ISSUE THREAD

**Issue by galadril** [Xenomes/Domoticz-TinyTUYA-Plugin#51]
Thanks for pointing to this repo for the TinyTUYA plugin. I've setup the plugin and now see that my irrigator is not a recognised device.
This is the info from the dump json file:

```
 {
    "name": "Bewatering",
    "id": "bf2df00703453453",
    "category": "sfkzq",
    "product_name": "R4238 Smart Irrigation Control",
    "product_id": "behtc3gdmbuvzrjz",
    "biz_type": 18,
    "model": "R4238",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1533895021982bN2sO/11d9adfee48220559d5d8f38f612ae44.png"
  },
```

**Comment by Xenomes** [comment]
Hi i am missing the extra data for device bf2df00703453453.

**Comment by galadril** [comment]
"uuid": "662e53aa1b89e291" ?

**Comment by galadril** [comment]
ah i get it, you mean those properties??

Properties of device: bf2df0070f8dffab5cd265
{
  "result": {
    "category": "sfkzq",
    "functions": [
      {
        "code": "switch",
        "desc": "{}",
        "name": "\u9600\u95e8\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "weather_delay",
        "desc": "{\"range\":[\"cancel\",\"24h\",\"48h\",\"72h\"]}",
        "name": "\u5929\u6c14\u5ef6\u65f6",
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"24h\",\"48h\",\"72h\"]}"
      },
      {
        "code": "countdown",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cycle_time",
        "desc": "{}",
        "name": "\u5faa\u73af\u5b9a\u65f6",
        "type": "String",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "name": "\u9600\u95e8\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_percentage",
        "name": "\u7535\u6c60\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "weather_delay",
        "name": "\u5929\u6c14\u5ef6\u65f6",
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"24h\",\"48h\",\"72h\"]}"
      },
      {
        "code": "countdown",
        "name": "\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "work_state",
        "name": "\u5de5\u4f5c\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\",\"idle\"]}"
      },
      {
        "code": "use_time_one",
        "name": "\u5355\u6b21\u4f7f\u7528\u65f6\u95f4",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1688473982475,
  "tid": "eaddc6431a6611ee871736843e81b476"
}
Status of device: bf2df0070f8dffab5cd265
{
  "result": [
    {
      "code": "switch",
      "value": false
    },
    {
      "code": "battery_percentage",
      "value": 74
    },
    {
      "code": "weather_delay",
      "value": "cancel"
    },
    {
      "code": "countdown",
      "value": 0
    },
    {
      "code": "work_state",
      "value": "idle"
    },
    {
      "code": "use_time_one",
      "value": 600
    }
  ],
  "success": true,
  "t": 1688473982628,
  "tid": "eaf58d8e1a6611ee8ac9ce4d0cb672c1"
}

**Comment by Xenomes** [comment]
And the status 😁

**Comment by galadril** [comment]
yeah i just noticed why the json contained more data 🥇 woops

**Comment by Xenomes** [comment]
Hi if you checkout the Develop you device is added to Domoticz. Need some final test to add it to the master.

**Comment by galadril** [comment]
Thanks, it did added 2 devices;
![image](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/14561640/df8f27d0-4b86-4fc9-b566-a965fc9662b3)

Its currently storming outside, but ill try to test some commands somewhere today

**Comment by galadril** [comment]
Maybe set the icon to this one>
![image](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/14561640/639162e7-d268-4eac-bf65-755c367a2f2b)

And its weird that the type is switch, but also unknown?

**Comment by Xenomes** [comment]
Where do you see the unknown?
I will update the code to use the icon 22.
You can update you device, using this:
/json.htm?type=setused&used=true&name=Bewatering&idx=<idx>&customimage=22

**Comment by galadril** [comment]
It showed unknown type here:
![image](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/14561640/33e9c3af-fbff-4d01-921c-a3a973683b5f)

And when  you click on edit device, it doesnt show any value on the device type combobox:
![image](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/14561640/341315c8-6f70-46b0-8c83-1a850ff9bb42)

Its gone if i manually set it to on/off switch and indeed i can also update the image there.. just wanted to mention it ;)

**Comment by galadril** [comment]
turning on/off works greatly, i see the status change and the battery indicator is also correct.

**Comment by Xenomes** [comment]
Ha yes I see now, i used a wrong Switchtype at the creation of the device.
You can correct it with: /json.htm?type=setused&used=true&name=Bewatering&idx=idx&customimage=22&switchtype=0

**Comment by galadril** [comment]
yes thanks, did that already.
the rest is working as expected, thanks

**Comment by Xenomes** [comment]
Ok thanks. I will merge it tomorrow to  the master.
