### ISSUE TITLE
Add LED Projector

### ISSUE THREAD

**Issue by chirogocki** [Xenomes/Domoticz-TinyTUYA-Plugin#52]
Hello,

I followed domoticz logs " This device is not reconised, edit and run the debug_discovery with python from the tools directory and receate a issue report at https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/issues so the device can be added."

Here is a part of the dump.json

> Properties of device: bffe--------------y1jd
> {
>   "result": {
>     "category": "xktyd",
>     "functions": [
>       {
>         "code": "switch_led",
>         "desc": "{}",
>         "name": "\u5f00\u5173",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "colour_data",
>         "desc": "{}",
>         "name": "\u5f69\u5149",
>         "type": "Json",
>         "values": "{}"
>       },
>       {
>         "code": "countdown",
>         "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
>         "name": "\u5012\u8ba1\u65f61",
>         "type": "Integer",
>         "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "mic_music_data",
>         "desc": "{\"maxlen\":\"255\"}",
>         "name": "\u9ea6\u514b\u98ce\u97f3\u4e50\u5f8b\u52a8",
>         "type": "String",
>         "values": "{\"maxlen\":\"255\"}"
>       },
>       {
>         "code": "star_work_mode",
>         "desc": "{\"range\":[\"manual\",\"scene\",\"music\"]}",
>         "name": "\u5de5\u4f5c\u6a21\u5f0f",
>         "type": "Enum",
>         "values": "{\"range\":[\"manual\",\"scene\",\"music\"]}"
>       },
>       {
>         "code": "colour_switch",
>         "desc": "{}",
>         "name": "\u5f69\u5149\u5f00\u5173",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "laser_switch",
>         "desc": "{}",
>         "name": "\u6fc0\u5149\u5f00\u5173",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "laser_bright",
>         "desc": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}",
>         "name": "\u6fc0\u5149\u4eae\u5ea6",
>         "type": "Integer",
>         "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "star_control_data",
>         "desc": "{}",
>         "name": "\u5b9e\u65f6\u8c03\u8282",
>         "type": "Raw",
>         "values": "{}"
>       },
>       {
>         "code": "star_scene_data",
>         "desc": "{}",
>         "name": "\u60c5\u666f",
>         "type": "Raw",
>         "values": "{}"
>       },
>       {
>         "code": "fan_switch",
>         "desc": "{}",
>         "name": "\u9a6c\u8fbe\u5f00\u5173",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "fan_speed",
>         "desc": "{\"unit\":\"%\",\"min\":1,\"max\":100,\"scale\":0,\"step\":1}",
>         "name": "\u9a6c\u8fbe\u8f6c\u901f",
>         "type": "Integer",
>         "values": "{\"unit\":\"%\",\"min\":1,\"max\":100,\"scale\":0,\"step\":1}"
>       }
>     ],
>     "status": [
>       {
>         "code": "switch_led",
>         "name": "\u5f00\u5173",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "colour_data",
>         "name": "\u5f69\u5149",
>         "type": "Json",
>         "values": "{}"
>       },
>       {
>         "code": "countdown",
>         "name": "\u5012\u8ba1\u65f61",
>         "type": "Integer",
>         "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "mic_music_data",
>         "name": "\u9ea6\u514b\u98ce\u97f3\u4e50\u5f8b\u52a8",
>         "type": "String",
>         "values": "{\"maxlen\":\"255\"}"
>       },
>       {
>         "code": "star_work_mode",
>         "name": "\u5de5\u4f5c\u6a21\u5f0f",
>         "type": "Enum",
>         "values": "{\"range\":[\"manual\",\"scene\",\"music\"]}"
>       },
>       {
>         "code": "colour_switch",
>         "name": "\u5f69\u5149\u5f00\u5173",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "laser_switch",
>         "name": "\u6fc0\u5149\u5f00\u5173",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "laser_bright",
>         "name": "\u6fc0\u5149\u4eae\u5ea6",
>         "type": "Integer",
>         "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "star_scene_data",
>         "name": "\u60c5\u666f",
>         "type": "Raw",
>         "values": "{}"
>       },
>       {
>         "code": "fan_switch",
>         "name": "\u9a6c\u8fbe\u5f00\u5173",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "fan_speed",
>         "name": "\u9a6c\u8fbe\u8f6c\u901f",
>         "type": "Integer",
>         "values": "{\"unit\":\"%\",\"min\":1,\"max\":100,\"scale\":0,\"step\":1}"
>       }
>     ]
>   },
>   "success": true,
>   "t": 1690980093941,
>   "tid": "e9b25b22313111ee871736843e81b476"
> }
> Status of device: bffe--------------y1jd
> {
>   "result": [
>     {
>       "code": "switch_led",
>       "value": false
>     },
>     {
>       "code": "colour_data",
>       "value": "{\"h\":240,\"s\":1000,\"v\":1000}"
>     },
>     {
>       "code": "countdown",
>       "value": 0
>     },
>     {
>       "code": "mic_music_data",
>       "value": "000002003232"
>     },
>     {
>       "code": "star_work_mode",
>       "value": "manual"
>     },
>     {
>       "code": "colour_switch",
>       "value": true
>     },
>     {
>       "code": "laser_switch",
>       "value": false
>     },
>     {
>       "code": "laser_bright",
>       "value": 1000
>     },
>     {
>       "code": "star_scene_data",
>       "value": "AA4AAQMyAQPoATI="
>     },
>     {
>       "code": "fan_switch",
>       "value": true
>     },
>     {
>       "code": "fan_speed",
>       "value": 100
>     }
>   ],
>   "success": true,
>   "t": 1690980094147,
>   "tid": "e9d31d2d313111ee8ecbe2b0bc7235c7"
> }

Information on this device can be found here : https://a.aliexpress.com/_Ew44vkB

Perhaps it will be difficult to integrate, there is 3 type of action :
- RGBW LED (gradient for luminosity, contrast and a color wheel)
- Fan control ON/OFF + speed (if you want to rotate the picture you can use a gradiant from 0 to 100%)
- Laser control ON/OFF + luminosity

Thanks for your help

Regards,

**Comment by Xenomes** [comment]
Thanks for the JSON data, I will look at it and what to import it to Domoticz.

**Comment by Xenomes** [comment]
Hi, I am adding the led projector, can you tell me what color control can do color and white light?

**Comment by chirogocki** [comment]
Hello @Xenomes,
I'm not sure of it. In smart Life app there is no control for white light directly but we can change the color's intensity.
Here is 2 captures of the app (I add comments in red).
I hope it can help you
![Screenshot_20230906-084743](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/9b2dc487-71d6-4f49-859a-62558c0c984c)
![Screenshot_20230906-084756](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/44b8f32b-a48f-4cea-a751-0af8e728f70d)
You can see the result on my ceiling
![PXL_20230906_064824792](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/bbc469fa-3946-4633-b115-da99a8a122be)
Thank you

**Comment by Xenomes** [comment]
Oke thanks for the screenshots! this is very helpful! Nice result btw!

**Comment by Xenomes** [comment]
Hi, can you check out the Develop version and test the plugin with your device?
```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service
```
To revert to the Master, change Develop to Master

**Comment by chirogocki** [comment]
Hi,
Thank you for your work !
I switched to Develop branch and now have 3 new devices :

- Projecteur LED (Colour)
- Projecteur LED (Laser)
- Projecteur LED (Fan)

Here is what I see 
![Capture d’écran 2023-09-07 à 08 37 05](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/4ebc25b2-74e9-4db5-b973-50259e4d6f33)
As you can see Projecteur LED (Colour) have fan type icon and is Light/Switch, Switch, ON/OFF
Normally it would be ColorSwitch, White, Dimmer.
I try ON/OFF command -> it's working great !

![Capture d’écran 2023-09-07 à 08 37 10](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/4f5a3b65-9800-4a33-ac8d-b03d8d8b132c)
Projecteur LED (Laser) is ColorSwitch, White, Dimmer but have to be Light/Switch, Switch, Dimmer
I can OFF the laser 1 time, ON command is not working and intensity have no effect

![Capture d’écran 2023-09-07 à 08 37 16](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/6c73dc83-24b2-40df-a86f-f981825cd8ad)
Projecteur LED (Fan) have switch type icon, is ColorSwitch, White, Dimmer but have to be Light/Switch, Switch, Dimmer
Same result command as Projecteur LED (Laser) -> I can OFF the fan 1 time, ON command is not working and intensity have no effect

Don't hesitate to ask me more tests

Have a good day !

**Comment by Xenomes** [comment]
Hi, Thanks for testing, I did find the bug. Pull the new develop, delete the four devices, and restart Domoticz.

**Comment by chirogocki** [comment]
Hi,
I pulled develop branch; delete the 4 devices (3 in switches and 1 in utility) and restartd domoticz.
This is a little bit strange...
Here is what I see in domoticz in my browser : 
![Capture d’écran 2023-09-10 215242](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/1d18e93a-c136-43f0-9298-862de3576a8b)

- Projecteur LED is Color Switch, RGBWW, Dimmer but act like a ON/OFF switch everytime I used it (color wheel and intensity have no effects).
- Projecteur LED (Colour)  is ON/OFF switch but do nothing.
- Projecteur LED (Laser) start OFF, I can ON it 1 time. I can play with intensity laser (this time), but if I OFF it one time I can't ON it again
- Projecteur LED (Fan) start OFF, I can ON it 1 time. I can play with intensity fan (this time), but if I OFF it one time I can't ON it again

In this develop version I can ON and OFF the projector with "Projecteur LED" with previous remembered state.

I hope this will help you.

Thanks for your hard work !

**Comment by Xenomes** [comment]
Hi,
Thank you for the feedback. I have changed the plugin again. Hopefully, we are heading towards the right solution. I cannot do device debugging, so that's what you are doing.
P.S. You don't have to delete the devices now.

**Comment by chirogocki** [comment]
Hi,
No problem for me to debug and thanks for your work.
It's better ! But not all done.

Here is domoticz screenshot :
![Capture d’écran 2023-09-12 à 08 05 38](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/54c248ea-973e-4609-92ab-3c7aa594fc98)

Projecteur LED (Laser) and Projecteur LED (Fan) are now ok ! I can ON and OFF it and play with intensity.
Projecteur LED and Projecteur LED (Colour) seems to be inverted. The color wheel and intensity for Projecteur LED is not working.

Have a nice day !

P.S. Sorry I saw your comment too late I have deleted the device after pulled develop branch.... I was too exited to test

**Comment by Xenomes** [comment]
Okay, I have reversed the 'Projecteur LED (Colour)' and changed 'Projecteur LED' to RGB. You only have to delete 'Projecteur LED'.

**Comment by chirogocki** [comment]
Hi,

Something is strange now, I pulled develop, deleted 'Projecteur LED' and restart domoticz.
There were no change in discovered devices but they seem to be offline, Here is a screenshot : 
<img width="1191" alt="Capture d’écran 2023-09-12 à 22 27 50" src="https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/c277bb03-8030-4167-9bf3-fb121ccff654">
And strangely it appears to have affected other device (Aquarium and Lampe salon cactus). 
- I checked my IOT core subscription and it's OK
- I can use the domotic'z offline devices with smart life app
- I try to change device in Search DeviceID in TinyTuya setup because I saw in the log the previous Search DeviceID was in error
`2023-09-12 22:42:31.568 Error: TinyTuyaCloud: Device read failed: bffe8aecfxxxxxxxxxxxx`
- I try to delete offline devices in domoticz, restart domoticz

I ended to deplug and replug the faulty devices and now they are all OK in domoticz (spot 2 and spot 5 are unplugged)
<img width="1195" alt="Capture d’écran 2023-09-12 à 22 40 35" src="https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/5bdf789a-34a2-4341-872a-34628fcc73bb">
But after playing with projector device, as I say,  I don't see any change from your previous change.
Did I do something wrong ?

**Comment by Xenomes** [comment]
Okay, that is strange. bffe8aecfxxxxxxxxxxxx is the starlight, I found a typo in the color control and fixed that.

**Comment by chirogocki** [comment]
Hi !
I pulled develop, delete the 4 devices and restart domoticz.
<img width="1193" alt="Capture d’écran 2023-09-14 à 07 31 05" src="https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/2129bf17-14bb-4666-b772-7e87d37c9b51">
Projecteur LED (Laser) and Projecteur LED (Fan) are working as expected ! I can ON and OFF it and play with intensity.
Projecteur LED and Projecteur LED (Colour) seems to be inverted again. And now Projecteur LED (Colour) ON/OFF switch is inverted when ON it it's OFF and vice versa.
In normal operation Projecteur LED act as a global switch it turn ON/OFF the whole device that's why I think Projecteur LED and Projecteur LED (Colour) type are inverted.
Thanks for your time !
Have a great day

**Comment by Xenomes** [comment]
Oh, okay, I think I understand now. I've reprogrammed it differently. After the update, you don't need to remove devices.

**Comment by chirogocki** [comment]
Hi,
Thanks, I made some test and I try to explain what is still wrong.
We can consider Projecteur LED (Laser) and Projecteur LED (Fan) are working just good !

In Smart Life app I have this screen :
![Screenshot_20230916-084307](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/e8c2e623-7a17-4f4d-9403-da5b18e14b44)
In this exact state :
- First bar (brightness) to 100%
- Second bar (color intensity) to 0%

The projector make these colors :
![PXL_20230916_064337651 PORTRAIT](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/1e97020e-28f0-49ab-b214-f4b7e2eced41)
If I change the color on the wheel, there is no effect because the second bar is 0%
If I put the first bar to 0% and the second bar to 0% there is no color at all (consider it's off)

Other example with this screen (second bar to 100%)
![Screenshot_20230916-084402](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/8a9b67ce-ea55-4887-b83a-26c73881786d)
the colors are green:
![PXL_20230916_064414284 PORTRAIT](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/a45bb3e8-d581-4bdb-b7fb-cf4415501a30)

For this screen :
![Screenshot_20230916-084442](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/502449ce-3ea7-4281-9e96-a5fd4bc064eb)
it produce this :
![PXL_20230916_064453389 PORTRAIT](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/064a7502-cc80-421e-b51b-63edc4309ebd)

If I try to reproduce this in domoticz app
![Screenshot_20230916-084932](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/ca108cc1-95d3-4fca-b0d4-bc77787adade)
If Projecteur LED is ON and Projecteur LED (Colour) is OFF there is no projection.
If Projecteur LED (Colour) is ON and Projecteur LED  is OFF there is no projection.
Projecteur LED and Projecteur LED (Colour) must be ON to see something.

When the 2 devices are turned ON :
Projecteur LED bar seems to have no effect on colors. When I open the color wheel
![Screenshot_20230916-084947](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/d93e5f30-7a29-42b6-8b15-7ee9cc4a2d8c)
If I let the cursor at the center, this produce the same effect in Smart life (first example : first bar 100%, second bar 0%)
If I try other colors, 100% red or 100% blue or green, there is a slightly change in color but it remain mostly like the first photo (red blue green). 

Is that helping you ? if you want me to do a specific test don't hesitate.

Thank you

**Comment by Xenomes** [comment]
Hi,
Okay, thanks for the detailed report I think what is happening.
> If Projecteur LED is ON and Projecteur LED (Colour) is OFF there is no projection.
If Projecteur LED (Colour) is ON and Projecteur LED is OFF there is no projection.
Projecteur LED and Projecteur LED (Colour) must be ON to see something.

I must see these two devices as one, I will check the code if that is programmed.

> If I let the cursor at the center, this produce the same effect in Smart life (first example : first bar 100%, second bar 0%)
If I try other colors, 100% red or 100% blue or green, there is a slightly change in color but it remain mostly like the first photo (red blue green).

That must be a scaling problem, Tuya use different scaling, at the moment 0-255 will change it to 0-1000. 
I will you know when the new version is ready.

Thanks for your patience.

**Comment by Xenomes** [comment]
The changes are in the new Develop!

**Comment by chirogocki** [comment]
Hi,

Wooo what a progress ! It's seems to work
<img width="788" alt="Capture d’écran 2023-09-17 à 16 56 43" src="https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/2405e1af-2726-4832-835a-c5b422ef1420">
Now the 2 devices are linked with ON/OFF function, if I OFF Projecteur LED (Colour), Projecteur LED turn OFF.
The bar for Projecteur LED have no effect but
<img width="361" alt="Capture d’écran 2023-09-17 à 16 57 24" src="https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/6080452f-d292-40f0-8623-ed3fc940d99d">
The bar in color wheel change color brightness and when I select blue, it's blue ! Great !!!

We are close to success ! I just see that we have a problem with the laser scaling
<img width="393" alt="Capture d’écran 2023-09-17 à 16 59 03" src="https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11406431/42976baa-5942-4e6b-963c-363c959bcf3c">
Laser are active starting from 30%, can you please adjust the scaling ?

Thank for your work !

PS : I have another tuya device well known by TinyTuya (a bulb light) but colors didn't work as expected. How can I open an issue properly ?

**Comment by Xenomes** [comment]
> The bar for Projecteur LED have no effect but

Changed some coding.

> Laser are active starting from 30%, can you please adjust the scaling ?

Correct the scaling 1 to 1000

> PS : I have another tuya device well known by TinyTuya (a bulb light) but colors didn't work as expected. How can I open an issue properly ?

Make a new issue and add a dump of the device. there is a change by tuya with the color code.

**Comment by Xenomes** [comment]
Change some code to make the dim bar working.

**Comment by chirogocki** [comment]
Hello,
Sorry for the delay. I was sick.

Scaling for laser have slightly changed. Now I can see it starting from 22%

The dim bar for Projecteur LED works only if I change color in the wheel after, but it kindly works !

Thank you

**Comment by Xenomes** [comment]
Okay, then i start to program the read back from Tuya. Maybe the 22% can be corrected.

**Comment by Xenomes** [comment]
I had a idea to correct the 22%, can you check the lathest Develop version?

**Comment by chirogocki** [comment]
Hello,

I checked the last Develop version, unfortunately, there is no change. Laser start at 22%

Thank you

**Comment by Xenomes** [comment]
Sorry my bad, did change the LED.

**Comment by Xenomes** [comment]
I change the scale fix to the laser.

**Comment by chirogocki** [comment]
Ok, for laser 0% turns the laser OFF, from 2% to 100% it turns it ON but with always the same brightness (not full bright).

It's the same thing for LED.

Thanks

**Comment by Xenomes** [comment]
OK, The 0% Off is good, But from1 to 100% the value should go up to 1000, I see i have made a mistake in the calculation. Can you set the debug in the log to 'All' and your see the command send to Tuya: {'commands': [{'code': 'laser_bright', 'value': 228}]}
Can you try the new Push.

**Comment by chirogocki** [comment]
I've updated to last develop version. It's way much better !
When I put laser to 0% I have this log

> 2023-10-28 10:17:55.580 TinyTuyaCloud: Command send to tuya :***********fby1jd, {'commands': [{'code': 'laser_switch', 'value': False}]}
> 2023-10-28 10:17:55.588 TinyTuyaCloud: Update device value: ***********fby1jd Unit: 3 sValue: Off nValue: 0 TimedOut=0

and when I put to 3% :

> 2023-10-28 10:18:13.580 TinyTuyaCloud: Command send to tuya :***********fby1jd, {'commands': [{'code': 'laser_switch', 'value': True}]}
> 2023-10-28 10:18:13.784 TinyTuyaCloud: Command send to tuya :***********fby1jd, {'commands': [{'code': 'laser_bright', 'value': 244}]}
> 2023-10-28 10:18:13.795 TinyTuyaCloud: Update device value: ***********fby1jd Unit: 3 sValue: On nValue: 1 TimedOut=0
> 2023-10-28 10:18:13.803 TinyTuyaCloud: Update device value: ***********fby1jd Unit: 3 sValue: 3 nValue: 1 TimedOut=0

Now the settings are correct for laser. Thank you


As I said to you earlier : "The dim bar for Projecteur LED works only if I change color in the wheel after, but it kindly works !"
In fact, the dim bar has no effect when I slide on it, it take effect after changing color on the wheel.

Again thank you for your time and work !

**Comment by Xenomes** [comment]
Good to hear that the laser is working. The reports in the log are as expected. The dim bar or color wheel is triggered by a different code. I will try to find a better code for this.

**Comment by Xenomes** [comment]
Hi, I have found a solution, can you check the Develop version?

**Comment by Xenomes** [comment]
The ticket was closed because there was no response or reaction.
