### ISSUE TITLE
Add WiFi Digital Meter

### ISSUE THREAD

**Issue by ccdesmers** [Xenomes/Domoticz-TinyTUYA-Plugin#53]
Hi, just add your plugins to Domoticz (2023.2 version) and it works just Great!!
I wanted to add a new Digital meter to follow my poer consumption, but it is not working:
here some extracts from the json file:

"name": "compteur maison",
    "id": "bf0edd46cf895216b3syjv",
    "key": "Deleted",
    "mac": "50:8b:b9:8a:c7:1f",
    "uuid": "2c2477701c2f3307",
    "sn": "1001118290025A",
    "category": "aqcz",
    "product_name": "WiFi Digital Meter",
    "product_id": "djfep9s6s3b2qk89",
    "biz_type": 18,
    "model": "PJ-1103",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/bay16111967609110m8U/f38a6728

**Comment by Xenomes** [comment]
Hi, I need the three parts of the JSON to create the correct code.

**Comment by ccdesmers** [comment]
hello, here it comes, full json (the one i want is the "Compteur Maison" one ;-) ) :

List of devices: 
[
  {
    "name": "Strippy",
    "id": "8605344670039f0e73fe",
    "key": "Deleted",
    "mac": "70:03:9f:0e:73:fe",
    "uuid": "8605344670039f0e73fe",
    "sn": "1000702010015E",
    "category": "cz",
    "product_name": "Strippy",
    "product_id": "ur3vwrw6otlobdwz",
    "biz_type": 18,
    "model": "Strippy",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/solution/9001/9baa03908eb18111_cover.png"
  },
  {
    "name": "Lampe Salon",
    "id": "bf9c7dcbf37e3aa409835s",
    "key": "Deleted",
    "mac": "fc:67:1f:f3:63:29",
    "uuid": "a96b88f50e7e2210",
    "category": "cz",
    "product_name": "Aubess Smart\u00a0Socket 20A/EM",
    "product_id": "2iepauebcvo74ujc",
    "biz_type": 18,
    "model": "Aubess Smart\u00a0socket 20A/EM",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1543221103243UgKoi/f4658549a85627521b71883301740c77.png"
  },
  {
    "name": "compteur maison",
    "id": "bf0edd46cf895216b3syjv",
    "key": "Deleted",
    "mac": "50:8b:b9:8a:c7:1f",
    "uuid": "2c2477701c2f3307",
    "sn": "1001118290025A",
    "category": "aqcz",
    "product_name": "WiFi Digital Meter",
    "product_id": "djfep9s6s3b2qk89",
    "biz_type": 18,
    "model": "PJ-1103",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/bay16111967609110m8U/f38a67283ad104867f4ca70eb9817f4e.jpg"
  },
  {
    "name": "brosse \u00e0 dents papa",
    "id": "bf31f56806358df1f1ayfd",
    "key": "Deleted",
    "mac": "fc:67:1f:fe:38:f9",
    "uuid": "6a32b9170dd9a5bb",
    "category": "cz",
    "product_name": "Aubess Smart\u00a0Socket 20A/EM",
    "product_id": "2iepauebcvo74ujc",
    "biz_type": 18,
    "model": "Aubess Smart\u00a0socket 20A/EM",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1543221103243UgKoi/f4658549a85627521b71883301740c77.png"
  }
]
Properties of device: 8605344670039f0e73fe
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "desc": "{}",
        "name": "\u5f00\u51732",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "desc": "{}",
        "name": "\u5f00\u51733",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "desc": "{}",
        "name": "\u5f00\u51734",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_5",
        "desc": "{}",
        "name": "\u5f00\u51735",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51732\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51733\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_4",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51734\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_5",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51735\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "name": "\u5f00\u51732",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "name": "\u5f00\u51733",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "name": "\u5f00\u51734",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_5",
        "name": "\u5f00\u51735",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "name": "\u5f00\u51732\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "name": "\u5f00\u51733\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_4",
        "name": "\u5f00\u51734\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_5",
        "name": "\u5f00\u51735\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1692028005998,
  "tid": "c5f63eac3ab911ee9a70760d0d3c40d3"
}
Status of device: 8605344670039f0e73fe
{
  "result": [
    {
      "code": "switch_1",
      "value": false
    },
    {
      "code": "switch_2",
      "value": true
    },
    {
      "code": "switch_3",
      "value": false
    },
    {
      "code": "switch_4",
      "value": false
    },
    {
      "code": "switch_5",
      "value": false
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "countdown_2",
      "value": 0
    },
    {
      "code": "countdown_3",
      "value": 0
    },
    {
      "code": "countdown_4",
      "value": 0
    },
    {
      "code": "countdown_5",
      "value": 0
    }
  ],
  "success": true,
  "t": 1692028006424,
  "tid": "c62b95c23ab911eeb1a5226f85af9d81"
}
Properties of device: bf9c7dcbf37e3aa409835s
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "desc": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}",
        "name": "\u4e0a\u7535\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "overcharge_switch",
        "desc": "{}",
        "name": "\u8fc7\u5145\u4fdd\u62a4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "light_mode",
        "desc": "{\"range\":[\"relay\",\"pos\",\"none\"]}",
        "name": "\u6307\u793a\u706f\u72b6\u6001\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\"]}"
      },
      {
        "code": "child_lock",
        "desc": "{}",
        "name": "\u7ae5\u9501",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cycle_time",
        "desc": "{}",
        "name": "\u5faa\u73af\u5b9a\u65f6",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "desc": "{}",
        "name": "\u968f\u673a\u5b9a\u65f6",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "desc": "{}",
        "name": "\u70b9\u52a8\u5f00\u5173",
        "type": "String",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "name": "\u589e\u52a0\u7535\u91cf",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "name": "\u5f53\u524d\u7535\u6d41",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "name": "\u5f53\u524d\u529f\u7387",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":80000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "name": "\u5f53\u524d\u7535\u538b",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "relay_status",
        "name": "\u4e0a\u7535\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "overcharge_switch",
        "name": "\u8fc7\u5145\u4fdd\u62a4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "light_mode",
        "name": "\u6307\u793a\u706f\u72b6\u6001\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\"]}"
      },
      {
        "code": "child_lock",
        "name": "\u7ae5\u9501",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cycle_time",
        "name": "\u5faa\u73af\u5b9a\u65f6",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "name": "\u968f\u673a\u5b9a\u65f6",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "name": "\u70b9\u52a8\u5f00\u5173",
        "type": "String",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1692028006822,
  "tid": "c66bc2973ab911eea9649a766792eea9"
}
Status of device: bf9c7dcbf37e3aa409835s
{
  "result": [
    {
      "code": "switch_1",
      "value": false
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "add_ele",
      "value": 3
    },
    {
      "code": "cur_current",
      "value": 0
    },
    {
      "code": "cur_power",
      "value": 0
    },
    {
      "code": "cur_voltage",
      "value": 2286
    },
    {
      "code": "relay_status",
      "value": "power_off"
    },
    {
      "code": "overcharge_switch",
      "value": false
    },
    {
      "code": "light_mode",
      "value": "relay"
    },
    {
      "code": "child_lock",
      "value": false
    },
    {
      "code": "cycle_time",
      "value": ""
    },
    {
      "code": "random_time",
      "value": ""
    },
    {
      "code": "switch_inching",
      "value": ""
    }
  ],
  "success": true,
  "t": 1692028007182,
  "tid": "c6abc1b73ab911eeb1a5226f85af9d81"
}
Properties of device: bf0edd46cf895216b3syjv
{
  "result": {
    "category": "aqcz"
  },
  "success": true,
  "t": 1692028007573,
  "tid": "c6e15f993ab911eeb1a5226f85af9d81"
}
Status of device: bf0edd46cf895216b3syjv
{
  "result": [],
  "success": true,
  "t": 1692028008010,
  "tid": "c727a98b3ab911eeb1a5226f85af9d81"
}
Properties of device: bf31f56806358df1f1ayfd
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "desc": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}",
        "name": "\u4e0a\u7535\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "overcharge_switch",
        "desc": "{}",
        "name": "\u8fc7\u5145\u4fdd\u62a4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "light_mode",
        "desc": "{\"range\":[\"relay\",\"pos\",\"none\"]}",
        "name": "\u6307\u793a\u706f\u72b6\u6001\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\"]}"
      },
      {
        "code": "child_lock",
        "desc": "{}",
        "name": "\u7ae5\u9501",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cycle_time",
        "desc": "{}",
        "name": "\u5faa\u73af\u5b9a\u65f6",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "desc": "{}",
        "name": "\u968f\u673a\u5b9a\u65f6",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "desc": "{}",
        "name": "\u70b9\u52a8\u5f00\u5173",
        "type": "String",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "name": "\u589e\u52a0\u7535\u91cf",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "name": "\u5f53\u524d\u7535\u6d41",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "name": "\u5f53\u524d\u529f\u7387",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":80000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "name": "\u5f53\u524d\u7535\u538b",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "relay_status",
        "name": "\u4e0a\u7535\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "overcharge_switch",
        "name": "\u8fc7\u5145\u4fdd\u62a4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "light_mode",
        "name": "\u6307\u793a\u706f\u72b6\u6001\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\"]}"
      },
      {
        "code": "child_lock",
        "name": "\u7ae5\u9501",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cycle_time",
        "name": "\u5faa\u73af\u5b9a\u65f6",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "name": "\u968f\u673a\u5b9a\u65f6",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "name": "\u70b9\u52a8\u5f00\u5173",
        "type": "String",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1692028008326,
  "tid": "c75a48753ab911ee9a70760d0d3c40d3"
}
Status of device: bf31f56806358df1f1ayfd
{
  "result": [
    {
      "code": "switch_1",
      "value": false
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "add_ele",
      "value": 1
    },
    {
      "code": "cur_current",
      "value": 0
    },
    {
      "code": "cur_power",
      "value": 0
    },
    {
      "code": "cur_voltage",
      "value": 2313
    },
    {
      "code": "relay_status",
      "value": "power_off"
    },
    {
      "code": "overcharge_switch",
      "value": false
    },
    {
      "code": "light_mode",
      "value": "relay"
    },
    {
      "code": "child_lock",
      "value": false
    },
    {
      "code": "cycle_time",
      "value": ""
    },
    {
      "code": "random_time",
      "value": ""
    },
    {
      "code": "switch_inching",
      "value": ""
    }
  ],
  "success": true,
  "t": 1692028008683,
  "tid": "c78eeca83ab911eeb1a5226f85af9d81"
}

**Comment by Xenomes** [comment]
Hi,
There is no data for your device to work with..
```
Properties of device: bf0edd46cf895216b3syjv
{
"result": {
"category": "aqcz"
},
"success": true,
"t": 1692028007573,
"tid": "c6e15f993ab911eeb1a5226f85af9d81"
}
Status of device: bf0edd46cf895216b3syjv
{
"result": [],
"success": true,
"t": 1692028008010,
"tid": "c727a98b3ab911eeb1a5226f85af9d81"
}
```

There is a option on iot.tuya.com to switch from "Standard instruction" to "DP instruction" instruction.
login to  iot.tuya.com => Cloud => "Your Project" open project => Devices => Select device box => pensil => choose "DP instruction" => Save Configuration
Run Python script again and post the new JSON.

**Comment by Xenomes** [comment]
The ticket was closed because there was no response or reaction.
