### ISSUE TITLE
add Geya GTS8-W Tuya Wifi Smart Time Relay Schalter 4p 63a 80a

### ISSUE THREAD

**Issue by ilkaskim** [Xenomes/Domoticz-TinyTUYA-Plugin#54]
hello, can you please add "Geya GTS8-W Tuya Wifi Smart Time Relay Switch 4p 63a 80a" ??

  {
    "name": "compressor",
    "id": "bf9a5029b199866dfdc5si",
    "key": "Deleted",
    "mac": "a0:92:08:20:e2:3b",
    "uuid": "abda3fd3ad4c889c",
    "sn": "10007586300019",
    "category": "znjdq",
    "product_name": "WiFi intelligent switch",
    "product_id": "iiozidbohdb3ma6f",
    "biz_type": 18,
    "model": "GTS8-80 4P",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1538798448044S9dA7/869d9dd21b58dd6a647b11a7204d55f8.png"

Properties of device: bf9a5029b199866dfdc5si
{
  "result": {
    "category": "znjdq",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5012\u8ba1\u65f61",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "desc": "{\"range\":[\"off\",\"on\",\"memory\"]}",
        "name": "\u4e0a\u7535\u72b6\u6001\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"off\",\"on\",\"memory\"]}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "name": "\u5012\u8ba1\u65f61",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "name": "\u4e0a\u7535\u72b6\u6001\u8bbe\u7f6e",
        "type": "Enum",
        "values": "{\"range\":[\"off\",\"on\",\"memory\"]}"
      }
    ]
  },
  "success": true,
  "t": 1693148603796,
  "tid": "de4c592144ea11eeb3f09e6a0abc163a"
}
Status of device: bf9a5029b199866dfdc5si
{
  "result": [
    {
      "code": "switch_1",
      "value": false
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "relay_status",
      "value": "memory"
    }
  ],
  "success": true,
  "t": 1693148603923,
  "tid": "de5fc09144ea11eeaedc22e9039ff6e5"

**Comment by Xenomes** [comment]
Thanks for the Json data, i hope to have some time this weekend to added to the beta to test.

**Comment by ilkaskim** [comment]
Hello, I wanted to ask if you have already found some time to adjust it? 😊

**Comment by Xenomes** [comment]
Hi, yes, I have done some work on the plugin. With some luck, the new development version will be released this week.

**Comment by Xenomes** [comment]
Hi, the device is now included in the master, pull the new version 1.5.9.

**Comment by ilkaskim** [comment]
It works perfectly. Thank you for your effort 👍👍👍👍

**Comment by Xenomes** [comment]
Perfect!!!
