### ISSUE TITLE
New devices

### ISSUE THREAD

**Issue by aldodemi** [Xenomes/Domoticz-TinyTUYA-Plugin#56]
Three devices 
- Monitor LG studio
- Monitor Samsung Studio
- Smart Wireless Switch M4 
defined as "Unknown Device"

All those devices are zigbee coonected thru Zigbee Wireless Gateway

[dump.json.txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/12514786/dump.json.txt)

**Comment by Xenomes** [comment]
Thank for the json data, i am curently addind devices to the plugin i will add these to.

**Comment by Xenomes** [comment]
Hi, can you check out the Develop version and test the plugin with your device?
```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service
```
To revert to the Master, change Develop to Master

**Comment by Xenomes** [comment]
The ticket was closed because there was no response or reaction.
