### ISSUE TITLE
New device light sensor

### ISSUE THREAD

**Issue by countcobolt** [Xenomes/Domoticz-TinyTUYA-Plugin#57]
Just tried adding a light sensor (Lux + enum) to domoticz using tuya, but no joy :) 

See below the dump.json output.

List of devices: 
[
  {
    "name": "LightSensor",
    "id": "bfed54170d5bad79c6ja6n",
    "key": "Deleted",
    "mac": "a8:80:55:3c:9b:5c",
    "uuid": "850805e29798a97f",
    "sn": "100101129002DC",
    "category": "dgnbj",
    "product_name": "LightSensor",
    "product_id": "tgkr1bwom0jcn3cx",
    "biz_type": 18,
    "model": "XFY-CGQ-GZ",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1526384154502LQz2a/b7fd3d49a7728eb0b710fabc2e401ee5.jpg"
  }
]
Properties of device: bfed54170d5bad79c6ja6n
{
  "result": {
    "category": "dgnbj",
    "status": [
      {
        "code": "bright_state",
        "name": "\u4eae\u5ea6\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "bright_value",
        "name": "\u4eae\u5ea6\u503c",
        "type": "Integer",
        "values": "{\"unit\":\"LUX\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1694709074020,
  "tid": "1f04dbeb531c11ee9a70760d0d3c40d3"
}
Status of device: bfed54170d5bad79c6ja6n
{
  "result": [
    {
      "code": "bright_state",
      "value": "high"
    },
    {
      "code": "bright_value",
      "value": 526
    }
  ],
  "success": true,
  "t": 1694709074167,
  "tid": "1f1ef3cf531c11eeb3f09e6a0abc163a"

**Comment by countcobolt** [comment]
Just made a quick and dirty patch and got it working

`diff --git a/plugin.py b/plugin.py
index 280e095..2dc4e2b 100644
--- a/plugin.py
+++ b/plugin.py
@@ -888,6 +888,11 @@ def onHandleThread(startup):
                         Domoticz.Log('Create device water leak sesor')
                         Domoticz.Unit(Name=dev['name'], DeviceID=dev['id'], Unit=1, Type=244, Subtype=73, Switchtype=11, Used=1).Create()
 
+                if dev_type == 'lightsensor':
+                    if createDevice(dev['id'], 1):
+                        Domoticz.Log('Create device light sensor')
+                        Domoticz.Unit(Name=dev['name'], DeviceID=dev['id'], Unit=1, Type=246, Subtype=1, Switchtype=11, Used=1).Create()
+
                 if dev_type == 'presence':
                     if createDevice(dev['id'], 1):
                         Domoticz.Log('Create device PIR sensor')
@@ -1613,6 +1618,15 @@ def onHandleThread(startup):
                                     Devices[dev['id']].Units[unit].BatteryLevel = currentbattery
                                     Devices[dev['id']].Units[unit].Update()
 
+                    if dev_type == 'lightsensor':
+                        Domoticz.Log('it is a light sensor Jim')
+                        Domoticz.Log(str(ResultValue))
+                        if searchCode('bright_value', ResultValue):
+#def UpdateDevice(ID, Unit, sValue, nValue, TimedOut, AlwaysUpdate = 0):
+                            Domoticz.Log('in update for lightsensor')
+                            currentbright= StatusDeviceTuya('bright_value')
+                            UpdateDevice(dev['id'], 1, str(currentbright),100, 0)
+
                     if dev_type == 'presence':
                         if searchCode('watersensor_state', ResultValue):
                             currentstatus = StatusDeviceTuya('watersensor_state')
@@ -1753,6 +1767,8 @@ def DeviceType(category):
         result = 'presence'
     elif category in {'sfkzq'}:
         result = 'irrigation'
+    elif category in {'dgnbj'}:
+        result = 'lightsensor'
     # elif 'infrared_' in category: # keep it last
     #     result = 'infrared_id'
     else:
@@ -2032,4 +2048,4 @@ def setConfigItem(Key=None, Value=None):
     return Config
 
 def version(v):
-    return tuple(map(int, (v.split("."))))
\ No newline at end of file
+    return tuple(map(int, (v.split("."))))`

**Comment by countcobolt** [comment]
Just made a quick and dirty patch

```
diff --git a/plugin.py b/plugin.py
index 280e095..2dc4e2b 100644
--- a/plugin.py
+++ b/plugin.py
@@ -888,6 +888,11 @@ def onHandleThread(startup):
                         Domoticz.Log('Create device water leak sesor')
                         Domoticz.Unit(Name=dev['name'], DeviceID=dev['id'], Unit=1, Type=244, Subtype=73, Switchtype=11, Used=1).Create()
 
+                if dev_type == 'lightsensor':
+                    if createDevice(dev['id'], 1):
+                        Domoticz.Log('Create device light sensor')
+                        Domoticz.Unit(Name=dev['name'], DeviceID=dev['id'], Unit=1, Type=246, Subtype=1, Switchtype=11, Used=1).Create()
+
                 if dev_type == 'presence':
                     if createDevice(dev['id'], 1):
                         Domoticz.Log('Create device PIR sensor')
@@ -1613,6 +1618,15 @@ def onHandleThread(startup):
                                     Devices[dev['id']].Units[unit].BatteryLevel = currentbattery
                                     Devices[dev['id']].Units[unit].Update()
 
+                    if dev_type == 'lightsensor':
+                        Domoticz.Log('it is a light sensor Jim')
+                        Domoticz.Log(str(ResultValue))
+                        if searchCode('bright_value', ResultValue):
+#def UpdateDevice(ID, Unit, sValue, nValue, TimedOut, AlwaysUpdate = 0):
+                            Domoticz.Log('in update for lightsensor')
+                            currentbright= StatusDeviceTuya('bright_value')
+                            UpdateDevice(dev['id'], 1, str(currentbright),100, 0)
+
                     if dev_type == 'presence':
                         if searchCode('watersensor_state', ResultValue):
                             currentstatus = StatusDeviceTuya('watersensor_state')
@@ -1753,6 +1767,8 @@ def DeviceType(category):
         result = 'presence'
     elif category in {'sfkzq'}:
         result = 'irrigation'
+    elif category in {'dgnbj'}:
+        result = 'lightsensor'
     # elif 'infrared_' in category: # keep it last
     #     result = 'infrared_id'
     else:
@@ -2032,4 +2048,4 @@ def setConfigItem(Key=None, Value=None):
     return Config
 
 def version(v):
-    return tuple(map(int, (v.split("."))))
\ No newline at end of file
+    return tuple(map(int, (v.split("."))))
```

**Comment by Xenomes** [comment]
Hi, thanks for your contribution! I've added the code to the development version and made a small change to the code:
`UpdateDevice(dev['id'], 1, str(currentbright),100, 0)`
to
`UpdateDevice(dev['id'], 1, float(currentbright),1, 0)`
I don't know what the 100 do 😅

**Comment by countcobolt** [comment]
hey, well the 100 was from testing, so indeed that should not be in there :) I'll update the str to float in my local :)
