### ISSUE TITLE
Add PJ2101A 1P WiFi Smart Meter (If possible)

### ISSUE THREAD

**Issue by Nonoose** [Xenomes/Domoticz-TinyTUYA-Plugin#58]
Hello,
I've read the dump, and I think it will be very difficult whith values it sends, but if it's possible, can you add the "PJ2101A 1P WiFi Smart Meter", an Amperometric bidirectionnal sensor.
Here is the dump :
[dump.json.txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/12641518/dump.json.txt)
Thanks a lot for all your work and your support,
Regards,
Nonoose

**Comment by Xenomes** [comment]
Hi Thanks for the Dump. Your device is added to the Develop.
```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service
```

To revert to the Master, change Develop to Master

**Comment by Nonoose** [comment]
It works like a charm, thanks a lot from France ;)

**Comment by Xenomes** [comment]
Perfect! I will add it to the master.

**Comment by Nonoose** [comment]
Sorry to reopen the case, I don't know if it's in your hands, but when I send electricity to the Grid, it's shown as electricity consumed from the grid.
On the app, I see the correct current way by looking at the last digit of the live current value (1 for production, 0 for consumption)
Is there a way to program this on the plugin ?

**Comment by Xenomes** [comment]
Can you send a visual of what you see and create a new 'dump.json' when it's producing? I need only the value of phase_a.
```
    {
      "code": "phase_a",
      "value": "CNwAIbYAB3k="
    }
```

**Comment by Nonoose** [comment]
Hello,
Sorry for my late answer, it was not very sunny last days :)
Here is the value when I produce :
```
 {
      "code": "phase_a",
      "value": "CQ0AA10AAHM="
    }
```
Hope it will help you

**Comment by Xenomes** [comment]
No problem, thanks for the value.

**Comment by Nonoose** [comment]
Hello,
I've made 2 printscreens of the Tuya app :
![Screenshot_20230923_163630_Tuya Smart](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/145229296/a6ec3244-0a2a-4654-bc2f-2af665a3d70f)
![Screenshot_20230927_145128_Tuya Smart](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/145229296/23c4588a-731d-4843-99c1-7e4398ade12f)
The one where "Current" ends by 1 is when I produce (last digit is always 1)
The one where it ends by 0 is when I consume (always ends with 0)
Hope it may help you.
Regards

**Comment by Xenomes** [comment]
That is a strange way of showing a negative value. I will try to make that for this device only.

**Comment by Xenomes** [comment]
Can you checkout the develop version.

**Comment by Nonoose** [comment]
Done,
I need to wait until the next day for sun, but I think it's inverted, as it shows me now, when I'm consuming power (0 at the end) : 
![image](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/145229296/30e5ef90-b05a-4690-93e8-39240aa3c914)
Tell me if I can do anything to help you,
Regards

**Comment by Xenomes** [comment]
Oeps, You are correct i turn it around in the code. You can pull a new one.

**Comment by Xenomes** [comment]
Added to the Master!

**Comment by Nonoose** [comment]
Everything is fine, thanks for everything
