### ISSUE TITLE
kWh isn't working, doesn't  update

### ISSUE THREAD

**Issue by varazir** [Xenomes/Domoticz-TinyTUYA-Plugin#6]
I have updated to 1.3.2 and the kWh showed up in domoticz. But it's not updating. 

I checked the app and it shows kWh.

**Comment by Xenomes** [comment]
is the normal Watt updating?

**Comment by varazir** [comment]
Yes

**Comment by varazir** [comment]
![Screenshot_20230105-210217](https://user-images.githubusercontent.com/262588/210869865-9560fde4-f839-44e7-8063-1e77cecb58ce.png)

**Comment by varazir** [comment]
![Uploading Screenshot_20230105-210140.png…]()

**Comment by varazir** [comment]
I'll add more later

**Comment by Xenomes** [comment]
> ![Screenshot_20230105-210217](https://user-images.githubusercontent.com/262588/210869865-9560fde4-f839-44e7-8063-1e77cecb58ce.png)

Is that a screenshot from the tuya based app?

**Comment by varazir** [comment]
From the smart life app. 

This from domoticz

![Screenshot_20230105-210140](https://user-images.githubusercontent.com/262588/210871152-14df1292-39f1-4695-a2a3-00ddb7092ebf.png)

**Comment by Xenomes** [comment]
The Kwh are not in the json of tuya, so i do calculate it if the watt is used. I don't own a switch with power meter i can only simulate. Is there power used from the switch right now? if so then i need a json dump of the device, you can create it with debug_discovery.py edit and run it with Python3.

**Comment by varazir** [comment]
Here it is. 



List of devices:
 [
  {
    "name": "Cleverio Wifi Outdoor Plug",
    "id": "",
    "key": "Deleted",
    "mac": "cc:8c:bf:b4:97:6d",
    "category": "cz",
    "product_name": "Cleverio Wifi Outdoor Plug",
    "product_id": "urnwekrjm4ulygw1",
    "biz_type": 18,
    "model": "51420 / Kangtai",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/bay1642483789914MMff/1652422484d4f29a97472.png",
    "uuid": "8499752007cda8fc"
  },
  {
    "name": "Cleverio AF-F100",
    "id": "43035720e098061d58bc",
    "key": "Deleted",
    "mac": "e0:98:06:1d:58:bc",
    "category": "fs",
    "product_name": "Cleverio AF-F100 ",
    "product_id": "jaefoofl9as5kevm",
    "biz_type": 18,
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1541396207188PFb5m/a0d244e9debd4e0f9a865980bacc2bbd.png",
    "uuid": "43035720e098061d58bc"
  }
]

Functions of device: bfd6bda7f3a84e2064d97h
 {
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "desc": "switch 1",
        "name": "switch 1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "countdown 1",
        "name": "countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "desc": "relay status",
        "name": "relay status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "cycle_time",
        "desc": "cycle time",
        "name": "cycle time",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "desc": "random time",
        "name": "random time",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "desc": "switch inching",
        "name": "switch inching",
        "type": "String",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1672919960111,
  "tid": "6314ffa58cf011edbdcf768159807b40"
}

Status of device: bfd6bda7f3a84e2064d97h
 {
  "result": [
    {
      "code": "switch_1",
      "value": true
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "add_ele",
      "value": 146
    },
    {
      "code": "cur_current",
      "value": 644
    },
    {
      "code": "cur_power",
      "value": 913
    },
    {
      "code": "cur_voltage",
      "value": 2384
    },
    {
      "code": "relay_status",
      "value": "power_off"
    },
    {
      "code": "cycle_time",
      "value": ""
    },
    {
      "code": "random_time",
      "value": ""
    },
    {
      "code": "switch_inching",
      "value": ""
    }
  ],
  "success": true,
  "t": 1672919960334,
  "tid": "6338ee9a8cf011ed817f5a5f1d3b12c7"
}

Functions of device: 43035720e098061d58bc
 {
  "result": {
    "category": "fs",
    "functions": [
      {
        "code": "switch",
        "desc": "switch",
        "name": "switch",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1672919960572,
  "tid": "635ae4b08cf011ed817f5a5f1d3b12c7"
}

Status of device: 43035720e098061d58bc
 {
  "result": [
    {
      "code": "switch",
      "value": false
    }
  ],
  "success": true,
  "t": 1672919960789,
  "tid": "637e79a48cf011ed817f5a5f1d3b12c7"
}

**Comment by Xenomes** [comment]
Problem found! I did a round to no decimals but for lower values there is then no update.
Pull the new version.

**Comment by varazir** [comment]
I'll try and report back when I have tested it.

**Comment by Xenomes** [comment]
Yep perfect!

**Comment by varazir** [comment]
> Yep perfect!

It's working thanks for the help.

**Comment by Xenomes** [comment]
Thanks for testing!

**Comment by varazir** [comment]
> Thanks for testing!

I got this, strange 

![image](https://user-images.githubusercontent.com/262588/211196190-ebcdac68-eaa8-49fa-b212-5f8d7a820387.png)

**Comment by Xenomes** [comment]
That's not good ... I will change the calculation.

**Comment by varazir** [comment]
> That's not good ... I will change the calculation.

Strange is it that it was positive then just went negativt.

**Comment by Xenomes** [comment]
how does the cvs download looks like?

**Comment by varazir** [comment]
When I'm looking it at now it's empty, 



Found this how to change it https://www.domoticz.com/forum/viewtopic.php?t=39070 next time it happens.

**Comment by Xenomes** [comment]
I think i found the problem. Can you pull the plugin i didn't change the release number.

**Comment by varazir** [comment]
when I restarted I get this 

```
2023-01-09 22:40:54.578 Error: Zigbee2MQTT: Failed to start, return code: 14/Connection refused (Check IP/Port)
2023-01-09 22:40:56.360 Error: TinyTUYA: handleThread: HTTPSConnectionPool(host='openapi.tuyaeu.com', port=443): Max retries exceeded with url: /v1.0/token?grant_type=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x69450d10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-01-09 22:41:53.070 Error: TinyTUYA: handleThread: name 'devs' is not defined
2023-01-09 22:42:53.074 Error: TinyTUYA: handleThread: name 'devs' is not defined
2023-01-09 22:43:53.083 Error: TinyTUYA: handleThread: name 'devs' is not defined
2023-01-09 22:44:53.071 Error: TinyTUYA: handleThread: name 'devs' is not defined
```

**Comment by varazir** [comment]
I'll try to pull new

**Comment by varazir** [comment]
Pulled new git and restarted domoticz, no errors I'll report back when I have done some tests.

**Comment by Xenomes** [comment]
How are the tests goings?

**Comment by varazir** [comment]
> How are the tests goings?

I haven't hade the need to laundry, but it's Sunday so it's  laundry day. 
I'll get back to you later today. So far it looks good 
![image](https://user-images.githubusercontent.com/262588/212532120-dfd351f6-a67e-491a-a2b1-55d217d12eb6.png)

**Comment by Xenomes** [comment]
Nice! I will close the issue. please reopen if there is a problem.
