### ISSUE TITLE
Please add (if possible) zigbee Smart Siren

### ISSUE THREAD

**Issue by octavianrusu** [Xenomes/Domoticz-TinyTUYA-Plugin#60]
I have two devices not seen in domoticz but it is my interest for the siren.
Thank you!

[dump.json.txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/12712952/dump.json.txt)

**Comment by Xenomes** [comment]
Hi octavianrusu,
The data looks good to add to the plugin.

**Comment by octavianrusu** [comment]
Hi,
if I can help I will do it.
Thank you!
Octavian

**Comment by Xenomes** [comment]
Hi octavianrusu,
could you please check out the development version and test the plugin with your device?

```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service

```
To switch back to the Master version, change 'Develop' to 'Master'.

**Comment by octavianrusu** [comment]
Thank you very much, it's working great. Three new device are added: Muffling, State and Volume. 
Thnk you again Xenomes!

**Comment by Xenomes** [comment]
Perfect! Thanks for the feedback. I will close the ticket. If there is an issue, you can reopen it.
