### ISSUE TITLE
Temperature electric quantity controller is not recognized

### ISSUE THREAD

**Issue by macb3** [Xenomes/Domoticz-TinyTUYA-Plugin#61]
Hello,
 The device  with name": "Temp control boiler",    "id": "bfbcc2890ef8186c28zo9j", is not recognized
Perhaps this can be fixed?  
Thanks for sharing this project.

[dump. json.txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/12724454/dump.json.txt)

**Comment by Xenomes** [comment]
Thanks for the code, it looks good 80% is already in the plugin need some tweaks to adjust.

**Comment by Xenomes** [comment]
Hi macb3,
could you please check out the development version and test the plugin with your device?

```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service

```
To switch back to the Master version, change 'Develop' to 'Master'.

**Comment by macb3** [comment]
[Hi](url) Xenomes, 
The test is successful, everything works.
I think this device can be added to the Master.
Thanks a lot.


![temp_control_TintyTuya_](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/146028426/c6176b8b-3c7f-4964-a99b-897517723bb0)

**Comment by Xenomes** [comment]
Thanks for the feedback. I will add it to the Master and close the ticket. If there is an issue, you can reopen it.
