### ISSUE TITLE
Add TYTE-D1 temperature smart switch

### ISSUE THREAD

**Issue by Nonoose** [Xenomes/Domoticz-TinyTUYA-Plugin#62]
Hello,
It's me again :D 
I've connected a Temperature smart switch, here is the JSON for the device :
Thnaks again for your valuable work
Regards,
Jean-Noël

[dump.json.txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/12736548/dump.json.txt)

**Comment by Xenomes** [comment]
Thanks for the code. Nice that your request is almost the same as #61, so I can program them together.

**Comment by Xenomes** [comment]
Hi Nonoose,
could you please check out the development version and test the plugin with your device?

```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service

```
To switch back to the Master version, change 'Develop' to 'Master'.

**Comment by Nonoose** [comment]
Hello,
Works like a charm, thanks a lot.

**Comment by Xenomes** [comment]
Perfect! Thanks for the feedback. I will close the ticket. If there is an issue, you can reopen it.
