### ISSUE TITLE
Error when starting TinyTUYA 1.6.3

### ISSUE THREAD

**Issue by Vitus-TL** [Xenomes/Domoticz-TinyTUYA-Plugin#64]
NameError: name 'last_update' is not defined
Call to function 'onHeartbeat' failed,

**Comment by Xenomes** [comment]
That is strange. The last_update is defined at startup. Is there any other error when the plugin is started? You can trigger the plugin to restart by selecting the plugin on the hardware page and clicking 'Update'."

**Comment by Xenomes** [comment]
The ticket was closed because there was no response or reaction.
