### ISSUE TITLE
Add Cronos OL20-BD068B Dehumidifier

### ISSUE THREAD

**Issue by dk64ty** [Xenomes/Domoticz-TinyTUYA-Plugin#65]
Hello,

I followed domoticz logs, and run debug_discovery tool. Here is the part of output:
[dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13191093/dump.json)

The most important for me are humidity and temperature readings and optional switch on/off functionality.

Thank you for the work you do

Regards,

**Comment by Xenomes** [comment]
Hi dk64ty,
could you please check out the development version and test the plugin with your device?

```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service

```
To switch back to the Master version, change 'Develop' to 'Master'.

**Comment by dk64ty** [comment]
It looks that everything works perfect - it is more than I want.  Thank you once again.
![image](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/149186831/4f9aff79-9831-486f-b98c-c36a19559912)

**Comment by Xenomes** [comment]
Perfect, I will close the issue and update the master.
