### ISSUE TITLE
New device WIFI Dual Meter1 not detected

### ISSUE THREAD

**Issue by moipopples** [Xenomes/Domoticz-TinyTUYA-Plugin#66]
Hello thanks for your job.
It is a Tuya Wifi Intelligent Energy Meter Solar PV System Power Production Consumption Bidirectional Monitoring Meter APP Control CT from Aliexpress
https://www.aliexpress.com/item/1005005861460301.html?spm=a2g0o.order_list.order_list_main.104.32bb5e5bqPqoD3

From https://eu.iot.tuya.com
WIFI Dual Meter1	bf89b6f44e6cb10a3apnne	WIFI Dual Meter

from debug_discovery.py
Properties of device:
{
"result": {
"category": "zndb",
"functions": [
{
"code": "forward_energy_total",
"desc": "{"unit":"KWH","min":0,"max":99999999,"scale":2,"step":1}",
"name": "\u6b63\u5411\u603b\u6709\u529f\u7535\u91cf",
"type": "Integer",
"values": "{"unit":"KWH","min":0,"max":99999999,"scale":2,"step":1}"
},
{
"code": "reverse_energy_total",
"desc": "{"unit":"KWH","min":0,"max":99999999,"scale":2,"step":1}",
"name": "\u53cd\u5411\u603b\u6709\u529f\u7535\u91cf",
"type": "Integer",
"values": "{"unit":"KWH","min":0,"max":99999999,"scale":2,"step":1}"
}
],
"status": [
{
"code": "forward_energy_total",
"name": "\u6b63\u5411\u603b\u6709\u529f\u7535\u91cf",
"type": "Integer",
"values": "{"unit":"KWH","min":0,"max":99999999,"scale":2,"step":1}"
},
{
"code": "reverse_energy_total",
"name": "\u53cd\u5411\u603b\u6709\u529f\u7535\u91cf",
"type": "Integer",
"values": "{"unit":"KWH","min":0,"max":99999999,"scale":2,"step":1}"
},
{
"code": "total_power",
"name": "\u603b\u529f\u7387",
"type": "Integer",
"values": "{"unit":"W","min":-99999999,"max":99999999,"scale":1,"step":1}"
}
]
},
"success": true,
"t": 1700242349338,
"tid": "4821b0d1856f11eea84192c59b34336d"
}

Status of device:
{
"result": [
{
"code": "forward_energy_total",
"value": 0
},
{
"code": "reverse_energy_total",
"value": 0
},
{
"code": "total_power",
"value": 0
}
],
"success": true,
"t": 1700242349517,
"tid": "483be546856f11eea84192c59b34336d"
}

**Comment by moipopples** [comment]
i have changed somthing on https://eu.iot.tuya.com/ now i have a lot of measurement
WIFI Dual Meter1 bf89b6f44e6cb10a3apnne WIFI Dual Meter

from debug_discovery.py


Properties of device: bf89b6f44e6cb10a3apnne
 {
  "result": {
    "category": "zndb",
    "functions": [
      {
        "code": "forward_energy_total",
        "desc": "{\"unit\":\"KWH\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}",
        "name": "\u6b63\u5411\u603b\u6709\u529f\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"KWH\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "reverse_energy_total",
        "desc": "{\"unit\":\"KWH\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}",
        "name": "\u53cd\u5411\u603b\u6709\u529f\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"KWH\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "voltage_coef",
        "desc": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}",
        "name": "voltage_calibration",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "current_a_calibration",
        "desc": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}",
        "name": "current_a_calibration",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "power_a_calibration",
        "desc": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}",
        "name": "power_a_calibration",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "energy_a_calibration_fwd",
        "desc": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}",
        "name": "energy_a_calibration_fwd",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "coef_a_reset",
        "desc": "{}",
        "name": "coef_a_reset",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "freq_calibration",
        "desc": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}",
        "name": "\u9891\u7387\u6821\u51c6",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "current_b_calibration",
        "desc": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}",
        "name": "current_b_calibration",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "power_b_calibration",
        "desc": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}",
        "name": "power_b_calibration",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "energy_b_calibration_fwd",
        "desc": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}",
        "name": "energy_b_calibration_fwd",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "coef_b_reset",
        "desc": "{}",
        "name": "coef_b_reset",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "energy_a_calibration_rev",
        "desc": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}",
        "name": "energy_a_calibration_rev",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "energy_b_calibration_rev",
        "desc": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}",
        "name": "energy_b_calibration_rev",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "report_rate_control",
        "desc": "{\"unit\":\"s\",\"min\":3,\"max\":60,\"scale\":0,\"step\":1}",
        "name": "report_rate_control",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":3,\"max\":60,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "forward_energy_total",
        "name": "\u6b63\u5411\u603b\u6709\u529f\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"KWH\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "reverse_energy_total",
        "name": "\u53cd\u5411\u603b\u6709\u529f\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"KWH\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "power_a",
        "name": "Power_a",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":600000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "direction_a",
        "name": "Current_Flow_A",
        "type": "Enum",
        "values": "{\"range\":[\"FORWARD\",\"REVERSE\"]}"
      },
      {
        "code": "tbd",
        "name": "TBD",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "direction_b",
        "name": "Current_FLow_B",
        "type": "Enum",
        "values": "{\"range\":[\"FORWARD\",\"REVERSE\"]}"
      },
      {
        "code": "power_b",
        "name": "Power_b",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":600000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "energy_forword_a",
        "name": "Forward_Energy_A",
        "type": "Integer",
        "values": "{\"unit\":\"KWH\",\"min\":0,\"max\":999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "energy_reverse_a",
        "name": "Reverse_Energy_A",
        "type": "Integer",
        "values": "{\"unit\":\"KWH\",\"min\":0,\"max\":999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "energy_forword_b",
        "name": "Forward_Energy_B",
        "type": "Integer",
        "values": "{\"unit\":\"KWH\",\"min\":0,\"max\":999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "energy_reserse_b",
        "name": "energy_reserse_b",
        "type": "Integer",
        "values": "{\"unit\":\"KWH\",\"min\":0,\"max\":999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "power_factor",
        "name": "Power_factor_A",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":2,\"step\":1}"
      },
      {
        "code": "freq",
        "name": "AC_Freq",
        "type": "Integer",
        "values": "{\"unit\":\"Hz\",\"min\":0,\"max\":10000,\"scale\":2,\"step\":1}"
      },
      {
        "code": "voltage_a",
        "name": "Voltage",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":28000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "current_a",
        "name": "Current_A",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "current_b",
        "name": "Current_B",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "total_power",
        "name": "Total_Power",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":-99999999,\"max\":99999999,\"scale\":1,\"step\":1}"
      },
      {
        "code": "voltage_coef",
        "name": "voltage_calibration",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "current_a_calibration",
        "name": "current_a_calibration",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "power_a_calibration",
        "name": "power_a_calibration",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "energy_a_calibration_fwd",
        "name": "energy_a_calibration_fwd",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "power_factor_b",
        "name": "Power_factor_B",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":2,\"step\":1}"
      },
      {
        "code": "freq_calibration",
        "name": "\u9891\u7387\u6821\u51c6",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "current_b_calibration",
        "name": "current_b_calibration",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "power_b_calibration",
        "name": "power_b_calibration",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "energy_b_calibration_fwd",
        "name": "energy_b_calibration_fwd",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "energy_a_calibration_rev",
        "name": "energy_a_calibration_rev",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "energy_b_calibration_rev",
        "name": "energy_b_calibration_rev",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":800,\"max\":1200,\"scale\":3,\"step\":1}"
      },
      {
        "code": "report_rate_control",
        "name": "report_rate_control",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":3,\"max\":60,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1700246791876,
  "tid": "a016ff29857911ee943acee4996e2853"
}

Status of device: bf89b6f44e6cb10a3apnne
 {
  "result": [
    {
      "code": "forward_energy_total",
      "value": 16
    },
    {
      "code": "reverse_energy_total",
      "value": 2
    },
    {
      "code": "power_a",
      "value": 6163
    },
    {
      "code": "direction_a",
      "value": "FORWARD"
    },
    {
      "code": "tbd",
      "value": false
    },
    {
      "code": "direction_b",
      "value": "FORWARD"
    },
    {
      "code": "power_b",
      "value": 635
    },
    {
      "code": "energy_forword_a",
      "value": 16
    },
    {
      "code": "energy_reverse_a",
      "value": 0
    },
    {
      "code": "energy_forword_b",
      "value": 0
    },
    {
      "code": "energy_reserse_b",
      "value": 2
    },
    {
      "code": "power_factor",
      "value": 78
    },
    {
      "code": "freq",
      "value": 4931
    },
    {
      "code": "voltage_a",
      "value": 2362
    },
    {
      "code": "current_a",
      "value": 3332
    },
    {
      "code": "current_b",
      "value": 1229
    },
    {
      "code": "total_power",
      "value": 6798
    },
    {
      "code": "voltage_coef",
      "value": 1000
    },
    {
      "code": "current_a_calibration",
      "value": 1000
    },
    {
      "code": "power_a_calibration",
      "value": 1000
    },
    {
      "code": "energy_a_calibration_fwd",
      "value": 1000
    },
    {
      "code": "power_factor_b",
      "value": 21
    },
    {
      "code": "freq_calibration",
      "value": 1000
    },
    {
      "code": "current_b_calibration",
      "value": 1000
    },
    {
      "code": "power_b_calibration",
      "value": 1000
    },
    {
      "code": "energy_b_calibration_fwd",
      "value": 1000
    },
    {
      "code": "energy_a_calibration_rev",
      "value": 1000
    },
    {
      "code": "energy_b_calibration_rev",
      "value": 1000
    },
    {
      "code": "report_rate_control",
      "value": 10
    }
  ],
  "success": true,
  "t": 1700246792042,
  "tid": "a03164b5857911ee943acee4996e2853"
}

**Comment by Xenomes** [comment]
Thank you for the JSON data, what quick see no problems to in create the device. Maybe i have some time this weekend i will added to de plugin.

**Comment by moipopples** [comment]
ok thanks i

**Comment by Xenomes** [comment]
Hi moipopples,

Could you please check out the 'new_device' version and test the plugin with your device? There will be 13 devices. If you have any recommendations, please let me know.

```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout new_device
sudo systemctl restart domoticz.service

```
To switch back to the Master version, change 'new_device' to 'Master'.

**Comment by moipopples** [comment]
hello thanks and great job,
there just little problem with units.
i try to put a picture
![image](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/63144274/7947cfc5-f3c1-465d-be81-44ed6286dc2a)

**Comment by moipopples** [comment]
4 units are in kWh but prompted as Watt.
it is not instantaneous consumption, it is an accumulation of kWh consumed.
I have also forget, the total is also in kWh

![image](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/63144274/696a2286-1bed-4b2d-a9f7-422861ad6b16)

**Comment by Xenomes** [comment]
Ha yes i see, i will change that. This four are total devices i missed that.

**Comment by moipopples** [comment]
> Ha yes i see, i will change that. This four are total devices i missed that.
5 there is also the total!
no problem great job !

**Comment by Xenomes** [comment]
I've uploaded a new version. Could you please check it out? Before reloading the plugin, you'll need to delete the 13 devices so that they can be recreated.

**Comment by moipopples** [comment]
Hello all seem to be ok for me, i have the same measurement with Domoticz and the smart app.
Thanks

**Comment by Xenomes** [comment]
Perfect! I will close the issue, if there is a problem you can reopen it!
