### ISSUE TITLE
Air quality detector

### ISSUE THREAD

**Issue by ipolo0000i** [Xenomes/Domoticz-TinyTUYA-Plugin#67]
Hey,
I think is new device. An air quality detector : 
[dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13481880/dump.json)

Thank you!

**Comment by Xenomes** [comment]
Hi,
Thank you for the JSON; this is useful! I will try adding it this weekend.

**Comment by Xenomes** [comment]
Hi, I added the device to de Develop branch, can you test it?
```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service
```

**Comment by ipolo0000i** [comment]
Hi,
It's work perfect!
There's just small issue, the carbon monoxide level isn't rising in TinyTUYA whereas i have it in the application and on the Tuya cloud service.
I will check it with the TinyTUYA project.

**Comment by Xenomes** [comment]
Hi, can you make a new JSON file, I don't see a error in the code, so it must be in the data.

**Comment by Xenomes** [comment]
The ticket was closed because there was no response or reaction.
