### ISSUE TITLE
Air Purifier

### ISSUE THREAD

**Issue by brydziu** [Xenomes/Domoticz-TinyTUYA-Plugin#69]
Hello,
I have new air purifier  Orllo T2.
Here is dump file.
[dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13504028/dump.json)

**Comment by Xenomes** [comment]
Thanks! Your json is complete different then the other one i got.  Thing i try to add it to the code this weekend.

**Comment by Xenomes** [comment]
Hi brydziu,
I added the device to de Develop branch, can you test it?

```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service
```

**Comment by brydziu** [comment]
Hi,
Everything looks great. Everything works except the fan speed switch. The data shown is correct (pm 2.5.) Thank you very much!

**Comment by Xenomes** [comment]
Perfect, good to hear!

**Comment by Xenomes** [comment]
Hi,
I was testing the 'fan speed switch' according to the data I received, and everything seems correct. Could you please explain what is not working so that we can debug it together and find a solution?

**Comment by Xenomes** [comment]
The ticket was closed because there was no response or reaction.
