### ISSUE TITLE
Delay for update status

### ISSUE THREAD

**Issue by dudusandi** [Xenomes/Domoticz-TinyTUYA-Plugin#7]
I can change de delay ? When  using homeassistant delay is 3seconds and I'm using tuya button to trigger another led devices.. But with domoticz with your plugin the delay is about 40seconds.. Even that nice work!!

**Comment by Xenomes** [comment]
To reduce the number of API calls, the plugin will check if there are changes ever 60 seconds.

You can change on you own risk to run out of API calls per month the following:

`Domoticz.Heartbeat(10)` to `Domoticz.Heartbeat(5)`
and
`if time.time() - last_update < 60 and testData == False:` to `if time.time() - last_update < 5 and testData == False:`

**Comment by pfolcato** [comment]
Hi Xenomes!
thanks for your great work!
I have an error in this function, in "onHeartbeat(self)":
"name 'last_update' is not defined"
I'm not a python programmer so I hope you fix my problem :)
.... Sorry... now I have understand the problem......
My subscription to cloud development plan has expired....

**Comment by Xenomes** [comment]
Happy that you found the problem.
