### ISSUE TITLE
Only 1/2 devices recognized

### ISSUE THREAD

**Issue by Biggood40** [Xenomes/Domoticz-TinyTUYA-Plugin#72]
Domoticz return for the wifi dual meter : "This device is not reconised, edit and run the debug_discovery with python from the tools directory ..."
I run debug and I see the 2 devices
[dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13558256/dump.json)

**Comment by Xenomes** [comment]
Hi, Can you pull the latest version. move the device code to power meter and second set your devices to 'DP instruction' in the device settings under iot.tuya.com account. For exact instructions see the PDF in the readme.

**Comment by Biggood40** [comment]
Thank you, it works fine

**Comment by Xenomes** [comment]
Great then is close the issue, I have updated the readme to change to 'DP instruction'.
