### ISSUE TITLE
Add Tongou wifi circuit breaker (DIN rail switch)

### ISSUE THREAD

**Issue by Sigloysien** [Xenomes/Domoticz-TinyTUYA-Plugin#74]
Hello Xenomes

Thank you so much for the work on Tuya integration into DomoticZ!
This circuit breaker (DIN rail) is not recognized by tinytua. 
Product available on : https://www.amazon.fr/dp/B0B7N1XQ9P?psc=1&ref=ppx_yo2ov_dt_b_product_details
Manufacturer details: https://fr.elcb.net/Les-produits/to-q-sy1-jwt-commutateur-wifi-intelligent-sur-rail-din-avec-fonction-de-mesure/

Attached is the json of the debug catch:
[dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13653951/dump.json)

The non recognized items are iD **bf37e1887d417c51d78wti** (online) and ID **bf3fee14eeb95447125dya** (offline, no wifi during winter there)

Thanks for any help you can bring to integrate these into next TinyTua plugin
Let me know if you need any details, trace of something, log, etc.

Patrick

**Comment by Xenomes** [comment]
Hi Patrick,

First, I want to ask if you put the devices in 'DP Instruction' mode? If not, could you do that and see if the devices are created in Domoticz?

**Comment by Sigloysien** [comment]
Hi Xenomes
No I did not do any extra steps before making the debug catch
I will look how this is done and see if they are created then.

**Comment by Sigloysien** [comment]
Well, it does the same thing. Create a Text Device with the text to create an issue here
![Capture d’écran 2023-12-14 à 20 38 40](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/153671360/5623b32b-0579-4e6d-a8a9-2d00ea23c614)
![Capture d’écran 2023-12-14 à 20 43 42](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/153671360/284e8ecf-4859-408c-b7d6-6f4c32097771)

**Comment by Xenomes** [comment]
OK, can you make a debug.json in the DP mode, than the readout is better.

**Comment by Sigloysien** [comment]
right, wll do maybe tonight, I need to go physically on the windows 7 PC that serves as server.

**Comment by Sigloysien** [comment]
Here is the json
[dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13678121/dump.json)

ID: bf37e1887d417c51d78wti
Hope it has gone to (famous now) DP mode.

Dank U !

**Comment by Xenomes** [comment]
Thanks, I try to add it this week.

**Comment by Xenomes** [comment]
Hi Sigloysien,
I added the device to de Develop branch, can you test it?

```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service
```

**Comment by Sigloysien** [comment]
Hi Xenomes

thank you! I'll try tonight. 
BTW I'm on windows, but I'm good with the instructions above. Just hope Git for Windows works just like the linux one.

**Comment by Xenomes** [comment]
Very good! Instruction are the same if you are in the correct directory.

**Comment by Sigloysien** [comment]
Hi Good evening
I uploaded and recreated the devices (had to it seems, as well as complete reboot of system as Python could not find "chardet", after reboot all ok on this side
It seems to be working fine, I could not test thouroughly tonight, but all devices came up. Thanks 

A few questions:
is it possible with tinytuya to not send our info to tuya server in China or anywhere ?
Should I leave the devices in DP mode or can I go back to standard?
Do you likeCoffe ?

thx Xenome, well appreciated!
Patrick

**Comment by Xenomes** [comment]
> Hi Good evening I uploaded and recreated the devices (had to it seems, as well as complete reboot of system as Python could not find "chardet", after reboot all ok on this side It seems to be working fine, I could not test thouroughly tonight, but all devices came up. Thanks

Okay, perfect. Keep me posted if there is a problem.
 
> A few questions: is it possible with tinytuya to not send our info to tuya server in China or anywhere ?

Yes and no. You need to connect to the server once to obtain the device key. Afterward, you can block internet access to the device at your router. I have a plugin available for offline control at https://github.com/Xenomes/Domoticz-TinyTUYA-Local-Plugin, but it currently supports only on/off functionality.
> Should I leave the devices in DP mode or can I go back to standard?

Using DP mode is the recommended approach with Tinytuya.
>Do you likeCoffe ?

Yes, a nice coffee, black 🤣

**Comment by Sigloysien** [comment]
Hi there !
Hope you had a great Christmas. No snow for you either I suppose. Damnglobal warming ! 

After a week, everything with my DIN rail wifi switches is running fine. Thank you for that!
And I ordered a couple of temp/humidity sensor from China, and they uploaded into Domoticz very easily today! So they were already implemented - great job 👍 !!!
Have a great New Year fiesta!
Drink some good wine. I'll buy you coffe for the 1st Jan Morning - you may need it then :-)

Patrick

**Comment by Xenomes** [comment]
Hi Sigloysien/Patrick,
Yes, indeed, no snow 😅 
Very good to hear that the plugin is running fine. I will merge it with the Master.
Thanks for the kind donation. 🙏
