### ISSUE TITLE
Support for Doorbell camera

### ISSUE THREAD

**Issue by DGA45** [Xenomes/Domoticz-TinyTUYA-Plugin#75]
Hi Xenomes,
I have an unrecognized device. Here is the dump file:
[dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13726430/dump.json)
Thanks a lot for your great job !

**Comment by Xenomes** [comment]
Hi DGA45,

First, I want to ask if you have put the devices in 'DP Instruction' mode. If not, could you do that and create a new dump.json? The value for the doorbell in your JSON is currently empty

**Comment by DGA45** [comment]
Hi,
Yes, the device is in "DP instruction" mode. Even in the device debugging tab from IoT Tuya cloud, the status remains grayed, like inactive:
![Debug IoT](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/59612603/991abe1d-2e46-49ed-b349-addf565776ce)

I wanted to get the notifications as the ones from the app: (someone knocks at the door, unlocking from indoor/outdoor, ...) and also to be able to unlock from Domoticz.

**Comment by Xenomes** [comment]
Ha, I see. Now, we need to detect the button press and movement. Maybe I can find something online.

**Comment by Xenomes** [comment]
Based on the pull request, this is too slow to get working. Maybe the https://github.com/Xenomes/Domoticz-TinyTUYA-Local-Plugin is able to get it working.

**Comment by Xenomes** [comment]
Hi, i have made a update to the plugin that may be resolves your issue. See https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/issues/154#issuecomment-2620041279
