### ISSUE TITLE
Heat pump not recognized

### ISSUE THREAD

**Issue by doucha2** [Xenomes/Domoticz-TinyTUYA-Plugin#76]
Hi, I would like to take some readings from a heat pump, inlet water temperature, outlet water temperature, unfortunately this device is not supported. I am sending complete dump.json file. It is a heat pump with ID "bf3ef1d62aceff6faeh6nk" other devices are working. If someone could give me a kick, I would like to try to modify it myself, but I don't know how to start.  Have a nice new year. 
[dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13801679/dump.json)

**Comment by Xenomes** [comment]
Hi, thanks for the JSON. I will check later this week to implement it in the code.
A good new year to you too!

**Comment by doucha2** [comment]
Hi Xenomes, so I managed to modify it for my use. It wasn't even that hard. Only for monitoring of 9 parameters.  I'm not familiar with github, what would be the correct way to send the code back to you? I also don't know if there would be anyone else here with a similar "znrb" product category device...

**Comment by Xenomes** [comment]
Hi, That is perfect, send the plugin.py to xenomes@outlook.com i will compare and merge the versions.

**Comment by Xenomes** [comment]
Thanks for the email, i updated the Develop branch.
