### ISSUE TITLE
add Pir Sensor

### ISSUE THREAD

**Issue by ilkaskim** [Xenomes/Domoticz-TinyTUYA-Plugin#77]
happy new year :)
Can you please adjust pir sensor. They are available in Domoticz but nothing happens when it is switched on. I can see all the movements in the Tuya app. Unfortunately nothing happens in Domoticz.

Thank you very much and happy holidays!!

https://de.aliexpress.com/item/1005004763848104.html?spm=a2g0o.order_list.order_list_main.5.135f5e5btU9Xd8&gatewayAdapt=glo2deu

    "name": "PIR motion sensor 2",
    "id": "bfb70dca57df3ce8a6guuh",
    "key": "Deleted",
    "mac": "",
    "category": "pir",
    "product_name": "PIR motion sensor",
    "product_id": "IDkXwcvanigdiTj3",
    "biz_type": 18,
    "model": "",
    "sub": true,
    "icon": "https://images.tuyaeu.com/smart/icon/1524817175gtuah13xg5xa305ri0wqxgvi_0.png",
    "uuid": "bfb70dca57df3ce8a6guuh",
    "node_id": "00124b00292b986a"
  },

Properties of device: bfb70dca57df3ce8a6guuh
{
  "result": {
    "category": "pir",
    "status": [
      {
        "code": "pir",
        "name": "pir \u68c0\u6d4b",
        "type": "Enum",
        "values": "{\"range\":[\"pir\",\"none\"]}"
      },
      {
        "code": "battery",
        "name": "\u7535\u6c60\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":500,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1704064561675,
  "tid": "9036b627a83211eebdfcfa79b8e3f4a5"
}
Status of device: bfb70dca57df3ce8a6guuh
{
  "result": [
    {
      "code": "pir",
      "value": "pir"
    },
    {
      "code": "battery",
      "value": 100
    }
  ],
  "success": true,
  "t": 1704064561944,
  "tid": "90534b59a83211eebdfcfa79b8e3f4a5"
}

**Comment by Xenomes** [comment]
Hi, I see the problem. I have updated the master with a quick fix. Keep in mind that the tinytuya module is a pull service, and it checks once a minute if the status has changed.
A good new year to you too!

**Comment by ilkaskim** [comment]
Thanks for the quick response, I'm at work now and I'll try tonight when I'm back home 👍

**Comment by ilkaskim** [comment]
Works fine, thank you very much 👍👍
Have a nice evening
