### ISSUE TITLE
Add Zigbee scene remote

### ISSUE THREAD

**Issue by rleunk** [Xenomes/Domoticz-TinyTUYA-Plugin#78]
Would it be possible to add the Tuya Smart Scene Switch 1-4 Gang

as found here [https://nl.aliexpress.com/item/1005005566323152.html?src=google&src=google&albch=shopping&acnt=494-037-6276&slnk=&plac=&mtctp=&albbt=Google_7_shopping&albagn=888888&isSmbAutoCall=false&needSmbHouyi=false&albcp=19207420692&albag=&trgt=&crea=nl1005005566323152&netw=x&device=c&albpg=&albpd=nl1005005566323152&gad_source=1&gclid=CjwKCAiAqNSsBhAvEiwAn_tmxUd90LkGEv2VHMydskUxzOMHr_M9s_DcbChJNM2dj_r0bO5KWBFtKhoCfXkQAvD_BwE&gclsrc=aw.ds&aff_fcid=fadcbc332b1042e8ae185c2477c91ad8-1704319185839-00341-UneMJZVf&aff_fsk=UneMJZVf&aff_platform=aaf&sk=UneMJZVf&aff_trace_key=fadcbc332b1042e8ae185c2477c91ad8-1704319185839-00341-UneMJZVf&terminal_id=baa28bb60b73451da2a28d3eb16a1ebd&afSmartRedirect=y](url)

Thanks in advance

here is the info i got with debug discovery:

List of devices: 
[
  {
    "name": "Afstandsbediening kamer",
    "id": "bf6----------coeko",
    "key": "Deleted",
    "mac": "a4:c1:38:c0:22:a4:16:66",
    "uuid": "a4c138c022a41666",
    "sn": "100129649001EB",
    "category": "wxkg",
    "product_name": "Switch of scene",
    "product_id": "mh9px7cq",
    "biz_type": 0,
    "model": "Switch of scene-ZIGBEE-V01",
    "sub": true,
    "icon": "https://images.tuyaeu.com/smart/icon/ay15554925906369PM9S/4b5d40431044b1174d496977a083af4f.jpg",
    "node_id": "a4c138c022a41666"
  },
 ]
Properties of device: bf----------coeko
{
  "result": {
    "category": "wxkg",
    "status": [
      {
        "code": "switch_mode1",
        "name": "\u65e0\u7ebf\u5f00\u51731",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"double_click\",\"press\"]}"
      },
      {
        "code": "switch_mode2",
        "name": "\u65e0\u7ebf\u5f00\u51732",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"double_click\",\"press\"]}"
      },
      {
        "code": "switch_mode3",
        "name": "\u65e0\u7ebf\u5f00\u51733",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"double_click\",\"press\"]}"
      },
      {
        "code": "switch_mode4",
        "name": "\u65e0\u7ebf\u5f00\u51734",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"double_click\",\"press\"]}"
      },
      {
        "code": "battery_percentage",
        "name": "\u7535\u6c60\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1704318388407,
  "tid": "8cbccbb8aa8111ee9384da1e0a435480"
}
Status of device: bf6----------coeko
{
  "result": [
    {
      "code": "switch_mode1",
      "value": "click"
    },
    {
      "code": "switch_mode2",
      "value": "click"
    },
    {
      "code": "switch_mode3",
      "value": "click"
    },
    {
      "code": "switch_mode4",
      "value": "click"
    },
    {
      "code": "battery_percentage",
      "value": 100
    }
  ],
  "success": true,
  "t": 1704318388513,
  "tid": "8ccaee8daa8111ee8fc772a61aaa5afa"
}

**Comment by Xenomes** [comment]
Hi,
First, I want to ask if you have put the devices in 'DP Instruction' mode. If not, could you do that and create a new dump.json? I hope there will be more state in there.

**Comment by rleunk** [comment]
Hi Xenomes,

 

Thnx, I looked, but the devices was already in DP Instraction mode, change dit to standard and made a new dump, then set it back to DP again, and made another dump.

It’s not i really needs the device in domoticz, otherwise looking for a way to block it being imported into domoticz, generates problems in the domoticz log.

 

Here are both new dumps, first the standard, then the DP mode:

 

Standard mode:

 

List of devices: 

  {

    "name": "Afstandsbediening kamer",

    "id": "bf6----------coeko",

    "key": "Deleted",

    "mac": "a4:c1:38:c0:22:a4:16:66",

    "uuid": "a4c138c022a41666",

    "sn": "100129649001EB",

    "category": "wxkg",

    "product_name": "Switch of scene",

    "product_id": "mh9px7cq",

    "biz_type": 0,

    "model": "Switch of scene-ZIGBEE-V01",

    "sub": true,

    "icon": https://images.tuyaeu.com/smart/icon/ay15554925906369PM9S/4b5d40431044b1174d496977a083af4f.jpg,

    "node_id": "a4c138c022a41666"

  },

Properties of device: bf----------coeko

{

  "result": {

    "category": "wxkg",

    "status": [

      {

        "code": "switch_mode1",

        "name": "\u65e0\u7ebf\u5f00\u51731",

        "type": "Enum",

        "values": "{\"range\":[\"click\",\"double_click\",\"press\"]}"

      },

      {

        "code": "switch_mode2",

        "name": "\u65e0\u7ebf\u5f00\u51732",

        "type": "Enum",

        "values": "{\"range\":[\"click\",\"double_click\",\"press\"]}"

      },

      {

        "code": "switch_mode3",

        "name": "\u65e0\u7ebf\u5f00\u51733",

        "type": "Enum",

        "values": "{\"range\":[\"click\",\"double_click\",\"press\"]}"

      },

      {

        "code": "switch_mode4",

        "name": "\u65e0\u7ebf\u5f00\u51734",

        "type": "Enum",

        "values": "{\"range\":[\"click\",\"double_click\",\"press\"]}"

      },

      {

        "code": "battery_percentage",

        "name": "\u7535\u6c60\u7535\u91cf",

        "type": "Integer",

        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"

      }

    ]

  },

  "success": true,

  "t": 1704382930227,

  "tid": "d2a8f341ab1711ee9a38d6c415ded054"

}

Status of device: bf6----------coeko

{

  "result": [

    {

      "code": "switch_mode1",

      "value": "click"

    },

    {

      "code": "switch_mode2",

      "value": "click"

    },

    {

      "code": "switch_mode3",

      "value": "click"

    },

    {

      "code": "switch_mode4",

      "value": "click"

    },

    {

      "code": "battery_percentage",

      "value": 100

    }

  ],

  "success": true,

  "t": 1704382930336,

  "tid": "d2b709d4ab1711ee847d96852008b4f4"

}

 

 

DP mode:

 

List of devices: 

  {

    "name": "Afstandsbediening kamer",

    "id": "bf6----------coeko",

    "key": "Deleted",

    "mac": "a4:c1:38:c0:22:a4:16:66",

    "uuid": "a4c138c022a41666",

    "sn": "100129649001EB",

    "category": "wxkg",

    "product_name": "Switch of scene",

    "product_id": "mh9px7cq",

    "biz_type": 0,

    "model": "Switch of scene-ZIGBEE-V01",

    "sub": true,

    "icon": https://images.tuyaeu.com/smart/icon/ay15554925906369PM9S/4b5d40431044b1174d496977a083af4f.jpg,

    "node_id": "a4c138c022a41666"

  },

Properties of device: bf6----------coeko

{

  "result": {

    "category": "wxkg",

    "status": [

      {

        "code": "switch_type_1",

        "name": "\u5f00\u5173\u65b9\u5f0f1",

        "type": "Enum",

        "values": "{\"range\":[\"single_click\",\"double_click\",\"long_press\"]}"

      },

      {

        "code": "switch_type_2",

        "name": "\u5f00\u5173\u65b9\u5f0f2",

        "type": "Enum",

        "values": "{\"range\":[\"single_click\",\"double_click\",\"long_press\"]}"

      },

      {

        "code": "switch_type_3",

        "name": "\u5f00\u5173\u65b9\u5f0f3",

        "type": "Enum",

        "values": "{\"range\":[\"single_click\",\"double_click\",\"long_press\"]}"

      },

      {

        "code": "switch_type_4",

        "name": "\u5f00\u5173\u65b9\u5f0f4",

        "type": "Enum",

        "values": "{\"range\":[\"single_click\",\"double_click\",\"long_press\"]}"

      },

      {

        "code": "battery_percentage",

        "name": "\u7535\u6c60\u7535\u91cf",

        "type": "Integer",

        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"

      }

    ]

  },

  "success": true,

  "t": 1704383030110,

  "tid": "0e311e31ab1811ee847d96852008b4f4"

}

Status of device: bf6----------coeko

{

  "result": [

    {

      "code": "switch_type_1",

      "value": "single_click"

    },

    {

      "code": "switch_type_2",

      "value": "single_click"

    },

    {

      "code": "switch_type_3",

      "value": "single_click"

    },

    {

      "code": "switch_type_4",

      "value": "single_click"

    },

    {

      "code": "battery_percentage",

      "value": 100

    }

  ],

  "success": true,

  "t": 1704383030211,

  "tid": "0e3fe5e5ab1811ee8b9b4ef73d358bf3"

}

 

 

Van: Xenomes ***@***.***> 
Verzonden: donderdag 4 januari 2024 14:25
Aan: Xenomes/Domoticz-TinyTUYA-Plugin ***@***.***>
CC: rleunk ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Xenomes/Domoticz-TinyTUYA-Plugin] Add Zigbee scene remote (Issue #78)

 

Hi,
First, I want to ask if you have put the devices in 'DP Instruction' mode. If not, could you do that and create a new dump.json? I hope there will be more state in there.

**Comment by rleunk** [comment]
Hi Xenomes,

Thnx, I looked, but the devices was already in DP Instraction mode, change dit to standard and made a new dump, then set it back to DP again, and made another dump.
It’s not i really needs the device in domoticz, otherwise looking for a way to block it being imported into domoticz, generates problems in the domoticz log.

Here are both new dumps, first the standard, then the DP mode:

Standard mode:

List of devices: 
  {
    "name": "Afstandsbediening kamer",
    "id": "bf6----------coeko",
    "key": "Deleted",
    "mac": "a4:c1:38:c0:22:a4:16:66",
    "uuid": "a4c138c022a41666",
    "sn": "100129649001EB",
    "category": "wxkg",
    "product_name": "Switch of scene",
    "product_id": "mh9px7cq",
    "biz_type": 0,
    "model": "Switch of scene-ZIGBEE-V01",
    "sub": true,
    "icon": https://images.tuyaeu.com/smart/icon/ay15554925906369PM9S/4b5d40431044b1174d496977a083af4f.jpg,
    "node_id": "a4c138c022a41666"
  },
Properties of device: bf----------coeko
{
  "result": {
    "category": "wxkg",
    "status": [
      {
        "code": "switch_mode1",
        "name": "\u65e0\u7ebf\u5f00\u51731",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"double_click\",\"press\"]}"
      },
      {
        "code": "switch_mode2",
        "name": "\u65e0\u7ebf\u5f00\u51732",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"double_click\",\"press\"]}"
      },
      {
        "code": "switch_mode3",
        "name": "\u65e0\u7ebf\u5f00\u51733",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"double_click\",\"press\"]}"
      },
      {
        "code": "switch_mode4",
        "name": "\u65e0\u7ebf\u5f00\u51734",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"double_click\",\"press\"]}"
      },
      {
        "code": "battery_percentage",
        "name": "\u7535\u6c60\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1704382930227,
  "tid": "d2a8f341ab1711ee9a38d6c415ded054"
}
Status of device: bf6----------coeko
{
  "result": [
    {
      "code": "switch_mode1",
      "value": "click"
    },
    {
      "code": "switch_mode2",
      "value": "click"
    },
    {
      "code": "switch_mode3",
      "value": "click"
    },
    {
      "code": "switch_mode4",
      "value": "click"
    },
    {
      "code": "battery_percentage",
      "value": 100
    }
  ],
  "success": true,
  "t": 1704382930336,
  "tid": "d2b709d4ab1711ee847d96852008b4f4"
}


DP mode:

List of devices: 
  {
    "name": "Afstandsbediening kamer",
    "id": "bf6----------coeko",
    "key": "Deleted",
    "mac": "a4:c1:38:c0:22:a4:16:66",
    "uuid": "a4c138c022a41666",
    "sn": "100129649001EB",
    "category": "wxkg",
    "product_name": "Switch of scene",
    "product_id": "mh9px7cq",
    "biz_type": 0,
    "model": "Switch of scene-ZIGBEE-V01",
    "sub": true,
    "icon": https://images.tuyaeu.com/smart/icon/ay15554925906369PM9S/4b5d40431044b1174d496977a083af4f.jpg,
    "node_id": "a4c138c022a41666"
  },
Properties of device: bf6----------coeko
{
  "result": {
    "category": "wxkg",
    "status": [
      {
        "code": "switch_type_1",
        "name": "\u5f00\u5173\u65b9\u5f0f1",
        "type": "Enum",
        "values": "{\"range\":[\"single_click\",\"double_click\",\"long_press\"]}"
      },
      {
        "code": "switch_type_2",
        "name": "\u5f00\u5173\u65b9\u5f0f2",
        "type": "Enum",
        "values": "{\"range\":[\"single_click\",\"double_click\",\"long_press\"]}"
      },
      {
        "code": "switch_type_3",
        "name": "\u5f00\u5173\u65b9\u5f0f3",
        "type": "Enum",
        "values": "{\"range\":[\"single_click\",\"double_click\",\"long_press\"]}"
      },
      {
        "code": "switch_type_4",
        "name": "\u5f00\u5173\u65b9\u5f0f4",
        "type": "Enum",
        "values": "{\"range\":[\"single_click\",\"double_click\",\"long_press\"]}"
      },
      {
        "code": "battery_percentage",
        "name": "\u7535\u6c60\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1704383030110,
  "tid": "0e311e31ab1811ee847d96852008b4f4"
}
Status of device: bf6----------coeko
{
  "result": [
    {
      "code": "switch_type_1",
      "value": "single_click"
    },
    {
      "code": "switch_type_2",
      "value": "single_click"
    },
    {
      "code": "switch_type_3",
      "value": "single_click"
    },
    {
      "code": "switch_type_4",
      "value": "single_click"
    },
    {
      "code": "battery_percentage",
      "value": 100
    }
  ],
  "success": true,
  "t": 1704383030211,
  "tid": "0e3fe5e5ab1811ee8b9b4ef73d358bf3"
}

**Comment by Xenomes** [comment]
Thanks, I have the idea to reset the selector switch to 'off' after the status has changed. Otherwise, I can't trigger the same button press, can you work with that?

**Comment by rleunk** [comment]
Sounds good

**Comment by Xenomes** [comment]
I saw that I already made some code for a similar product. I added your JSON code and added the device to the 'Develop' branch. Can you test it?
```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service
```

**Comment by rleunk** [comment]
Thanx, nice going, I just did a test, the standard error message to do a dump is gone now.
After reboot i get the following message in the domoticz log: 2024-01-05 18:08:59.594 Error: Cannot set options on device 0

I have 4 new devices on the switches tab, with the round on/off button and single_click, double click and long press button.

When i press the round button, it does nothing and stays grey,
When pressing single click, double click or long press that button gets active, and the round on/off button gets red and stays that way, can not switch it off.

After reboot it is in the last state before doing the reboot.

Pressing single click on switch 1 gives:
2024-01-05 18:34:14.986 Status: User: xxxxxx (IP: 192.168.1.8) initiated a switch command (1302/Afstandsbediening kamer (Switch 1)/Set Level)

Hope this info is usefull.

**Comment by rleunk** [comment]
![Schermafbeelding 2024-01-05 182314](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/31292367/41f1a7ae-b167-4c1d-92e5-e0aff0c02241)

Screenshot says more then 100 words :-)

**Comment by rleunk** [comment]
![Schermafbeelding 2024-01-05 182346](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/31292367/ee8f159c-a02e-48ec-818c-6f30c324d4c6)

**Comment by Xenomes** [comment]
> Thanx, nice going, I just did a test, the standard error message to do a dump is gone now. After reboot i get the following message in the domoticz log: 2024-01-05 18:08:59.594 Error: Cannot set options on device 0

I saw the error too; it is only listed on the creation of the switches. I am trying to find out the issue, but there is no problem with the created switches.

> I have 4 new devices on the switches tab, with the round on/off button and single_click, double click and long press button.
> 
> When i press the round button, it does nothing and stays grey, When pressing single click, double click or long press that button gets active, and the round on/off button gets red and stays that way, can not switch it off.

That is what I was afraid of; in the JSON, there is only a status and no function (control). So, the traffic is one-way, from the remote to Domoticz, with a delay of a maximum of 1 minute.
 
> After reboot it is in the last state before doing the reboot.
> 
> Pressing single click on switch 1 gives: 2024-01-05 18:34:14.986 Status: User: xxxxxx (IP: 192.168.1.8) initiated a switch command (1302/Afstandsbediening kamer (Switch 1)/Set Level)

The command before that is Command send to Tuya: bf6----------coeko, {'commands': [{'code': 'switch_type_1', 'value': 'single_click'}]}. That is the normal function for Tuya to execute, but it is ignored by Tuya. The command you mentioned is for the button update.
> Hope this info is usefull.

**Comment by rleunk** [comment]
Ok, thnx for the update. Only status should be fine for me.
Look like no status change is coming through at this moment, all devices are last seen at the time I pressed one of the click button's last night

**Comment by Xenomes** [comment]
Okay, I see I forgot to reset a test setting. I pushed a new version.

**Comment by rleunk** [comment]
Status is now changing from single_click to double click or long press, from one too another or other combinations.
Last seen is not updated when doing the same action as the mode the device is in at that moment, but think that is normal?
Al together works fine for me.

Thnx for the work Xenomes

**Comment by Xenomes** [comment]
Okay perfect! There is no other way to detect if the key is pressed again.
