### ISSUE TITLE
PC321-TY Power meter

### ISSUE THREAD

**Issue by nlovrens** [Xenomes/Domoticz-TinyTUYA-Plugin#8]
Hi,

Can you please add three phase power meter PC321-TY compatibility. BTW, is it possible to add local pooling option to avoid cloud API calls? 
This is debug discovery:

> List of devices: 
>  [
>   {
>     "name": "Power Clamp",
>     "id": "bfcf6e05fbed089041mmzh",
>     "key": "Deleted",
>     "mac": "1c:90:ff:24:ec:5a",
>     "category": "zndb",
>     "product_name": "Power Clamp",
>     "product_id": "9rjjf6rdkca9woju",
>     "biz_type": 0,
>     "model": "",
>     "sub": false,
>     "icon": "https://images.tuyaeu.com/smart/icon/ay1515026431018saCFs/af3de6a42a5ae7e5afb3fbc411cc1dfb.png",
>     "uuid": "6ed8134fe5338dff"
>   }
> ]
> 
> Functions of device: bfcf6e05fbed089041mmzh
>  {
>   "result": {
>     "category": "zndb",
>     "functions": []
>   },
>   "success": true,
>   "t": 1674159717111,
>   "tid": "ebd72200983611edbd98a6d801a7eabc"
> }
> 
> Status of device: bfcf6e05fbed089041mmzh
>  {
>   "result": [],
>   "success": true,
>   "t": 1674159717238,
>   "tid": "ebeb2e0b983611ed89e112b09600735b"
> }

This is direct local IP scan from tinytuya:

> TinyTuya (Tuya device scanner) [1.10.0]
> 
> [Loaded devices.json - 1 devices]
> 
> Scanning on UDP ports 6666 and 6667 and 7000 for devices for 18 seconds...
> 
> Power Clamp   Product ID = 9rjjf6rdkca9woju  [Valid Broadcast]:
>     Address = 192.168.0.54   Device ID = bfcf6e05fbed089041mmzh (len:22)  Local Key = deleted  Version = 3.3  Type = default, MAC = 1c:90:ff:24:ec:5a
>     Status: {'101': 5, '104': 0, '111': 1, '114': 0, '121': 2351, '124': 0, '135': 50, '136': 347, '137': 48, '138': '0'}
> Scan completed in 18.0407 seconds                  
>                     
> Scan Complete!  Found 1 devices.
> Broadcasted: 1
> Versions: 3.3: 1

Thank you!

**Comment by Xenomes** [comment]
> Can you please add three phase power meter PC321-TY compatibility.

Yes off course i will try to add it!

> BTW, is it possible to add local pooling option to avoid cloud API calls?

Local support is on the to-do list, but I do don't know when i start working in that.

Edit:
I see now that the "functions": [] and "result": [] are empty. I think that Tinytuya don't 100% support it.

**Comment by nlovrens** [comment]
I don't know why those are empty, it could be that is not supported... I will see what I can do to troubleshoot...

**Comment by nlovrens** [comment]
ok, I have changed control instruction mode on tuya platform from "Standard Instruction" to "DP Instruction" and now I have some results.

By default "debug_discovery.py" gave me this, "functions" are still empty:
> root@docker .../Domoticz-TinyTUYA-Plugin/tools# python3 debug_discovery.py 
> List of devices: 
>  [
>   {
>     "name": "Power Clamp",
>     "id": "bfcf6e05fbed089041mmzh",
>     "key": "Deleted",
>     "mac": "1c:90:ff:24:ec:5a",
>     "category": "zndb",
>     "product_name": "Power Clamp",
>     "product_id": "9rjjf6rdkca9woju",
>     "biz_type": 0,
>     "model": "",
>     "sub": false,
>     "icon": "https://images.tuyaeu.com/smart/icon/ay1515026431018saCFs/af3de6a42a5ae7e5afb3fbc411cc1dfb.png",
>     "uuid": "6ed8134fe5338dff"
>   }
> ]
> 
> Functions of device: bfcf6e05fbed089041mmzh
>  {
>   "result": {
>     "category": "zndb",
>     "functions": []
>   },
>   "success": true,
>   "t": 1674217213383,
>   "tid": "ca49ab5098bc11ed89e112b09600735b"
> }
> 
> Status of device: bfcf6e05fbed089041mmzh
>  {
>   "result": [
>     {
>       "code": "VoltageA",
>       "value": 5
>     },
>     {
>       "code": "CurrentA",
>       "value": 0
>     },
>     {
>       "code": "ActivePowerA",
>       "value": 0
>     },
>     {
>       "code": "PowerFactorA",
>       "value": 0
>     },
>     {
>       "code": "ReactivePowerA",
>       "value": 0
>     },
>     {
>       "code": "EnergyConsumedA",
>       "value": 0
>     },
>     {
>       "code": "VoltageB",
>       "value": 1
>     },
>     {
>       "code": "CurrentB",
>       "value": 0
>     },
>     {
>       "code": "ActivePowerB",
>       "value": 0
>     },
>     {
>       "code": "PowerFactorB",
>       "value": 0
>     },
>     {
>       "code": "ReactivePowerB",
>       "value": 0
>     },
>     {
>       "code": "EnergyConsumedB",
>       "value": 0
>     },
>     {
>       "code": "VoltageC",
>       "value": 2338
>     },
>     {
>       "code": "CurrentC",
>       "value": 0
>     },
>     {
>       "code": "ActivePowerC",
>       "value": 0
>     },
>     {
>       "code": "PowerFactorC",
>       "value": 0
>     },
>     {
>       "code": "ReactivePowerC",
>       "value": 0
>     },
>     {
>       "code": "EnergyConsumedC",
>       "value": 0
>     },
>     {
>       "code": "EnergyConsumed",
>       "value": 0
>     },
>     {
>       "code": "Current",
>       "value": 0
>     },
>     {
>       "code": "ActivePower",
>       "value": 0
>     },
>     {
>       "code": "ReactivePower",
>       "value": 0
>     },
>     {
>       "code": "Frequency",
>       "value": 50
>     },
>     {
>       "code": "Temperature",
>       "value": 332
>     },
>     {
>       "code": "DeviceStatus",
>       "value": 48
>     },
>     {
>       "code": "voltage_phase_seq",
>       "value": "0"
>     }
>   ],
>   "success": true,
>   "t": 1674217213531,
>   "tid": "ca609dbf98bc11ed89e112b09600735b"
> }

If I modify "debug_discovery.py" script to c.getproperties instead of c.getfunctions, i get this:

> root@docker .../Domoticz-TinyTUYA-Plugin/tools# python3 debug_discovery.py 
> List of devices: 
>  [
>   {
>     "name": "Power Clamp",
>     "id": "bfcf6e05fbed089041mmzh",
>     "key": "Deleted",
>     "mac": "1c:90:ff:24:ec:5a",
>     "category": "zndb",
>     "product_name": "Power Clamp",
>     "product_id": "9rjjf6rdkca9woju",
>     "biz_type": 0,
>     "model": "",
>     "sub": false,
>     "icon": "https://images.tuyaeu.com/smart/icon/ay1515026431018saCFs/af3de6a42a5ae7e5afb3fbc411cc1dfb.png",
>     "uuid": "6ed8134fe5338dff"
>   }
> ]
> 
> Functions of device: bfcf6e05fbed089041mmzh
>  {
>   "result": {
>     "category": "zndb",
>     "status": [
>       {
>         "code": "VoltageA",
>         "name": "A\u76f8\u7535\u538b",
>         "type": "Integer",
>         "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
>       },
>       {
>         "code": "CurrentA",
>         "name": "A\u76f8\u7535\u6d41",
>         "type": "Integer",
>         "values": "{\"unit\":\"A\",\"min\":0,\"max\":300000,\"scale\":3,\"step\":1}"
>       },
>       {
>         "code": "ActivePowerA",
>         "name": "A\u76f8\u6709\u529f\u529f\u7387",
>         "type": "Integer",
>         "values": "{\"unit\":\"W\",\"min\":0,\"max\":660000,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "PowerFactorA",
>         "name": "A\u76f8\u529f\u7387\u56e0\u6570",
>         "type": "Integer",
>         "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":2,\"step\":1}"
>       },
>       {
>         "code": "ReactivePowerA",
>         "name": "A\u76f8\u65e0\u529f\u529f\u7387",
>         "type": "Integer",
>         "values": "{\"unit\":\"var\",\"min\":0,\"max\":66000,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "EnergyConsumedA",
>         "name": "A\u76f8\u7535\u91cf",
>         "type": "Integer",
>         "values": "{\"unit\":\"Kw\u00b7h\",\"min\":0,\"max\":2000000000,\"scale\":2,\"step\":1}"
>       },
>       {
>         "code": "VoltageB",
>         "name": "B\u76f8\u7535\u538b",
>         "type": "Integer",
>         "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
>       },
>       {
>         "code": "CurrentB",
>         "name": "B\u76f8\u7535\u6d41",
>         "type": "Integer",
>         "values": "{\"unit\":\"A\",\"min\":0,\"max\":300000,\"scale\":3,\"step\":1}"
>       },
>       {
>         "code": "ActivePowerB",
>         "name": "B\u76f8\u6709\u529f\u529f\u7387",
>         "type": "Integer",
>         "values": "{\"unit\":\"W\",\"min\":0,\"max\":660000,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "PowerFactorB",
>         "name": "B\u76f8\u529f\u7387\u56e0\u6570",
>         "type": "Integer",
>         "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":2,\"step\":1}"
>       },
>       {
>         "code": "ReactivePowerB",
>         "name": "B\u76f8\u65e0\u529f\u529f\u7387",
>         "type": "Integer",
>         "values": "{\"unit\":\"var\",\"min\":0,\"max\":66000,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "EnergyConsumedB",
>         "name": "B\u76f8\u7535\u91cf",
>         "type": "Integer",
>         "values": "{\"unit\":\"Kw\u00b7h\",\"min\":0,\"max\":2000000000,\"scale\":2,\"step\":1}"
>       },
>       {
>         "code": "VoltageC",
>         "name": "C\u76f8\u7535\u538b",
>         "type": "Integer",
>         "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
>       },
>       {
>         "code": "CurrentC",
>         "name": "C\u76f8\u7535\u6d41",
>         "type": "Integer",
>         "values": "{\"unit\":\"A\",\"min\":0,\"max\":300000,\"scale\":3,\"step\":1}"
>       },
>       {
>         "code": "ActivePowerC",
>         "name": "C\u76f8\u6709\u529f\u529f\u7387",
>         "type": "Integer",
>         "values": "{\"unit\":\"W\",\"min\":0,\"max\":660000,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "PowerFactorC",
>         "name": "C\u76f8\u529f\u7387\u56e0\u6570",
>         "type": "Integer",
>         "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":2,\"step\":1}"
>       },
>       {
>         "code": "ReactivePowerC",
>         "name": "C\u76f8\u65e0\u529f\u529f\u7387",
>         "type": "Integer",
>         "values": "{\"unit\":\"var\",\"min\":0,\"max\":66000,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "EnergyConsumedC",
>         "name": "C\u76f8\u7535\u91cf",
>         "type": "Integer",
>         "values": "{\"unit\":\"Kw\u00b7h\",\"min\":0,\"max\":2000000000,\"scale\":2,\"step\":1}"
>       },
>       {
>         "code": "EnergyConsumed",
>         "name": "\u603b\u7535\u91cf",
>         "type": "Integer",
>         "values": "{\"unit\":\"Kw\u00b7h\",\"min\":0,\"max\":2000000000,\"scale\":2,\"step\":1}"
>       },
>       {
>         "code": "Current",
>         "name": "\u603b\u7535\u6d41",
>         "type": "Integer",
>         "values": "{\"unit\":\"A\",\"min\":0,\"max\":900000,\"scale\":3,\"step\":1}"
>       },
>       {
>         "code": "ActivePower",
>         "name": "\u603b\u529f\u7387",
>         "type": "Integer",
>         "values": "{\"unit\":\"W\",\"min\":0,\"max\":1980000,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "ReactivePower",
>         "name": "\u603b\u65e0\u529f\u529f\u7387",
>         "type": "Integer",
>         "values": "{\"unit\":\"var\",\"min\":0,\"max\":198000,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "Frequency",
>         "name": "\u9891\u7387",
>         "type": "Integer",
>         "values": "{\"unit\":\"Hz\",\"min\":0,\"max\":80,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "Temperature",
>         "name": "\u8bbe\u5907\u6e29\u5ea6",
>         "type": "Integer",
>         "values": "{\"unit\":\"\u2103\",\"min\":-100,\"max\":800,\"scale\":1,\"step\":1}"
>       },
>       {
>         "code": "DeviceStatus",
>         "name": "\u8bbe\u5907\u72b6\u6001",
>         "type": "Bitmap",
>         "values": "{\"label\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\"],\"maxlen\":17}"
>       },
>       {
>         "code": "voltage_phase_seq",
>         "name": "\u7535\u538b\u76f8\u5e8f\u68c0\u6d4b",
>         "type": "Enum",
>         "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\"]}"
>       }
>     ]
>   },
>   "success": true,
>   "t": 1674217242416,
>   "tid": "db9766b498bc11ed89e112b09600735b"
> }
> 
> Status of device: bfcf6e05fbed089041mmzh
>  {
>   "result": [
>     {
>       "code": "VoltageA",
>       "value": 5
>     },
>     {
>       "code": "CurrentA",
>       "value": 0
>     },
>     {
>       "code": "ActivePowerA",
>       "value": 0
>     },
>     {
>       "code": "PowerFactorA",
>       "value": 0
>     },
>     {
>       "code": "ReactivePowerA",
>       "value": 0
>     },
>     {
>       "code": "EnergyConsumedA",
>       "value": 0
>     },
>     {
>       "code": "VoltageB",
>       "value": 1
>     },
>     {
>       "code": "CurrentB",
>       "value": 0
>     },
>     {
>       "code": "ActivePowerB",
>       "value": 0
>     },
>     {
>       "code": "PowerFactorB",
>       "value": 0
>     },
>     {
>       "code": "ReactivePowerB",
>       "value": 0
>     },
>     {
>       "code": "EnergyConsumedB",
>       "value": 0
>     },
>     {
>       "code": "VoltageC",
>       "value": 2340
>     },
>     {
>       "code": "CurrentC",
>       "value": 0
>     },
>     {
>       "code": "ActivePowerC",
>       "value": 0
>     },
>     {
>       "code": "PowerFactorC",
>       "value": 0
>     },
>     {
>       "code": "ReactivePowerC",
>       "value": 0
>     },
>     {
>       "code": "EnergyConsumedC",
>       "value": 0
>     },
>     {
>       "code": "EnergyConsumed",
>       "value": 0
>     },
>     {
>       "code": "Current",
>       "value": 0
>     },
>     {
>       "code": "ActivePower",
>       "value": 0
>     },
>     {
>       "code": "ReactivePower",
>       "value": 0
>     },
>     {
>       "code": "Frequency",
>       "value": 50
>     },
>     {
>       "code": "Temperature",
>       "value": 332
>     },
>     {
>       "code": "DeviceStatus",
>       "value": 48
>     },
>     {
>       "code": "voltage_phase_seq",
>       "value": "0"
>     }
>   ],
>   "success": true,
>   "t": 1674217242585,
>   "tid": "dbaf7e3398bc11edae3d265fe02d1603"
> }
> 
> 
> dump.json is created!

**Comment by Xenomes** [comment]
That is beter! Functions can be empty if there is no control, i have looked up the device, and there are no controls, or the app is showing something else?

**Comment by nlovrens** [comment]
No, there is no control, only readings

**Comment by Xenomes** [comment]
Hi I added the device to the Develop branche, please test it out!
Don't forget to delete the old unknown device.

**Comment by nlovrens** [comment]
It looks that it is working fine. Thank you so much!

**Comment by nlovrens** [comment]
Actually, I have one suggestion to make it simpler (at least visually :). Number of generated devices can be reduced because kWh meter also displays instant power consumption in Watts. And there is a 3 phase current device that can be used for all three phases. I have made a diagram to make it more clear:

![power_meter](https://user-images.githubusercontent.com/20867277/213816471-b46f68e1-e356-4a4b-a965-113d36bbb76f.jpg)

**Comment by Xenomes** [comment]
Thanks for your feedback, i will merge the devices together and change the to 3 phase, I missed that device.

**Comment by nlovrens** [comment]
Hi, I have connected the meter to check if it actually measures and it does shows, but watts are shown 1/10. For example, L3 power should be 270W, not 27W.

 
![image](https://user-images.githubusercontent.com/20867277/213864086-8b1be35e-3407-4ae8-a31d-ee18524b2692.png)

Also, kWh meter already shows instant power consumption so there is no need to merge two devices, you can only remove instant power device:

![image](https://user-images.githubusercontent.com/20867277/213864188-52e55816-fcb3-426a-a1c4-a769d2953b18.png)

![image](https://user-images.githubusercontent.com/20867277/213864201-5b905684-971c-48d5-88fe-5bf3881fe7aa.png)

**Comment by Xenomes** [comment]
Hi,
The Develop is updated with your requests, delete all power Clamp devices and update plugin.

**Comment by nlovrens** [comment]
Great, thank you. But, total power (kWh) and total current (A) are now missing :)

![image](https://user-images.githubusercontent.com/20867277/213868634-7c495282-dbcf-4e73-adff-7fa0a00e1bf8.png)

**Comment by Xenomes** [comment]
Yes, they where the same as Phase1. Am i incorrect?

**Comment by nlovrens** [comment]
No, there are phase1, phase2 and phase3. Total power is a sum of those three. So, at the end of the debug_discovery:

![image](https://user-images.githubusercontent.com/20867277/213868841-3e4c56a1-73b1-4bd9-9d1e-50bd54ce606f.png)

**Comment by Xenomes** [comment]
Can you put a new result json. With new values, to see what's get updated.

**Comment by nlovrens** [comment]
Sure, there it is:

> List of devices: 
>  [
>   {
>     "name": "Power Clamp",
>     "id": "bfcf6e05fbed089041mmzh",
>     "key": "Deleted",
>     "mac": "1c:90:ff:24:ec:5a",
>     "category": "zndb",
>     "product_name": "Power Clamp",
>     "product_id": "9rjjf6rdkca9woju",
>     "biz_type": 0,
>     "model": "",
>     "sub": false,
>     "icon": "https://images.tuyaeu.com/smart/icon/ay1515026431018saCFs/af3de6a42a5ae7e5afb3fbc411cc1dfb.png",
>     "uuid": "6ed8134fe5338dff"
>   }
> ]
> 
> Functions of device: bfcf6e05fbed089041mmzh
>  {
>   "result": {
>     "category": "zndb",
>     "functions": []
>   },
>   "success": true,
>   "t": 1674311489141,
>   "tid": "4b039564999811edae3d265fe02d1603"
> }
> 
> Status of device: bfcf6e05fbed089041mmzh
>  {
>   "result": [
>     {
>       "code": "VoltageA",
>       "value": 2334
>     },
>     {
>       "code": "CurrentA",
>       "value": 221
>     },
>     {
>       "code": "ActivePowerA",
>       "value": 27
>     },
>     {
>       "code": "PowerFactorA",
>       "value": 56
>     },
>     {
>       "code": "ReactivePowerA",
>       "value": 0
>     },
>     {
>       "code": "EnergyConsumedA",
>       "value": 8
>     },
>     {
>       "code": "VoltageB",
>       "value": 2333
>     },
>     {
>       "code": "CurrentB",
>       "value": 67
>     },
>     {
>       "code": "ActivePowerB",
>       "value": 9
>     },
>     {
>       "code": "PowerFactorB",
>       "value": 57
>     },
>     {
>       "code": "ReactivePowerB",
>       "value": 0
>     },
>     {
>       "code": "EnergyConsumedB",
>       "value": 3
>     },
>     {
>       "code": "VoltageC",
>       "value": 2336
>     },
>     {
>       "code": "CurrentC",
>       "value": 1918
>     },
>     {
>       "code": "ActivePowerC",
>       "value": 281
>     },
>     {
>       "code": "PowerFactorC",
>       "value": 62
>     },
>     {
>       "code": "ReactivePowerC",
>       "value": 0
>     },
>     {
>       "code": "EnergyConsumedC",
>       "value": 386
>     },
>     {
>       "code": "EnergyConsumed",
>       "value": 398
>     },
>     {
>       "code": "Current",
>       "value": 2206
>     },
>     {
>       "code": "ActivePower",
>       "value": 316
>     },
>     {
>       "code": "ReactivePower",
>       "value": 0
>     },
>     {
>       "code": "Frequency",
>       "value": 50
>     },
>     {
>       "code": "Temperature",
>       "value": 434
>     },
>     {
>       "code": "DeviceStatus",
>       "value": 0
>     },
>     {
>       "code": "voltage_phase_seq",
>       "value": "2"
>     }
>   ],
>   "success": true,
>   "t": 1674311489302,
>   "tid": "4b1c64e5999811ed89e112b09600735b"
> }
> 
> 
> dump.json is created!

**Comment by Xenomes** [comment]
The two devices are back. in the new Develop.

**Comment by nlovrens** [comment]
Hi,
I have tested it and now all devices are ok, but I have noticed that total current and L1 current were the same, and total power and L1 power were the same as well. I have looked into your code and noticed that in line 1029 you are getting valueRaw in the result using "if...in" function which matches first occurrence of the searched word, it doesn't match exact complete word. So, by searching for "Current" or "Power" it will actually match "CurrentA" and "ActivePowerA" and you will get that value because it is preceding "Current" and "ActivePower" in the result. I have managed to fix that using regex. So by "import re" and changing line 1029 to:
`valueRaw = [item['value'] for item in result if re.search(r'\b'+Function+r'\b', item['code']) != None][0]`
now it matches exact word and all data is shown as it should be.
atached is modified plugin.py.
If you need I can send you my API keys so you can test it yourself.

[plugin.py.txt](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/10475223/plugin.py.txt)

**Comment by Xenomes** [comment]
Thank for the modification! No i don't need the API keys, i can replicate a lot whit the json files. In the Develop your modification is add, also the scaling is now dynamic with getproperties so that work now much better.

**Comment by nlovrens** [comment]
Hi,
Unfortunately, now it is missing "last_update":

> 
> 2023-01-23 10:02:08.075 Error: Tuya Cloud: Call to function 'onHeartbeat' failed, exception details:
> 2023-01-23 10:02:08.075 Error: Tuya Cloud: Traceback (most recent call last):
> 2023-01-23 10:02:08.075 Error: Tuya Cloud: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 309, in onHeartbeat
> 2023-01-23 10:02:08.075 Error: Tuya Cloud: _plugin.onHeartbeat()
> 2023-01-23 10:02:08.075 Error: Tuya Cloud: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 270, in onHeartbeat
> 2023-01-23 10:02:08.075 Error: Tuya Cloud: if time.time() - last_update < 60 and testData == False:
> 2023-01-23 10:02:08.075 Error: Tuya Cloud: NameError: name 'last_update' is not defined
> 2023-01-23 10:02:18.099 Error: Tuya Cloud: Call to function 'onHeartbeat' failed, exception details:
> 2023-01-23 10:02:18.100 Error: Tuya Cloud: Traceback (most recent call last):
> 2023-01-23 10:02:18.100 Error: Tuya Cloud: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 309, in onHeartbeat
> 2023-01-23 10:02:18.100 Error: Tuya Cloud: _plugin.onHeartbeat()
> 2023-01-23 10:02:18.100 Error: Tuya Cloud: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 270, in onHeartbeat
> 2023-01-23 10:02:18.100 Error: Tuya Cloud: if time.time() - last_update < 60 and testData == False:
> 2023-01-23 10:02:18.100 Error: Tuya Cloud: NameError: name 'last_update' is not defined
> 2023-01-23 10:02:28.070 Error: Tuya Cloud: Call to function 'onHeartbeat' failed, exception details:
> 2023-01-23 10:02:28.070 Error: Tuya Cloud: Traceback (most recent call last):
> 2023-01-23 10:02:28.070 Error: Tuya Cloud: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 309, in onHeartbeat
> 2023-01-23 10:02:28.070 Error: Tuya Cloud: _plugin.onHeartbeat()
> 2023-01-23 10:02:28.070 Error: Tuya Cloud: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 270, in onHeartbeat
> 2023-01-23 10:02:28.070 Error: Tuya Cloud: if time.time() - last_update < 60 and testData == False:
> 2023-01-23 10:02:28.070 Error: Tuya Cloud: NameError: name 'last_update' is not defined
> 2023-01-23 10:02:38.092 Error: Tuya Cloud: Call to function 'onHeartbeat' failed, exception details:
> 2023-01-23 10:02:38.092 Error: Tuya Cloud: Traceback (most recent call last):
> 2023-01-23 10:02:38.092 Error: Tuya Cloud: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 309, in onHeartbeat
> 2023-01-23 10:02:38.092 Error: Tuya Cloud: _plugin.onHeartbeat()
> 2023-01-23 10:02:38.092 Error: Tuya Cloud: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 270, in onHeartbeat
> 2023-01-23 10:02:38.092 Error: Tuya Cloud: if time.time() - last_update < 60 and testData == False:
> 2023-01-23 10:02:38.092 Error: Tuya Cloud: NameError: name 'last_update' is not defined

**Comment by Xenomes** [comment]
owe that is strange, i have update the Develop maybe it is fix.

**Comment by nlovrens** [comment]
hi, it looks that it works now. thank you
