### ISSUE TITLE
Add Wireless Switch

### ISSUE THREAD

**Issue by bwbboot** [Xenomes/Domoticz-TinyTUYA-Plugin#80]
Thanks!

` {
    "name": "Wireless Switch",
    "id": "bf9ea1682456670df7lm1h",
    "key": "Deleted",
    "mac": "fc:67:1f:28:55:df",
    "uuid": "57943f2de17416f3",
    "sn": "10008459100145",
    "category": "wxkg",
    "product_name": "Wireless Switch",
    "product_id": "l8yaz4um5b3pwyvf",
    "biz_type": 18,
    "model": "LKWSW201",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1550298204274iXb1I/daa3d49566506041feb8c3f95902086f.png"
  }`

`Properties of device: bf9ea1682456670df7lm1h
{
  "result": {
    "category": "wxkg",
    "status": [
      {
        "code": "switch_mode1",
        "name": "\u65e0\u7ebf\u5f00\u51731",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"press\"]}"
      },
      {
        "code": "switch_mode2",
        "name": "\u65e0\u7ebf\u5f00\u51732",
        "type": "Enum",
        "values": "{\"range\":[\"click\",\"press\"]}"
      },
      {
        "code": "battery_percentage",
        "name": "\u7535\u6c60\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1704539374534,
  "tid": "12bb9562ac8411eeb4711ef527e2ea42"
}
Status of device: bf9ea1682456670df7lm1h
{
  "result": [
    {
      "code": "switch_mode1",
      "value": "click"
    },
    {
      "code": "switch_mode2",
      "value": "click"
    },
    {
      "code": "battery_percentage",
      "value": 92
    }
  ],
  "success": true,
  "t": 1704539374665,
  "tid": "12cf0d73ac8411ee965f7eb6fd123fbf"
}
`

**Comment by Xenomes** [comment]
Hi Thanks! You device support was added to the latest develop version yesterday 😆

**Comment by bwbboot** [comment]
Perfect. Thanks!!

**Comment by bwbboot** [comment]
I have followed this instruction

`cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service`

Then removed the device from domoticz. But it's still discovered as an unsupported device.

<img width="1365" alt="Screenshot 2024-01-06 at 16 27 52" src="https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/31098984/9b79c9a9-fbca-4b51-8e4a-f1f8f2085d31">

**Comment by Xenomes** [comment]
Ha i see the issue, if you do a new pull it is fixed.

**Comment by bwbboot** [comment]
<img width="1419" alt="Screenshot 2024-01-06 at 17 02 16" src="https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/31098984/f011550f-7b47-43cf-b2ef-062973a08db5">

Thanks a lot!
