### ISSUE TITLE
Support for brightness sensor

### ISSUE THREAD

**Issue by GillesMart** [Xenomes/Domoticz-TinyTUYA-Plugin#82]
Hello,
Here is the json for a brightness sensor, that provides also temperature and humidity. It would be quite useful for automation when there's light in a room, to close shades or to shut off lights.

[light_sensor.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13933120/light_sensor.json)

Best regards.

**Comment by Xenomes** [comment]
Hi GillesMart,
Thanks for both JSON files. I will add this one to the sensor group. However, the 'Status of device:' is missing in the JSON. Can you provide it?

**Comment by Xenomes** [comment]
I made some manual edits to fill in the missing data, so please test it to ensure it is working correctly. I also added it to the Develop branch.

**Comment by GillesMart** [comment]
Hi Xenomes,
Sorry for not having been able to answer sooner. Here is the JSON with the "status of device" information.
[light_sensor2.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13986725/light_sensor2.json)
I haven't tested the Develop branch yet.

**Comment by GillesMart** [comment]
Hi, I can see a Lux sensor and a switch. The Lux sensor does update, which is great. I don't know what the purpose of the switch is, because it's an always-on device. I don't see any effect. But anyway, it's in the JSON, so why not. Thank you very much.

**Comment by Xenomes** [comment]
Good to hear that it is working. Regarding the switch, there is nothing displayed in the app what looks like on/off function?

**Comment by GillesMart** [comment]
Found the manual: it's a switch for a buzzer, in order to hear alerts from the device itself:
[NAS‐CW01W6_manual.pdf](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13994952/NAS.CW01W6_manual.pdf)

**Comment by Xenomes** [comment]
Okay, so the switch is also on the function side. Would you like to be in control of it?

**Comment by GillesMart** [comment]
Honestly I personally have no use for it, I just think it should be handled the same way as the other functions like humidity alarm and so on.

**Comment by Xenomes** [comment]
Perfect, then we leave it this way! Thanks!
