### ISSUE TITLE
Support for a cubetouch

### ISSUE THREAD

**Issue by GillesMart** [Xenomes/Domoticz-TinyTUYA-Plugin#83]
Hello, 
Here is the json for a cubetouch. It's a device that is able to press a button, for automatizing old-school devices with a physical button.

[cubetouch.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13933124/cubetouch.json)

Best regards.

**Comment by Xenomes** [comment]
Hi, I have add this device to de Develop build.
```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service
```

**Comment by GillesMart** [comment]
Hi, I can see that a switch has been created. It seems to be working. Thank you.

**Comment by Xenomes** [comment]
Very good!
