### ISSUE TITLE
Support fo SETTI+ weather station

### ISSUE THREAD

**Issue by mobzd** [Xenomes/Domoticz-TinyTUYA-Plugin#85]
I am attaching a dump.json of a device that is not recognized. It is a SETTI+ SMS603 weather station with three additional temperature and humidity indicators included. I would be very grateful if you could integrate it into TinyTUYA.
[dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/13989604/dump.json)

**Comment by Xenomes** [comment]
Thanks for the JSON. The three additional temperature and humidity indicators are in the JSON. I will try to add them this weekend.

**Comment by Xenomes** [comment]
Device is added to the Develop version, can you test it?

```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service
```
To switch back to the Master version, change 'Develop' to 'Master'.

**Comment by mobzd** [comment]
This version works almost perfectly. There are 2 problems:
- the fourth (ext3) sensor is missing (1 in the station + 3 external)
- ext2 (Temperature) always returns 0.0 C even though ext2 (Temperature + Humidity) returns correctly 23.3 C, 30%

Many thanks for including my station in your plugin! :)
 
<img width="1197" alt="Zrzut ekranu 2024-01-20 o 09 52 59" src="https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/27740783/51d2d3f7-8fd0-4789-b94f-4f818ea79293">

**Comment by Xenomes** [comment]
fixed in the new Develop!

**Comment by mobzd** [comment]
Wow - you're fast :)

We're almost there, but there's something wrong with ext3 (Temperature + Humidity) even though the individual Temperature and Humidity are OK.

Regards
—
Slawomir Bandzerewicz
***@***.***
tel. 502 424 494

**Comment by Xenomes** [comment]
I forgot small part of the code, pushed a new version.

**Comment by Xenomes** [comment]
Found one more typo, think it is now correct.

**Comment by mobzd** [comment]
Perfect! Everything works fine.

Thank you.
