### ISSUE TITLE
Air Purifier bug :)

### ISSUE THREAD

**Issue by Eurynomosek** [Xenomes/Domoticz-TinyTUYA-Plugin#86]
if dev_type == 'purifier':
                if Command == 'Off' and Unit == 1:
                    SendCommandCloud(DeviceID, 'switch', False)
                    UpdateDevice(DeviceID, Unit, 'Off', 0, 0)
                elif Command == 'On' and Unit == 1:
                    SendCommandCloud(DeviceID, 'poswitchwer_go', True)///////////////////////////////// misspelling
                    UpdateDevice(DeviceID, Unit, 'On', 1, 0)
                elif Command == 'Set Level' and Unit == 3:
                    mode = Devices[DeviceID].Units[Unit].Options['LevelNames'].split('|')
                    SendCommandCloud(DeviceID, 'mode', mode[int(Level / 10)])
                    UpdateDevice(DeviceID, Unit, Level, 1, 0)
                elif Command == 'Set Level' and Unit == 4:
                    mode = Devices[DeviceID].Units[Unit].Options['LevelNames'].split('|')
                    SendCommandCloud(DeviceID, 'mode', mode[int(Level / 10)])/////////////////////////////  please change  mode to speed 
                    UpdateDevice(DeviceID, Unit, Level, 1, 0)
                    
                    

                    
                    
when I changed these two wrong names everything works fine for  Purifier Setti+ AP850W

**Comment by Xenomes** [comment]
Hi Eurynomosek,
Thanks for the update, the typo in switch i had notice the mode to speed not.
The Develop is updated!
