### ISSUE TITLE
Please add CO2 meter, Zigbee/BT hub, change temperature/humidity sensor

### ISSUE THREAD

**Issue by Lion251** [Xenomes/Domoticz-TinyTUYA-Plugin#9]
Hi,

I've started playing with your plugin, and like it very much.
Many devices work out of the box, but I've encountered three new ones that are not recognized or handled properly.
Could you have a look at those?

The first one is a Zigbee temperature/humidity sensor.
It is recognized, but temperature is displayed without decimal point e.g. 143C ipv 14.3C
The second one is the Zigbee/bluetooth <=> WIFI gateway that is used to access #1.
I don't think it has Tuya functions, but it would be nice if it wouldn't throw an error message.
The third one is a CO2/Temp/humidity sensor.

If there is anything I can do to help, please let me know.
Is there a better way to upload the dump.json than copy/paste?

List of devices: 
[
  {
    "name": "Temperature and humidity Sensor",
    "id": "bf3f710f00739091b2ax1s",
    "key": "Deleted",
    "mac": "",
    "category": "wsdcg",
    "product_name": "Temperature and humidity Sensor",
    "product_id": "znbl8dj5",
    "biz_type": 0,
    "model": "ZG-227Z",
    "sub": true,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1531985537002uUUZI/773253070dc0aeff00c7e297ce647dcf.png",
    "uuid": "bf3f710f00739091b2ax1s",
    "node_id": "a4c1386dda9c8287"
  },
  {
    "name": "Gateway",
    "id": "bf9a726558031de3a546ce",
    "key": "Deleted",
    "mac": "a0:92:08:8b:50:01",
    "category": "wg2",
    "product_name": "Gateway",
    "product_id": "vv5weaudutzsqvai",
    "biz_type": 0,
    "model": "G08Pro(Zigbee+Bluetooth\u7f51\u5173)",
    "sub": true,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1525749833414yotNt/26ede3412687c225b9ca020f3340482f.png",
    "uuid": "fed3943f29fccb75"
  },
  {
    "name": "\u4e8c\u6c27\u5316\u78b3\u6d4b\u8bd5\u4eea PTH-9CW",
    "id": "bfa97ab3b1b974f198niqy",
    "key": "Deleted",
    "mac": "fc:67:1f:71:d3:4b",
    "category": "co2bj",
    "product_name": "\u4e8c\u6c27\u5316\u78b3\u6d4b\u8bd5\u4eea PTH-9CW",
    "product_id": "milbtultxrbfcc7u",
    "biz_type": 0,
    "model": "PTH9CW",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1571825171870ICRMe/8c8cdba866052da402427c8164fbe04d.png",
    "uuid": "9502e30fd7a0eca7"
  },
]
Functions of device: bf3f710f00739091b2ax1s
{
  "result": {
    "category": "wsdcg",
    "functions": [
      {
        "code": "temp_unit_convert",
        "desc": "temp unit convert",
        "name": "temp unit convert",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      }
    ]
  },
  "success": true,
  "t": 1674315252724,
  "tid": "0e48197d99a111ed89e112b09600735b"
}
Status of device: bf3f710f00739091b2ax1s
{
  "result": [
    {
      "code": "va_temperature",
      "value": 143
    },
    {
      "code": "va_humidity",
      "value": 39
    },
    {
      "code": "battery_percentage",
      "value": 100
    },
    {
      "code": "temp_unit_convert",
      "value": "c"
    }
  ],
  "success": true,
  "t": 1674315252985,
  "tid": "0e6665a399a111ed89e112b09600735b"
}
Functions of device: bf9a726558031de3a546ce
{
  "result": {
    "category": "wg2",
    "functions": [
      {
        "code": "switch_alarm_sound",
        "desc": "switch alarm sound",
        "name": "switch alarm sound",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "master_state",
        "desc": "master state",
        "name": "master state",
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"alarm\"]}"
      },
      {
        "code": "factory_reset",
        "desc": "factory reset",
        "name": "factory reset",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_active",
        "desc": "alarm active",
        "name": "alarm active",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ]
  },
  "success": true,
  "t": 1674315253178,
  "tid": "0e8d95fb99a111ed97b7f276006a160b"
}
Status of device: bf9a726558031de3a546ce
{
  "result": [
    {
      "code": "switch_alarm_sound",
      "value": false
    },
    {
      "code": "master_state",
      "value": "normal"
    },
    {
      "code": "factory_reset",
      "value": false
    },
    {
      "code": "alarm_active",
      "value": ""
    }
  ],
  "success": true,
  "t": 1674315253405,
  "tid": "0eb2cf8399a111ed89e112b09600735b"
}
Functions of device: bfa97ab3b1b974f198niqy
{
  "result": {
    "category": "co2bj",
    "functions": []
  },
  "success": true,
  "t": 1674315253567,
  "tid": "0ecbb3db99a111ed97b7f276006a160b"
}
Status of device: bfa97ab3b1b974f198niqy
{
  "result": [
    {
      "code": "co2_value",
      "value": 581
    },
    {
      "code": "temp_current",
      "value": 14
    },
    {
      "code": "humidity_value",
      "value": 49
    }
  ],
  "success": true,
  "t": 1674315253751,
  "tid": "0ee76d5899a111edae3d265fe02d1603"
}

**Comment by Xenomes** [comment]
Thanks! I will add these device. Let you know for testing.

**Comment by Xenomes** [comment]
Can you do a git pull and make a new debug_discovery? i added new scaling in the plug in so in need new info.

**Comment by Lion251** [comment]
List of devices: 
[
  {
    "name": "Temperature and humidity Sensor",
    "id": "bf3f710f00739091b2ax1s",
    "key": "Deleted",
    "mac": "",
    "category": "wsdcg",
    "product_name": "Temperature and humidity Sensor",
    "product_id": "znbl8dj5",
    "biz_type": 0,
    "model": "ZG-227Z",
    "sub": true,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1531985537002uUUZI/773253070dc0aeff00c7e297ce647dcf.png",
    "uuid": "bf3f710f00739091b2ax1s",
    "node_id": "a4c1386dda9c8287"
  },
  {
    "name": "Gateway",
    "id": "bf9a726558031de3a546ce",
    "key": "Deleted",
    "mac": "a0:92:08:8b:50:01",
    "category": "wg2",
    "product_name": "Gateway",
    "product_id": "vv5weaudutzsqvai",
    "biz_type": 0,
    "model": "G08Pro(Zigbee+Bluetooth\u7f51\u5173)",
    "sub": true,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1525749833414yotNt/26ede3412687c225b9ca020f3340482f.png",
    "uuid": "fed3943f29fccb75"
  },
  {
    "name": "\u4e8c\u6c27\u5316\u78b3\u6d4b\u8bd5\u4eea PTH-9CW",
    "id": "bfa97ab3b1b974f198niqy",
    "key": "Deleted",
    "mac": "fc:67:1f:71:d3:4b",
    "category": "co2bj",
    "product_name": "\u4e8c\u6c27\u5316\u78b3\u6d4b\u8bd5\u4eea PTH-9CW",
    "product_id": "milbtultxrbfcc7u",
    "biz_type": 0,
    "model": "PTH9CW",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1571825171870ICRMe/8c8cdba866052da402427c8164fbe04d.png",
    "uuid": "9502e30fd7a0eca7"
  },
  {
    "name": "A60-PA-WIFILIC-TY-CCT",
    "id": "bfa02fd285cfec2bf7lesc",
    "key": "Deleted",
    "mac": "d8:1f:12:ff:06:52",
    "category": "dj",
    "product_name": "A60-PA-WIFILIC-TY-CCT",
    "product_id": "xpaqxtzoftcxrpuu",
    "biz_type": 0,
    "model": "",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay15431996119293jn9C/7c6e3772e915d9fcb9b92730f67c0f89.png",
    "uuid": "a00f15886b02ece8"
  },
  {
    "name": "Koelkast",
    "id": "bf153acf8b2e88888fnta9",
    "key": "Deleted",
    "mac": "28:6d:cd:4d:4f:db",
    "category": "cz",
    "product_name": "Smart Plug",
    "product_id": "zmuquaytzuth4gkp",
    "biz_type": 0,
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/001460162698766TR4v1/79942f3d6a88da0da6bd6d907f600800.png",
    "uuid": "52250803286dcd4d4fdb"
  }
]
Functions of device: bf3f710f00739091b2ax1s
{
  "result": {
    "category": "wsdcg",
    "functions": [
      {
        "code": "temp_unit_convert",
        "desc": "temp unit convert",
        "name": "temp unit convert",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      }
    ]
  },
  "success": true,
  "t": 1674448910735,
  "tid": "40ab4bd99ad811edae3d265fe02d1603"
}
Properties of device: bf3f710f00739091b2ax1s
{
  "result": {
    "category": "wsdcg",
    "functions": [
      {
        "code": "temp_unit_convert",
        "desc": "{\"range\":[\"c\",\"f\"]}",
        "name": "\u6e29\u6807\u5207\u6362",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      }
    ],
    "status": [
      {
        "code": "va_temperature",
        "name": "\u5f53\u524d\u6e29\u5ea6",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-200,\"max\":800,\"scale\":1,\"step\":1}"
      },
      {
        "code": "va_humidity",
        "name": "\u6e7f\u5ea6\u6570\u503c",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "battery_percentage",
        "name": "\u7535\u6c60\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_unit_convert",
        "name": "\u6e29\u6807\u5207\u6362",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      }
    ]
  },
  "success": true,
  "t": 1674448910953,
  "tid": "40ccdb179ad811edae3d265fe02d1603"
}
Status of device: bf3f710f00739091b2ax1s
{
  "result": [
    {
      "code": "va_temperature",
      "value": 140
    },
    {
      "code": "va_humidity",
      "value": 42
    },
    {
      "code": "battery_percentage",
      "value": 100
    },
    {
      "code": "temp_unit_convert",
      "value": "c"
    }
  ],
  "success": true,
  "t": 1674448911189,
  "tid": "40f2f5859ad811ed97b7f276006a160b"
}
Functions of device: bf9a726558031de3a546ce
{
  "result": {
    "category": "wg2",
    "functions": [
      {
        "code": "switch_alarm_sound",
        "desc": "switch alarm sound",
        "name": "switch alarm sound",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "master_state",
        "desc": "master state",
        "name": "master state",
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"alarm\"]}"
      },
      {
        "code": "factory_reset",
        "desc": "factory reset",
        "name": "factory reset",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_active",
        "desc": "alarm active",
        "name": "alarm active",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ]
  },
  "success": true,
  "t": 1674448911381,
  "tid": "4110b18a9ad811edae3d265fe02d1603"
}
Properties of device: bf9a726558031de3a546ce
{
  "result": {
    "category": "wg2",
    "functions": [
      {
        "code": "switch_alarm_sound",
        "desc": "{}",
        "name": "\u62a5\u8b66\u58f0\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "master_state",
        "desc": "{\"range\":[\"normal\",\"alarm\"]}",
        "name": "\u4e3b\u673a\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"alarm\"]}"
      },
      {
        "code": "factory_reset",
        "desc": "{}",
        "name": "\u6062\u590d\u51fa\u5382\u8bbe\u7f6e",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_active",
        "desc": "{\"maxlen\":255}",
        "name": "\u4e3b\u52a8\u62a5\u8b66",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ],
    "status": [
      {
        "code": "switch_alarm_sound",
        "name": "\u62a5\u8b66\u58f0\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "master_state",
        "name": "\u4e3b\u673a\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"alarm\"]}"
      },
      {
        "code": "factory_reset",
        "name": "\u6062\u590d\u51fa\u5382\u8bbe\u7f6e",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_active",
        "name": "\u4e3b\u52a8\u62a5\u8b66",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ]
  },
  "success": true,
  "t": 1674448911597,
  "tid": "412dff059ad811ed89e112b09600735b"
}
Status of device: bf9a726558031de3a546ce
{
  "result": [
    {
      "code": "switch_alarm_sound",
      "value": false
    },
    {
      "code": "master_state",
      "value": "normal"
    },
    {
      "code": "factory_reset",
      "value": false
    },
    {
      "code": "alarm_active",
      "value": ""
    }
  ],
  "success": true,
  "t": 1674448911795,
  "tid": "414f912c9ad811ed89e112b09600735b"
}
Functions of device: bfa97ab3b1b974f198niqy
{
  "result": {
    "category": "co2bj",
    "functions": []
  },
  "success": true,
  "t": 1674448912036,
  "tid": "416f54809ad811ed89e112b09600735b"
}
Properties of device: bfa97ab3b1b974f198niqy
{
  "result": {
    "category": "co2bj",
    "status": [
      {
        "code": "co2_value",
        "name": "CO2\u68c0\u6d4b\u503c",
        "type": "Integer",
        "values": "{\"unit\":\"ppm\",\"min\":0,\"max\":5000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "name": "\u5f53\u524d\u6e29\u5ea6",
        "type": "Integer",
        "values": "{\"unit\":\"\u2103\",\"min\":-40,\"max\":125,\"scale\":0,\"step\":1}"
      },
      {
        "code": "humidity_value",
        "name": "\u6e7f\u5ea6\u6570\u503c",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1674448912232,
  "tid": "419169d59ad811ed89e112b09600735b"
}
Status of device: bfa97ab3b1b974f198niqy
{
  "result": [
    {
      "code": "co2_value",
      "value": 648
    },
    {
      "code": "temp_current",
      "value": 13
    },
    {
      "code": "humidity_value",
      "value": 53
    }
  ],
  "success": true,
  "t": 1674448912434,
  "tid": "41b0766c9ad811ed89e112b09600735b"
}
Functions of device: bfa02fd285cfec2bf7lesc
{
  "result": {
    "category": "dj",
    "functions": [
      {
        "code": "switch_led",
        "desc": "switch led",
        "name": "switch led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "desc": "work mode",
        "name": "work mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value_v2",
        "desc": "bright value v2",
        "name": "bright value v2",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value_v2",
        "desc": "temp value v2",
        "name": "temp value v2",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "scene_data_v2",
        "desc": "scene data v2",
        "name": "scene data v2",
        "type": "Json",
        "values": "{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"
      },
      {
        "code": "countdown_1",
        "desc": "countdown 1",
        "name": "countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_data",
        "desc": "control data",
        "name": "control data",
        "type": "Json",
        "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "rhythm_mode",
        "desc": "rhythm mode",
        "name": "rhythm mode",
        "type": "Raw",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "sleep_mode",
        "desc": "sleep mode",
        "name": "sleep mode",
        "type": "Raw",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "wakeup_mode",
        "desc": "wakeup mode",
        "name": "wakeup mode",
        "type": "Raw",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "remote_switch",
        "desc": "remote switch",
        "name": "remote switch",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1674448912649,
  "tid": "41d0dbf49ad811ed89e112b09600735b"
}
Properties of device: bfa02fd285cfec2bf7lesc
{
  "result": {
    "category": "dj",
    "functions": [
      {
        "code": "switch_led",
        "desc": "{}",
        "name": "\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "desc": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}",
        "name": "\u5de5\u4f5c\u6a21\u5f0f",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value_v2",
        "desc": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}",
        "name": "\u4eae\u5ea6",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value_v2",
        "desc": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}",
        "name": "\u8272\u6e29",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "scene_data_v2",
        "desc": "{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}",
        "name": "\u573a\u666f\u6a21\u5f0f\u503c",
        "type": "Json",
        "values": "{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_data",
        "desc": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}",
        "name": "\u8c03\u8282\u6a21\u5f0f\u503c",
        "type": "Json",
        "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "rhythm_mode",
        "desc": "{\"maxlen\":255}",
        "name": "\u751f\u7269\u8282\u5f8b",
        "type": "Raw",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "sleep_mode",
        "desc": "{\"maxlen\":255}",
        "name": "\u5165\u7761",
        "type": "Raw",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "wakeup_mode",
        "desc": "{\"maxlen\":255}",
        "name": "\u5524\u9192",
        "type": "Raw",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "remote_switch",
        "desc": "{}",
        "name": "\u9065\u63a7\u5668\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "name": "\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "name": "\u6a21\u5f0f",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value_v2",
        "name": "\u4eae\u5ea6",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value_v2",
        "name": "\u51b7\u6696",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "scene_data_v2",
        "name": "\u60c5\u666f\u6a21\u5f0f",
        "type": "Json",
        "values": "{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"
      },
      {
        "code": "countdown_1",
        "name": "\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_data",
        "name": "\u8c03\u8282\u63a7\u5236",
        "type": "Json",
        "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "rhythm_mode",
        "name": "\u751f\u7269\u8282\u5f8b",
        "type": "Raw",
        "values": "{\"maxlen\":\"255\"}"
      },
      {
        "code": "sleep_mode",
        "name": "\u5165\u7761",
        "type": "Raw",
        "values": "{\"maxlen\":\"255\"}"
      },
      {
        "code": "wakeup_mode",
        "name": "\u5524\u9192",
        "type": "Raw",
        "values": "{\"maxlen\":\"255\"}"
      },
      {
        "code": "remote_switch",
        "name": "\u9065\u63a7\u5668\u5f00\u5173",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1674448912842,
  "tid": "41ee73c89ad811ed89e112b09600735b"
}
Status of device: bfa02fd285cfec2bf7lesc
{
  "result": [
    {
      "code": "switch_led",
      "value": true
    },
    {
      "code": "work_mode",
      "value": "white"
    },
    {
      "code": "bright_value_v2",
      "value": 195
    },
    {
      "code": "temp_value_v2",
      "value": 74
    },
    {
      "code": "scene_data_v2",
      "value": "{\"scene_num\":1,\"scene_units\":[{\"bright\":200,\"h\":0,\"s\":0,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":13,\"unit_switch_duration\":14,\"v\":0}]}"
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "control_data",
      "value": ""
    },
    {
      "code": "rhythm_mode",
      "value": "AAAAAAA="
    },
    {
      "code": "sleep_mode",
      "value": "AAA="
    },
    {
      "code": "wakeup_mode",
      "value": "AAA="
    },
    {
      "code": "remote_switch",
      "value": true
    }
  ],
  "success": true,
  "t": 1674448913049,
  "tid": "420d92b19ad811ed89e112b09600735b"
}
Functions of device: bf153acf8b2e88888fnta9
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "desc": "switch 1",
        "name": "switch 1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "countdown 1",
        "name": "countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1674448913251,
  "tid": "422adc709ad811edbd98a6d801a7eabc"
}
Properties of device: bf153acf8b2e88888fnta9
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "\u5f00\u51731",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "name": "\u5f00\u51731\u5012\u8ba1\u65f6",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "name": "\u589e\u52a0\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"kwh\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "name": "\u5f53\u524d\u7535\u6d41",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "name": "\u5f53\u524d\u529f\u7387",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "name": "\u5f53\u524d\u7535\u538b",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1674448913586,
  "tid": "424a62529ad811ed97b7f276006a160b"
}
Status of device: bf153acf8b2e88888fnta9
{
  "result": [
    {
      "code": "switch_1",
      "value": true
    },
    {
      "code": "countdown_1",
      "value": 0
    },
    {
      "code": "add_ele",
      "value": 14
    },
    {
      "code": "cur_current",
      "value": 0
    },
    {
      "code": "cur_power",
      "value": 0
    },
    {
      "code": "cur_voltage",
      "value": 2406
    }
  ],
  "success": true,
  "t": 1674448913937,
  "tid": "4295fb819ad811edae3d265fe02d1603"
}

**Comment by Xenomes** [comment]
Hi, Thanks for the new json!
The devices are added to the develop branche, please let me know the result.
I saw that the gateway had a switch_alarm_sound switch do you think it useful?
