### ISSUE TITLE
Tuya RF+WIFI thermostat 

### ISSUE THREAD

**Issue by macb3** [Xenomes/Domoticz-TinyTUYA-Plugin#91]
Hello,

I have an issue with a Tuya RF+WIFI thermostat (Device ID 32022240c82b96168900)
After updating the TinyTUYA-Plugin to version="1.7.3",  I lost most functions in Domoticz for this device. There is only a power switch to see , but it does not work. 
Maybe you know a solution.
 I thank you in advance and thanks for running this project.

[dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/14182154/dump.json)

![32022240c82b96168900](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/146028426/46c5ecfa-f06e-46bd-bdc2-c00162fb32f1)

**Comment by Xenomes** [comment]
I see that your filter includes 'power,' which is the reason it only shows one device.
I have push a new version, can you check it out?

**Comment by macb3** [comment]
I pulled the new version, but no result, only powerswitch, not working.


![devices_tiny_tuya](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/146028426/003021f5-ef02-48a4-9950-c5068aabe873)

My main concern is to be able to operate the setpoint and the measured value of the temperature again in Domoticz
I compared the dump.json with an earlier printout (issue#61) and saw that it was different.

"code": "temp_set" changed in  "code": "TempSet",
"code": "Temp_Current", changed to  "code": "TempCurrent",
maybe this info will help.

Also screenshot of Tuya iot platform

![Tuya iot platform](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/146028426/c3695e94-7a27-4552-98bd-db9b3e9aecae)

**Comment by Xenomes** [comment]
```
"code": "temp_set" changed in "code": "TempSet",
"code": "Temp_Current", changed to "code": "TempCurrent",
maybe this info will help.
```
Thanks this helps a lot!

**Comment by Xenomes** [comment]
Can you checkout the Develop to test?
```
cd ~/domoticz/plugins/Domoticz-TinyTUYA-Plugin
git pull
git checkout Develop
sudo systemctl restart domoticz.service
```
To switch back to the Master version, change 'Develop' to 'Master'.

**Comment by macb3** [comment]
Thanks again,  your newly added code works.

![thermostaat](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/146028426/d274b41b-29e1-489e-b540-e2e202890307)

However, I just wonder how it is possible that the code on the device changed.

**Comment by Xenomes** [comment]
I don't know. This is the third time that a device functions names change. Maybe the manufactor/tuya or tinytuya. Did you update tinytuya recente?

**Comment by macb3** [comment]
I updated tiny tuya a few days ago, because there were glitches on several devices, after the update everything except the thermostat worked fine again. 
Fortunately, it now works again and why the code on the device changed remains unclear.
Thanks again for solving the problem.
