### ISSUE TITLE
No module named 'tinytuya'

### ISSUE THREAD

**Issue by varazir** [Xenomes/Domoticz-TinyTUYA-Plugin#92]
Hello, 

I'm running Domoticz in docker 
I have installed tinytuya and I can run `python -m tinytuya scan` without error 

```
2024-02-07 18:23:37.248 Error: TinyTUYA: (tinytuya) failed to load 'plugin.py', Python Path used was '/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages'.
2024-02-07 18:23:37.302 Error: TinyTUYA: Traceback (most recent call last):
2024-02-07 18:23:37.302 Error: TinyTUYA: File "/opt/domoticz/userdata/plugins/Domoticz-TinyTUYA-Plugin/plugin.py", line 59, in <module>
2024-02-07 18:23:37.302 Error: TinyTUYA: import tinytuya
2024-02-07 18:23:37.302 Error: TinyTUYA: ModuleNotFoundError: No module named 'tinytuya'
```

`python --version`
Python 3.11.2

**Comment by Xenomes** [comment]
You need to add the tinytuya install to the customstart.sh and rebuild you docker container.

**Comment by varazir** [comment]
> You need to add the tinytuya install to the customstart.sh and rebuild you docker container.

Okay, 

Added this to  /opt/domoticz/userdata

```
#!/bin/bash

if [ -f /opt/domoticz/FIRSTRUN ]; then
true
else
echo 'updating packages'
apt-get -qq update
echo 'installing tinytuya'
pip3 install requests==2.23.0 charset-normalizer==3.0.1 tinytuya -U
echo 'installing iputils-ping'
apt-get -y install iputils-ping
echo 'creating FIRSTRUN file so script can check on next run'
touch /opt/domoticz/FIRSTRUN
echo 'copying event script templates to external mapped storage /volume1/domoticz/scripts/templates'
cp -r /opt/domoticz/scripts/templates  /opt/domoticz/userdata/scripts
cd /opt/domoticz || return
fi
```

and ran 

docker-compose down
docker-compose up -d 

Still get the same error

**Comment by Xenomes** [comment]
I am not a docker user, i think you need to add a -y to say yes to the install.
```
pip3 install -y requests==2.23.0 charset-normalizer==3.0.1 tinytuya -U
```
Looking at the instructions, i see:
> Updating the image
> 
> From within the container folder issue:
> 
> ```
> docker-compose pull domoticz
> docker-compose down
> docker-compose up -d --remove-orphans
> docker image prune
> ```

**Comment by varazir** [comment]
I tried to install it manual using a bash session but it fails . I could try your way.

**Comment by varazir** [comment]
didn't help... I hade a good ide to run everything inside docker...

**Comment by Xenomes** [comment]
You could try: ```sudo docker exec -t domoticz pip install tinytuya```

**Comment by varazir** [comment]
I'm getting this 
https://gist.github.com/varazir/7a39293f14a98430468fa72c9c940049

**Comment by Xenomes** [comment]
Strange is did just do it to a new docker...
```
sudo docker exec -t domoticz pip install `tinytuya`
Collecting tinytuya
  Downloading tinytuya-1.13.1-py2.py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 3.3 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from tinytuya) (2.31.0)
Collecting cryptography
  Downloading cryptography-42.0.2-cp39-abi3-manylinux_2_28_x86_64.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 13.1 MB/s
Collecting colorama
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting cffi>=1.12
  Downloading cffi-1.16.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (443 kB)
     |████████████████████████████████| 443 kB 18.0 MB/s
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 15.6 MB/s
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->tinytuya) (3.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests->tinytuya) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->tinytuya) (2.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->tinytuya) (2024.2.2)
Installing collected packages: pycparser, cffi, cryptography, colorama, tinytuya
Successfully installed cffi-1.16.0 colorama-0.4.6 cryptography-42.0.2 pycparser-2.21 tinytuya-1.13.1
```

**Comment by varazir** [comment]
It's the domoticz docker ?

**Comment by varazir** [comment]
nvm I see you did, strange

**Comment by varazir** [comment]
I'm running on a raspberry pi 3

**Comment by Xenomes** [comment]
Yep 'domoticz/domoticz:stable' i am running it on 'Ubuntu 20.04.6 LTS' but docker container keep it the same a cross systems.

**Comment by varazir** [comment]
I tried with running  
` sudo docker exec -t domoticz pip cache purge`
Then tried the installation again but it fails again in the same way..

**Comment by Xenomes** [comment]
You can see maybe the error by using the logs.
```
sudo docker-compose down
sudo docker-compose up -d && sudo docker logs -f domoticz
```

**Comment by varazir** [comment]
The rerun file isn't there. 

I come to it fails on installing cffi 
And what I come to is that arm-linux-gnueabihf-gcc is missing. 
Strange is that I can install it outside the docker.

**Comment by Xenomes** [comment]
I edit the commit, i was wrong.

**Comment by varazir** [comment]
The logs say nothing, just that domoticz starts.

**Comment by Xenomes** [comment]
So you don't see the execution of customstart.sh?

**Comment by varazir** [comment]
no

**Comment by varazir** [comment]
I tried to with the stable docker image still same

**Comment by varazir** [comment]
Asked on the tinytuyya github  and got this 

https://github.com/jasonacox/tinytuya/blob/master/examples/Dockerfile

**Comment by Xenomes** [comment]
Ha yes, that is for the tinytuya webserver, that we don't use. If i have some time tonight i will try to create it on a rpi3b.

**Comment by varazir** [comment]
I tried to install the stuff manually but got the same error when I was trying to install cffi

**Comment by varazir** [comment]
I noticed that the domoticz docker using bullseye OS and I have installed bookworm

**Comment by Xenomes** [comment]
In the docker on the RPI3B i got the same error. Looks like the docker is missing something.

**Comment by Xenomes** [comment]
Found it! You need to add to the customstart.sh script before the install of tinytuya.
`pip install cryptography==3.1.1`

**Comment by varazir** [comment]
> Found it! You need to add to the customstart.sh script before the install of tinytuya. `pip install cryptography==3.1.1`

Hmm, tried that but I get this

root@23d127f220fb:/opt/domoticz# pip3 install cryptography==3.1.1 requests==2.23.0 charset-normalizer==3.0.1 tinytuya -U
Collecting cryptography==3.1.1
  Downloading cryptography-3.1.1.tar.gz (534 kB)
     |████████████████████████████████| 534 kB 1.4 MB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-vnvltys2/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"''
       cwd: None
  Complete output (75 lines):

error: command 'arm-linux-gnueabihf-gcc' failed: No such file or directory

**Comment by varazir** [comment]
I'm testing with something. so far I found out I need to install this

apt install libffi-dev build-essential pkg-config libssl-dev -y

**Comment by Xenomes** [comment]
Yes you are correct... i forgot about these 😅

**Comment by varazir** [comment]
This 3 lines are needed then: 
apt -qq update
apt install libffi-dev build-essential pkg-config libssl-dev -y
pip3 install cryptography==3.1.1 requests==2.23.0 charset-normalizer==3.0.1 tinytuya -U

**Comment by Xenomes** [comment]
If it works i can add a docker section to the install 😆

**Comment by varazir** [comment]
Do you understand where I should save that file ?

It just say userdata 

/opt/domoticz/userdata  ?

trying out this 

if [ -f /opt/domoticz/FIRSTRUN ]; then
true
else
echo 'updating packages'
apt-get -qq update
echo 'Install lbs needed for tinytuy'
apt install libffi-dev build-essential pkg-config libssl-dev -y
echo 'installing tinytuya'
pip3 install -y cryptography==3.1.1 requests==2.23.0 charset-normalizer==3.0.1 tinytuya -U
echo 'installing iputils-ping'
apt-get -y install iputils-ping
echo 'creating FIRSTRUN file so script can check on next run'
touch /opt/domoticz/FIRSTRUN
echo 'copying event script templates to external mapped storage /volume1/domoticz/scripts/templates'
cp -r /opt/domoticz/scripts/templates  /opt/domoticz/userdata/scripts
cd /opt/domoticz || return
fi

**Comment by varazir** [comment]
can't see that the script is running

**Comment by varazir** [comment]
I run this:

`docker exec -it domoticz bash`
`apt update && apt install libffi-dev build-essential pkg-config libssl-dev -y && pip3 install cryptography==3.1.1 requests==2.23.0 charset-normalizer==3.0.1 tinytuya -U`

And checked it in Domoticz and the plugin is working.

**Comment by Xenomes** [comment]
Nice! That script need to be in opt/domoticz/userdata of the local volume.

**Comment by varazir** [comment]
From the composer file 

    volumes:
      - ./config:/opt/domoticz/userdata

Should I save it in config folder or create a new folder and call it userdata in the domoticz folder ?
I tried both  when I restart the docker nothing shows

**Comment by Xenomes** [comment]
Then the file need to be in the ./config i used a other instruction to use /opt/domoticz. I have now used the instruction on Domoticz, i see you found the missing ' to.
![afbeelding](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11648297/2bc3167b-3111-458a-9d11-a1d80e26d6fc)

**Comment by Xenomes** [comment]
I made some changes to the Develop version for Bookworm, are you able to test?

**Comment by varazir** [comment]
As the docker is 3.9 and buster not sure what it will do?
It's running fine now so I'm planing to switch out my old installation of domoticz with this setup I tested on my backup RPi.

**Comment by Xenomes** [comment]
Okay. Thank you, then i close the issue.
