### ISSUE TITLE
Add airconditioner ?

### ISSUE THREAD

**Issue by TokTias** [Xenomes/Domoticz-TinyTUYA-Plugin#94]
Hi !
Can you include support for my airconditioner ?
dump.json attached here.

Thanks in advance !
/Mathias

[dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/14310372/dump.json)

**Comment by Xenomes** [comment]
Hi TokTias, The device is added to version 1.7.7

**Comment by TokTias** [comment]
Works fine now, thanks a lot !

**Comment by Xenomes** [comment]
Perfect! Thank for the feed back!
