### ISSUE TITLE
Plugin not work

### ISSUE THREAD

**Issue by ikino** [Xenomes/Domoticz-TinyTUYA-Plugin#95]
Hello

after few days plugin stop working. I don't know why. This is in logs:

```
2024-02-18 19:29:06.757 TUYA: Device count: 0
2024-02-18 19:29:06.828 Zigbee 2 MQTT Raspberry Pi: Zigbee2mqtt bridge is online
2024-02-18 19:29:06.842 Zigbee 2 MQTT Raspberry Pi: Received available devices list from bridge
2024-02-18 19:29:06.323 Status: Zigbee 2 MQTT Raspberry Pi: Initialized version 3.2.0-beta
2024-02-18 19:29:06.754 Status: TUYA: Initialized version 1.7.7, author 'Xenomes'
2024-02-18 19:29:07.519 Zigbee 2 MQTT Raspberry Pi: Received available devices groups from bridge
2024-02-18 19:29:07.519 Zigbee 2 MQTT Raspberry Pi: Joining new devices is enabled on the zigbee bridge
2024-02-18 19:29:08.509 TUYA: Heartbeat interval set to: 10.
2024-02-18 19:29:08.509 Error: TUYA: handleThread: string indices must be integers, not 'str' line 752
2024-02-18 19:29:13.067 TUYA: onHeartbeat called
2024-02-18 19:29:13.067 TUYA: onHeartbeat called skipped
2024-02-18 19:29:23.084 TUYA: onHeartbeat called 
```

**Comment by Xenomes** [comment]
Hi ikino, is see "TUYA: Device count: 0" and line 752 is the line where the data is read from the tuya server. Looks like there is a problem with the connection or the subscription has ended.

**Comment by ikino** [comment]
Xenomes, thanks for your reply. I checked tuya page and all looks ok. I have a project with access id / secret, I see devices in devices tab. I tried to put a different device id in the plugin settings and it didn't help.

**Comment by Xenomes** [comment]
In version 1.7.9 i have updated the tools/debug_discovery.py to test the connection to Tuya, can you run it or run the 'python3 -m tinytuya wizard'

**Comment by ikino** [comment]
```
./debug_discovery.py --region EU --apikey xxx --apisecret xxx --deviceid xxx
Script is running, please wait!
Error getting device list: 'str' object does not support item assignment
```

**Comment by ikino** [comment]
variable devices from tuya_cloud.getdevices() returns:
{'Error': 'Error Response from Tuya Cloud', 'Err': '913', 'Payload': "Error from Tuya Cloud: Code 28841002: 'No permissions. Your subscription to cloud development plan has expired.'"}

so, it's clear now... what i do to do working it? why is expired? i use free account on tuya.

it would be good to write the error message sent by tuya in the log so that it is immediately clear what the problem is.

**Comment by Xenomes** [comment]
There is some code in the plugin, but i can't test it, my account is 3 years old and never has beeing expired. Think I know where the error message is stored but not 100% sure.
You could test it if you want 😅

Open Python3 and copy line by line the code in, replace the xxxx with your credentials, 
```python
import tinytuya
tuya = tinytuya.cloud(apiRegion="eu", apiKey="xxxxxxxxxxxxxxxxxxxx", apiSecret="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", apiDeviceID="xxxxxxxxxxxxxxxxxx")
tuya.error
tuya.token
```
I am interested in the output of tuya.error and tuya.token if there is error message 😆

**Comment by ikino** [comment]
No error message. Only token.

```
>>> import tinytuya
>>> tuya = tinytuya.Cloud(apiRegion="eu", apiKey="xxx", apiSecret="xxx", apiDeviceID="xxx")
>>> tuya.error
>>> tuya.token
'xxxxxxxxxxxxxxxxxxxx'

```

**Comment by ikino** [comment]
I found in Tuya platfotm so "The contract has expired."

**Comment by Xenomes** [comment]
Thanks then i know the error is empty... Thank you!!
In the Readme there is a link to the request form.

**Comment by ikino** [comment]
@Xenomes Thank you for help. I extend trial by 6 months, now it works.
But, it's be fine when plugin show warning about it, it's only few lines to add to code. :+1:

**Comment by Xenomes** [comment]
Perfect!
