### ISSUE TITLE
Add a humidifier ?

### ISSUE THREAD

**Issue by TokTias** [Xenomes/Domoticz-TinyTUYA-Plugin#96]
Hi and thanks again for helping me earlier with adding support for my AC unit.
I now how yet another Tuya device in my network, a air humidifier (see attached json dump).
I just hope it might be added too please ?

Cheers and thanks in advance !
[Humidifier_dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/14324533/Humidifier_dump.json)

**Comment by Xenomes** [comment]
Hi TokTias,

There is no data to work with:
```
{
  "result": {
    "category": "jsq"
  },
  "success": true,
  "t": 1708292482950,
  "tid": "75ac1c85cea611eeaa88e22b04041d75"
}
Status of device: ebac01bd5555d9cd15jwpo
{
  "result": [],
  "success": true,
  "t": 1708292484005,
  "tid": "764e1ac0cea611eea1f20ed40d2f8029"
}
```
Did you change the device to 'DP instruction'?

**Comment by TokTias** [comment]
Hi !
Not sure what you mean by changing the device to DP instruction ?
I managed to squeeze ut a tiny bit more by using  tinytuya wizard (see attached json). I'm however not sure if it's of any use though...

/T
[snapshot.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/14351922/snapshot.json)

**Comment by Xenomes** [comment]
The instructions you can find on the last three pages in pdf link in the README.md

**Comment by TokTias** [comment]
Alright ! I think we've got something now.

Cheers !
/T
[Humidifier_DP_dump.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/files/14352018/Humidifier_DP_dump.json)

**Comment by Xenomes** [comment]
Did you try to reload the plugin in Domoticz?

**Comment by TokTias** [comment]
I restarted domoticz and now the humidifier shows up, but it seems to be a copy (same parameters with other name) as my A(C that you helped me to add a day ago.
I have two instances of TinyTUYA (Cloud) HW in domoticz with the corresponding DeviceID for each (A(/C and humidifier).
Might be something wrong from my part, I'll investigate and let you know.

**Comment by Xenomes** [comment]
> I have two instances of TinyTUYA (Cloud) HW in domoticz with the corresponding DeviceID for each (A(/C and humidifier).

That is not needed. The DeviceID is there to detect other devices. I will load your latest dump tonight in my test system and see what is needed  to correct.
