### ISSUE TITLE
adding battery power % to illumination device

### ISSUE THREAD

**Issue by countcobolt** [Xenomes/Domoticz-TinyTUYA-Plugin#98]
hi all

I have added a ldgc illuminiation sensor in the plugin. It correctly now shows as an illumination device. Yet , I would be interested to also see the battery percentage.  Is this something that can be added?

I could not get the dump.json from my docker, but below is the output
List of devices: 
[
  {
    "name": "Illumination sensor",
    "id": "bf46b76e86b7080f68nboe",
    "key": "Deleted",
    "mac": "a8:80:55:09:38:b6",
    "uuid": "8cadb024ef232110",
    "sn": "10009960800140",
    "category": "ldcg",
    "product_name": "Illumination sensor",
    "product_id": "c7aae5w9tasun5ma",
    "biz_type": 18,
    "model": "XFY-CGQ-WFGZL",
    "sub": false,
    "icon": "https://images.tuyaeu.com/smart/icon/ay1526384154502LQz2a/1656395340e99d8a1b6ed.jpg"
  }
]
Properties of device: bf46b76e86b7080f68nboe
{
  "result": {
    "category": "ldcg",
    "status": [
      {
        "code": "bright_value",
        "name": "\u5f53\u524d\u4eae\u5ea6\u503c",
        "type": "Integer",
        "values": "{\"unit\":\"LUX\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "battery_state",
        "name": "\u7535\u6c60\u7535\u91cf\u72b6\u6001",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "battery_percentage",
        "name": "\u7535\u6c60\u7535\u91cf",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1708419749871,
  "tid": "c6abb504cfce11ee9d7cfe8b4d072f7e"
}
Status of device: bf46b76e86b7080f68nboe
{
  "result": [
    {
      "code": "bright_value",
      "value": 2435
    },
    {
      "code": "battery_state",
      "value": "middle"
    },
    {
      "code": "battery_percentage",
      "value": 60
    }
  ],
  "success": true,
  "t": 1708419750030,
  "tid": "c6c2cd07cfce11ee909eda03510e4af7"
}50030,
  "tid": "c6c2cd07cfce11ee909eda03510e4af7"
}

thanks!

**Comment by Xenomes** [comment]
Hi,
No problem with the output, device is added in 1.7.9, and the battery state is visible in Domoticz.
![afbeelding](https://github.com/Xenomes/Domoticz-TinyTUYA-Plugin/assets/11648297/9e0e5184-ef6d-43e4-8833-13a189f25924)
